/**
 * GENERATED by pnpm exec tsx scripts/generate-solver-map.ts (MADR 0061 d4).
 *
 * Do not hand-edit: the map resolves every stationRole solver package of the
 * mouth station to its one exported solver module. The registry is the
 * only package allowed to import solver packages (solver-importer allowlist).
 */
import { mouthClosedformSolver } from "@openclinxr/station-mouth-solver-closedform";
import type { SolverModule } from "@openclinxr/station-mouth-objective";

/** Every mouth-station solver module the registry may resolve by pin. */
export const mouthSolverModules: readonly SolverModule[] = [
  mouthClosedformSolver,
];
