/**
 * Public interface of @openclinxr/session-state.
 *
 * Named lists, not `export *`. A star republishes a module wholesale, so a symbol added inside
 * becomes public with nobody deciding it should be. Generated by `pnpm arch:narrow-entrypoint`
 * from what the tree actually consumes, then proved by `pnpm packages:typecheck:agent`.
 */
export type {
  ActorInteractionState,
  ActorMemory,
  ActorModelContext,
  ActorRuntimeState,
  ActorTransformState,
  AsyncDurableMultiActorSessionStore,
  ClinicalOrderState,
  CreateMultiActorClinicalSessionInput,
  DurableClinicalEventRecord,
  DurableClinicalEventReviewProjection,
  DurableConversationTurnRecord,
  DurableEmotionalStateTimelineRecord,
  DurableMultiActorSessionStore,
  DurableStorePosture,
  InteractionLogEntry,
  InteractionRoutingReason,
  InteractionTurnSource,
  MultiActorClinicalSession,
  MultiActorPersistencePhase2Strategy,
  PersistenceSpikeStores,
  RealtimeCacheStorePosture,
  RealtimeSessionCache,
  RealtimeSessionCacheSnapshot,
  RealtimeSessionCacheTurnRef,
  RecordClinicalActionInput,
  RouteActorInteractionInput,
  RouteActorInteractionResult,
  RouteActorInteractionSourceInput,
  TextInteractionSource,
  UpdateActorSpatialStateInput,
  Vector3,
  VoiceTranscriptInteractionSource,
  WriteRealtimeCacheSnapshotInput,
} from "./types.js";
export {
  buildActorModelContext,
  createMultiActorClinicalSession,
  createPersistenceSpikeStores,
  evaluateMultiActorPersistencePhase2Strategy,
  persistLatestInteractionTurn,
  recordClinicalAction,
  rehydrateRealtimeCacheFromDurableState,
  routeActorInteraction,
  updateActorSpatialState,
  writeRealtimeCacheSnapshot,
} from "./session-core.js";
export {
  createDurableExamFormEncounterBundlePins,
  durableExamStationEncounterBundlePinClaimScope,
  durableExamStationEncounterBundlePinNotEvidenceFor,
  launchPinnedStationAssetsFromPort,
} from "./encounter-bundle-selection/index.js";
export type {
  DurableExamFormEncounterBundlePins,
  DurableExamStationEncounterBundlePin,
  ExamFormEncounterBundlePinPersistencePort,
  LaunchPinnedStationAssetsInput,
  LaunchPinnedStationAssetsResult,
  PersistExamFormEncounterBundlePinsInput,
} from "./encounter-bundle-selection/index.js";
export {
  projectDurableClinicalEventForReview,
} from "./internal.js";
