/**
 * issue-291 — actor phenotype export.
 *
 * The encounter specification (scenario fixture actor record) is the home for
 * authored clinical/cosmetic phenotype. This module deterministically extracts
 * the authored `phenotype` from every fixture actor into a committed JSON export
 * that the asset factory's Python generator reads (orchestrate_character.py →
 * generate_mesh.py). Authoring a case = authoring a fixture actor; the export is
 * regenerated by a CLI and guarded against drift by actor-phenotype-export.test.ts.
 *
 * issue-293: actors WITHOUT an authored phenotype are resolved through the
 * descriptor -> numeric lookup (descriptor-phenotype-lookup.ts) when the case
 * states a mappable clinical descriptor. Derived entries carry
 * `descriptor_derived: true`; they are deterministic, never invented identity.
 *
 * Pipeline-only knobs (seed, output_name, anny_topology, sleeveGeometryExpansion)
 * are NOT authored here — they stay in the generator. See
 * .openclinxr/evidence/issue-291/phenotype-field-inventory.json for the per-field
 * home classification.
 */

import type { Scenario } from "@openclinxr/shared-schemas";

import { derivePhenotypeFromDescriptors } from "./descriptor-phenotype-lookup.js";
import { edChestPainScenarioV2 } from "./ed-chest-pain.js";
import { scenarioBank } from "./scenario-bank.js";

export const ACTOR_PHENOTYPE_EXPORT_SCHEMA_VERSION = "openclinxr.actor-phenotype.v1";

export type ActorPhenotypeExportEntry = {
  role: string;
  phenotype: Record<string, unknown>;
};

export type ActorPhenotypeExport = {
  schemaVersion: typeof ACTOR_PHENOTYPE_EXPORT_SCHEMA_VERSION;
  source: string;
  entries: Record<string, Record<string, ActorPhenotypeExportEntry>>;
};

/** The full shipped fixture population (bank + the separately exported ED v2). */
export function actorPhenotypeFixturePopulation(): Scenario[] {
  return [...scenarioBank, edChestPainScenarioV2];
}

/**
 * Deterministic extraction: one entry per actor that authors a non-empty
 * `phenotype`. Output is stable (no timestamps) so the committed export can be
 * diffed against a regeneration.
 */
export function buildActorPhenotypeExport(): ActorPhenotypeExport {
  const entries: Record<string, Record<string, ActorPhenotypeExportEntry>> = {};
  for (const scenario of actorPhenotypeFixturePopulation()) {
    const caseEntries: Record<string, ActorPhenotypeExportEntry> = {};
    for (const actor of scenario.actors ?? []) {
      const authored = actor.phenotype;
      if (authored !== undefined && Object.keys(authored).length > 0) {
        caseEntries[actor.actorId] = {
          role: actor.role,
          phenotype: { ...authored },
        };
        continue;
      }
      // issue-293: no authored phenotype — resolve the actor's clinical
      // descriptors through the seeded lookup, or leave the case refused.
      const derived = derivePhenotypeFromDescriptors(scenario, actor);
      if (derived !== undefined) {
        caseEntries[actor.actorId] = {
          role: actor.role,
          phenotype: derived,
        };
      }
    }
    if (Object.keys(caseEntries).length > 0) {
      entries[scenario.scenarioId] = caseEntries;
    }
  }
  return {
    schemaVersion: ACTOR_PHENOTYPE_EXPORT_SCHEMA_VERSION,
    source: "packages/openclinxr/scenario-fixtures/src (scenarioBank + edChestPainScenarioV2); regenerate via pnpm exec tsx tools/openclinxr/dark-factory/export-actor-phenotype.ts",
    entries,
  };
}

export function serializeActorPhenotypeExport(
  exported: ActorPhenotypeExport = buildActorPhenotypeExport(),
): string {
  return `${JSON.stringify(exported, null, 2)}\n`;
}
