/**
 * Public interface of @openclinxr/scenario-fixtures.
 *
 * Named lists, not `export *`. A star republishes a module wholesale, so a symbol added inside
 * becomes public with nobody deciding it should be. Generated by `pnpm arch:narrow-entrypoint`
 * from what the tree actually consumes, then proved by `pnpm packages:typecheck:agent`.
 */

export type {
  AuthoredUtteranceRecord,
} from "./authored-utterance-record-mod.js";
export {
  affectForAuthoredRecord,
  keywordAffectFallbackFromText,
  PEDS_ASTHMA_SCENARIO_ID,
  resolveAuthoredUtteranceRecord,
} from "./authored-utterance-record-mod.js";
export {
  clinicKneePainScenario,
} from "./clinic-knee-pain.js";
export type {
  DialogueFixtureSeed,
} from "./ed-chest-pain-mod.js";
export {
  edChestPainDialogueSeeds,
  edChestPainScenario,
  edChestPainScenarioV2,
  edChestPainScenarioV3,
} from "./ed-chest-pain-mod.js";
export {
  pediatricAsthmaScenario,
} from "./pediatric-asthma.js";
export {
  scenarioBank,
  scenarioDialogueSeedBank,
} from "./scenario-bank.js";
export {
  buildDynamicEncounterFactoryPlanningProjection,
  buildDynamicEncounterFactoryProjectionArtifact,
  buildScenarioBankExamSequenceProjection,
  createLearnerScenarioView,
  evaluateScenarioBankMaturity,
  variantScenarioBank,
} from "./scenario-bank-maturity.js";
