/**
 * Public interface of @openclinxr/scenario-fixtures.
 *
 * Named lists, not `export *`. A star republishes a module wholesale, so a symbol added inside
 * becomes public with nobody deciding it should be. Generated by `pnpm arch:narrow-entrypoint`
 * from what the tree actually consumes, then proved by `pnpm packages:typecheck:agent`.
 */
export {
  edChestPainDialogueSeeds,
  edChestPainScenario,
  edChestPainScenarioV2,
  edChestPainScenarioV3,
} from "./ed-chest-pain.js";
export type {
  DialogueFixtureSeed,
} from "./ed-chest-pain.js";
export {
  adultAbdominalPainScenario,
} from "./adult-abdominal-pain.js";
export {
  pediatricAsthmaDialogueSeeds,
  pediatricAsthmaScenario,
} from "./pediatric-asthma.js";
export {
  PEDS_ASTHMA_SCENARIO_ID,
  PEDS_CREDIBILITY_VETO_ROLES,
  affectForAuthoredRecord,
  firstNameFromDisplayName,
  keywordAffectFallbackFromText,
  learnerVisibleAuthoredCaption,
  resolveAuthoredUtteranceRecord,
} from "./authored-utterance-record.js";
export type {
  AuthoredUtteranceRecord,
} from "./authored-utterance-record.js";
export {
  clinicKneePainScenario,
} from "./clinic-knee-pain.js";
export {
  findScenarioFixtureById,
  responseClipForBodyRegion,
  scenarioBank,
  scenarioDialogueSeedBank,
} from "./scenario-bank.js";
export {
  buildDynamicEncounterFactoryPlanningProjection,
  buildDynamicEncounterFactoryProjectionArtifact,
  buildScenarioBankExamSequenceProjection,
  createLearnerScenarioView,
  evaluateScenarioBankMaturity,
  variantScenarioBank,
} from "./scenario-bank-maturity.js";
export type {
  DynamicEncounterFactoryPlanningProjection,
  DynamicEncounterFactoryPlanningScenario,
} from "./scenario-bank-maturity.js";
