/**
 * Public interface of @openclinxr/xr-locomotion.
 *
 * Named lists, not `export *`. A star republishes a module wholesale, so a symbol added inside
 * becomes public with nobody deciding it should be. Generated by `pnpm arch:narrow-entrypoint`
 * from what the tree actually consumes, then proved by `pnpm packages:typecheck:agent`.
 */
export {
  applyLocomotion,
  createKeyboardLocomotion,
  createXrHandGestureLocomotionState,
  createXrHandSelectState,
  formatHandSelectStatus,
  isLocomotionVectorActive,
  isXrHandPinching,
  maybeCompleteTraceActionFromHandSelect,
  recordHandSelectTraceLatency,
  sampleRoomScalePose,
} from "./locomotion.js";
export {
  applyDeterministicPortalPreviewStart,
  buildExamineeLocomotionEvidence,
  createExamineeLocomotionTrail,
  formatPortalTransitionEvidence,
  PORTAL_THRESHOLD_Z,
  parsePortalPreviewStart,
  updateExamineeLocomotionTrail,
  updatePortalTransitionEvidence,
  updateReusableExteriorAnteroomVisibility,
} from "./portal-trail.js";
export {
  applyGeneratedHumanoidRoleSpecificPosture,
} from "./role-posture.js";
export type {
  ExamineeLocomotionEvidence,
  PortalTransitionContext,
  PortalTransitionEvidence,
  RolePostureContext,
  XrHandGroup,
  XrInputSourceWithGamepad,
  XrSessionLike,
} from "./types.js";
