/**
 * Public interface of @openclinxr/xr-pose.
 *
 * Named lists, not `export *`. A star republishes a module wholesale, so a symbol added inside
 * becomes public with nobody deciding it should be. Generated by `pnpm arch:narrow-entrypoint`
 * from what the tree actually consumes, then proved by `pnpm packages:typecheck:agent`.
 */
export {
  describeRuntimeBundleScenarioMatch,
  resolveEffectiveVerticalOffsetMeters,
} from "./actor-floor-composition-mod.js";
export type { OwnedChain } from "./chain-ownership.js";
// The chain-ownership seam a motion executor declares against. Named, not a star: this file's
// header says a star republishes a module wholesale.
export { boneIsOwned } from "./chain-ownership.js";
export {
  applyBoneEuler,
  applyGeneratedHumanoidClinicalIdlePosture,
  applyHumanoidJointRotationsByAlias,
  MPFB_CLINICAL_IDLE_ARM_HANG,
  MPFB_IDLE_FORELARM_BEND_FRACTION,
  mpfbForearmIdleEuler,
} from "./clinical-idle-posture.js";
export {
  holdSupinePlantFrame,
} from "./hob-body-align.js";
export {
  measureBackToDeckGap,
  measureHeadPillowGapMeters,
  measurePelvisOnSeat,
  measureSeatClearanceMeters,
  readBackSectionPlane,
  settleSupineOntoBackSection,
  settleSupineOntoBackSectionPreservingSeat,
} from "./hob-contact-metrics.js";
export {
  collectJointNames,
  findBonesBySanitisedName,
  resolveRotationMap,
  sanitiseBoneName,
} from "./pose-bone-runtime.js";
export {
  applyPosturePose,
  plantSeatedPelvisOnSeat,
} from "./seated-pose.js";
export {
  applyMpfb2SeatedFold,
} from "./seated-pose-mpfb2.js";
export {
  animatedTranslationBoneNames,
  seatedRoleClipIsPlayable,
} from "./seated-role-clip-policy.js";
export {
  applyAndPlantSupineOnDeck,
  applySupinePoseHoldingIncline,
  readSupineTorsoWorldDeg,
  reapplySupineHeadToStoredPillow,
} from "./supine-deck-plant.js";
export {
  applySupinePose,
} from "./supine-pose.js";
