/**
 * Public interface of @openclinxr/xr-pose.
 *
 * Named lists, not `export *`. A star republishes a module wholesale, so a symbol added inside
 * becomes public with nobody deciding it should be. Generated by `pnpm arch:narrow-entrypoint`
 * from what the tree actually consumes, then proved by `pnpm packages:typecheck:agent`.
 */
export {
  MAX_FLOAT_METERS,
  MAX_SINK_METERS,
  describeRuntimeBundleScenarioMatch,
  resolveEffectiveVerticalOffsetMeters,
} from "./actor-floor-composition.js";
export {
  LIBRARY_CLINICAL_IDLE_ARM_HANG,
  MIXAMO_CLINICAL_IDLE_ARM_HANG,
  MPFB_CLINICAL_IDLE_ARM_HANG,
  MPFB_IDLE_FORELARM_BEND_FRACTION,
  applyBoneEuler,
  applyGeneratedHumanoidClinicalIdlePosture,
  applyHumanoidJointRotationsByAlias,
  mpfbForearmIdleEuler,
} from "./clinical-idle-posture.js";
export {
  holdSupinePlantFrame,
  lowerSupineBodyOntoDeck,
  settleSupineFloatOntoDeck,
} from "./hob-body-align.js";
export {
  measureBackToDeckGap,
  measureHeadPillowGapMeters,
  measurePelvisOnSeat,
  measureSeatClearanceMeters,
  readBackSectionPlane,
  settleSupineOntoBackSection,
  settleSupineOntoBackSectionPreservingSeat,
} from "./hob-contact-metrics.js";
export {
  findSupineBone,
} from "./hob-extremity-flex.js";
export {
  collectJointNames,
  findBonesBySanitisedName,
  resolveRotationMap,
  sanitiseBoneName,
} from "./pose-bone-runtime.js";
export type {
  PoseRotation,
} from "./pose-bone-runtime.js";
export {
  SEATED_CLIP_NAME,
  STANDING_CLIP_NAME,
  applyPosturePose,
  plantSeatedFeetNearFloor,
  plantSeatedPelvisOnSeat,
  restSeatedHandsOnThighs,
} from "./seated-pose.js";
export {
  applyMpfb2SeatedFold,
  isMpfb2Rig,
} from "./seated-pose-mpfb2.js";
export {
  animatedTranslationBoneNames,
  seatedRoleClipIsPlayable,
} from "./seated-role-clip-policy.js";
export {
  applyAndPlantSupineOnDeck,
  applySupinePoseHoldingIncline,
  plantSupineBodyOnDeck,
  readSupineTorsoWorldDeg,
  reapplySupineHeadToStoredPillow,
} from "./supine-deck-plant.js";
export {
  applySupinePose,
} from "./supine-pose.js";
export type {
  ApplySupinePoseOptions,
} from "./supine-pose.js";

// The chain-ownership seam a motion executor declares against. Named, not a star: this file's
// header says a star republishes a module wholesale.
export { boneIsOwned } from "./chain-ownership.js";
export type { OwnedChain } from "./chain-ownership.js";
