import { existsSync, readdirSync, readFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Fabricated stand-in ratchet (ArchUnit-style; "an app never gains a fake dependency").
 *
 * WHY: two slices of the composition-root migration were discarded after a worker
 * moved code into a package and, at the new call site, supplied a FAKE for a
 * dependency instead of the real one. Both passed every gate that existed:
 *
 *   cellix-m16  `shell: shell as unknown as Group` and
 *               `input.equipmentPlan.forEach(() => {});` — the emptied loop is where
 *               ~150 lines of clinical-panel refresh went, inside a diff that
 *               appeared to save 722 lines.
 *   cellix-m18  `registerReactiveProp: (propId, group) => { /* no-op in main *\/ }`
 *               while the real implementation stayed in main.ts.
 *
 * Both were found by reading the diff by hand. The ui-xr suite, the build, the
 * typecheck and knip were all green on both trees, because a no-op IS a valid
 * function and a cast IS valid TypeScript. Nothing mechanical objected.
 *
 * WHAT IS COUNTED, per app source file:
 *   emptyArrows — an arrow function whose body is empty or holds only a comment.
 *                 This is the shape a discarded dependency takes.
 *   casts       — `as any` / `as unknown as`, the shape a fabricated value takes
 *                 when it has to satisfy a moved signature.
 *
 * EXCLUDED: `(window as any).__openClinXr…`. Attaching evidence to the window object
 * is an established idiom across the XR runtime, it is not a stand-in for a moved
 * dependency, and without this exclusion the rule flags cellix-m17 — a slice that
 * passed its contract and landed. Measured, not assumed.
 *
 * VALIDATION against the 12 slices of this migration that have a verdict:
 *   flagged 0 of the 7 that passed their contract (m4, m5, m6, m7, m12, m13, m17);
 *   flagged BOTH that were discarded for fabricated stand-ins (m16 +2, m18 +1);
 *   flagged m14 (+22), which failed its contract for other reasons.
 * NOT TESTED: a fabrication that REUSES an existing site keeps the count flat and is
 * not detected. m11 and m15 failed their contracts without moving the count, so they
 * are neither support nor counter-evidence.
 *
 * RATCHET SEMANTICS (same as checks/file-size-budgets.ts):
 *   Counts are frozen at the current measurement and may only FALL. A new stand-in
 *   raises a count and fails the gate. The fix is to pass the real dependency, never
 *   to raise the number.
 */

export type StandInCounts = { emptyArrows: number; casts: number };

/** An arrow function with an empty or comment-only body. */
const EMPTY_ARROW = /=>\s*\{\s*(?:\/\*[\s\S]*?\*\/|\/\/[^\n]*)?\s*\}/;

/** A cast that makes a value satisfy a signature it does not naturally satisfy. */
const CAST = /\bas\s+any\b|\bas\s+unknown\s+as\b/;

/** Evidence attachment to the window object — an idiom, not a stand-in. See WHY above. */
const WINDOW_EVIDENCE = /\(\s*window\s+as\s+(?:any|unknown\s+as\s+[\w<>[\]]+)\s*\)|window\s+as\s+unknown\s+as/;

const APP_SCAN_ROOTS = ["apps"] as const;

/**
 * Frozen counts, one entry per app file that currently holds at least one site.
 * Generated by running measureStandInSites() against a clean tree. Entries may only
 * be LOWERED or REMOVED; never add one to excuse a new stand-in.
 */
export const STAND_IN_FREEZE: Record<string, StandInCounts> = {
  "apps/api/src/app.test.ts": { emptyArrows: 0, casts: 1 },
  "apps/arena/model-vetting-studio/src/pipeline-admin/jsdom-setup.ts": { emptyArrows: 4, casts: 0 },
  "apps/arena/model-vetting-studio/src/pipeline-admin/pipeline-admin-app.test.tsx": { emptyArrows: 0, casts: 1 },
  "apps/arena/model-vetting-studio/src/pipeline-admin/pipeline-admin-data.test.ts": { emptyArrows: 0, casts: 3 },
  "apps/arena/model-vetting-studio/src/pipeline-admin/preview-bridge.ts": { emptyArrows: 0, casts: 2 },
  "apps/arena/model-vetting-studio/src/pipeline-admin/promote-panel.test.tsx": { emptyArrows: 0, casts: 2 },
  "apps/arena/ui-xr-iwsdk-spike/src/uikitml-spatial-text.ts": { emptyArrows: 0, casts: 1 },
  "apps/ui-admin/src/App.test.tsx": { emptyArrows: 0, casts: 1 },
  "apps/ui-admin/src/api-client.test.ts": { emptyArrows: 0, casts: 1 },
  "apps/ui-admin/src/api-client.ts": { emptyArrows: 0, casts: 2 },
  "apps/ui-admin/src/the-scenario-edit-invalidates-stale-faculty-approval.test.tsx": { emptyArrows: 0, casts: 7 },
  "apps/ui-xr/src/lighting-rig-runtime.test.ts": { emptyArrows: 1, casts: 4 },
  "apps/ui-xr/src/main.ts": { emptyArrows: 1, casts: 23 },
};

function findWorkspaceRoot(): string {
  let dir = dirname(fileURLToPath(import.meta.url));
  for (let i = 0; i < 12; i += 1) {
    try {
      readFileSync(join(dir, "pnpm-workspace.yaml"));
      return dir;
    } catch {
      dir = dirname(dir);
    }
  }
  throw new Error("workspace root (pnpm-workspace.yaml) not found");
}

/** Count the stand-in sites in one source text. Exported so the test can drive it directly. */
export function countStandInSites(text: string): StandInCounts {
  let emptyArrows = 0;
  let casts = 0;
  for (const line of text.split("\n")) {
    if (WINDOW_EVIDENCE.test(line)) continue;
    if (EMPTY_ARROW.test(line)) emptyArrows += 1;
    if (CAST.test(line)) casts += 1;
  }
  return { emptyArrows, casts };
}

/** Every app source file holding at least one site, keyed by workspace-relative path. */
export function measureStandInSites(): Record<string, StandInCounts> {
  const root = findWorkspaceRoot();
  const found: Record<string, StandInCounts> = {};
  const walk = (dir: string): void => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = join(dir, entry.name);
      if (entry.isDirectory()) {
        if (!/node_modules$|[/\\]dist$/.test(full)) walk(full);
        continue;
      }
      if (!/\.(ts|tsx)$/.test(entry.name)) continue;
      if (/\.d\.ts$/.test(entry.name)) continue;
      const counts = countStandInSites(readFileSync(full, "utf8"));
      if (counts.emptyArrows > 0 || counts.casts > 0) found[relative(root, full)] = counts;
    }
  };
  for (const scanRoot of APP_SCAN_ROOTS) {
    const start = join(root, scanRoot);
    if (existsSync(start)) walk(start);
  }
  return found;
}

export type StandInViolation = { file: string; detail: string };

/**
 * One violation per app file whose stand-in count EXCEEDS its frozen entry, and one
 * per file that holds sites without a frozen entry at all.
 */
export function checkStandInFreeze(
  freeze: Record<string, StandInCounts> = STAND_IN_FREEZE,
  measured: Record<string, StandInCounts> = measureStandInSites(),
): StandInViolation[] {
  const violations: StandInViolation[] = [];
  for (const [file, counts] of Object.entries(measured)) {
    const frozen = freeze[file];
    if (!frozen) {
      violations.push({
        file,
        detail:
          `${file}: ${counts.emptyArrows} empty-arrow / ${counts.casts} cast site(s) in a file with no frozen entry. ` +
          "An empty arrow body and an `as any` are the two shapes a FABRICATED DEPENDENCY takes when code moves " +
          "into a package: cellix-m16 and cellix-m18 were both discarded for exactly this, and both were green on " +
          "tests, build, typecheck and knip. FIX: pass the real dependency. Do NOT add a freeze entry.",
      });
      continue;
    }
    if (counts.emptyArrows > frozen.emptyArrows || counts.casts > frozen.casts) {
      violations.push({
        file,
        detail:
          `${file}: ${counts.emptyArrows} empty-arrow / ${counts.casts} cast site(s) > frozen ` +
          `${frozen.emptyArrows} / ${frozen.casts}. An empty arrow body and an \`as any\` are the two shapes a ` +
          "FABRICATED DEPENDENCY takes when code moves into a package: cellix-m16 supplied " +
          "`shell as unknown as Group` and an emptied `forEach(() => {})` where ~150 lines of panel refresh had " +
          "been; cellix-m18 supplied `registerReactiveProp: (propId, group) => { /* no-op in main */ }` while the " +
          "real implementation stayed behind. Both trees were green. FIX: pass the real dependency. Counts only " +
          "shrink — do NOT raise this number.",
      });
    }
  }
  return violations;
}

/** Frozen entries that no longer hold as many sites as recorded — the ratchet must tighten. */
export function checkStandInFreezeIsHonest(
  freeze: Record<string, StandInCounts> = STAND_IN_FREEZE,
  measured: Record<string, StandInCounts> = measureStandInSites(),
): StandInViolation[] {
  const violations: StandInViolation[] = [];
  for (const [file, frozen] of Object.entries(freeze)) {
    const counts = measured[file] ?? { emptyArrows: 0, casts: 0 };
    if (counts.emptyArrows < frozen.emptyArrows || counts.casts < frozen.casts) {
      violations.push({
        file,
        detail:
          `${file}: frozen at ${frozen.emptyArrows} empty-arrow / ${frozen.casts} cast but now measures ` +
          `${counts.emptyArrows} / ${counts.casts}. Lower the freeze entry to the measurement (or delete it when ` +
          "both reach zero) so the ceiling keeps tracking the tree.",
      });
    }
  }
  return violations;
}
