/**
 * Public interface of @openclinxr/xr-runtime-wiring.
 *
 * Named lists, not `export *`. A star republishes a module wholesale, so a symbol added inside
 * becomes public with nobody deciding it should be. Generated by `pnpm arch:narrow-entrypoint`
 * from what the tree actually consumes, then proved by `pnpm packages:typecheck:agent`.
 */
export {
  booleanQueryParam,
  configuredExamRunId,
  configuredExamSequence,
  positiveIntegerQueryParam,
} from "./exam-run-params.js";
export type {
  ExamRunQueryDeps,
} from "./exam-run-params.js";
export {
  buildExamNavigationHref,
  buildExamRunStationOutcome,
  findFormStationOutcome,
  formElapsedSecondForCurrentStation,
  formatStationClock,
  mergeExamRunStationOutcome,
  nextExamScenarioId,
} from "./exam-run-sequence.js";
export type {
  ExamStationContext,
} from "./exam-run-sequence.js";
