/**
 * Public interface of @openclinxr/xr-asset-loading.
 *
 * Named lists, not `export *`. A star republishes a module wholesale, so a symbol added inside
 * becomes public with nobody deciding it should be. Generated by `pnpm arch:narrow-entrypoint`
 * from what the tree actually consumes, then proved by `pnpm packages:typecheck:agent`.
 */
export {
  clinicalTouchResponseClipNamesForActor,
  gazeProbeAnimationClipNamesFromGltf,
  hasAuthoredClinicalIdlePoseClip,
  roleAnimationClipNamesForActor,
} from "./clip-names.js";
export {
  addHumanoidSourceComparatorFaceReviewCues,
  comparatorCaptureSubjectActorId,
  frameComparatorCaptureOnNamedActor,
  loadGeneratedEnvironmentIntoSceneSlot,
  loadGeneratedEquipmentIntoSceneSlot,
  loadGeneratedHumanoidIntoActorSlot,
  selectedHumanoidSourceComparator,
} from "./generated-loaders.js";
export {
  registerGeneratedHumanoidAnimation,
} from "./humanoid-animation.js";
export {
  tintGeneratedSceneMaterials,
} from "./material-tint.js";
export {
  neutralizeGeneratedHumanoidMorphTargets,
  pedsAsthmaPatientBundleVisemeUtterance,
  suppressRuntimeDiagnosticOverlaysForSourceComparator,
} from "./morph-helpers.js";
export {
  addActorSpecificIdentityVariantCue,
  addReusableExteriorPreEncounterRoom,
  addRoleSpecificHumanoidVisuals,
  addScenarioSpecificClinicalSetDressing,
  addScenarioSpecificClinicalTeamCue,
  addScenarioSpecificFamilyCue,
  addScenarioSpecificPatientCue,
  configureSemanticRolePoseOverlay,
  shouldShowProceduralHumanoidDetailCues,
} from "./role-visuals.js";
export type {
  AssetLoadingScenarioTheme,
  HumanoidCueMode,
} from "./role-visuals.js";
export type {
  AssetLoadingContext,
  HumanoidSourceProvenance,
} from "./types.js";
export {
  runtimeHumanoidVariantAssetPath,
} from "./variant-paths.js";
