import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

type GeneratedFile = {
  filePath: string;
  content: string;
};

const args = new Set(process.argv.slice(2));
const checkOnly = args.has("--check");
const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const schemaPath = path.join(packageRoot, "src/schema.graphql");
const documentsDir = path.join(packageRoot, "src/documents");
const generatedDir = path.join(packageRoot, "src/generated");

const documentOrder = [
  "scenario-bank.graphql",
  "scenario-detail.graphql",
  "review-packet-replay.graphql",
  "exam-form-workbench.graphql",
  "assemble-exam-form.graphql",
  "create-station-run-queue-snapshot.graphql",
  "submit-scenario-review.graphql",
  "save-faculty-score-draft.graphql",
  "station-run-queue-snapshots.graphql",
] as const;

const routeIdsByFileName = new Map<string, string>([
  ["assemble-exam-form.graphql", "exam-form-assembly"],
  ["create-station-run-queue-snapshot.graphql", "station-run-queue-snapshot"],
  ["submit-scenario-review.graphql", "scenario-review-decision"],
  ["save-faculty-score-draft.graphql", "faculty-score-draft"],
  ["station-run-queue-snapshots.graphql", "station-run-queue-snapshots"],
]);

const files = await buildGeneratedFiles();

if (checkOnly) {
  const outOfDate = await findOutOfDateFiles(files);
  if (outOfDate.length > 0) {
    throw new Error(`Generated GraphQL artifacts are stale: ${outOfDate.map((file) => path.relative(packageRoot, file)).join(", ")}`);
  }
} else {
  await fs.mkdir(generatedDir, { recursive: true });
  await Promise.all(files.map((file) => fs.writeFile(file.filePath, file.content)));
}

async function buildGeneratedFiles(): Promise<GeneratedFile[]> {
  const schemaSdl = await fs.readFile(schemaPath, "utf8");
  const documents = await Promise.all(
    documentOrder.map(async (fileName) => {
      const filePath = path.join(documentsDir, fileName);
      const source = await fs.readFile(filePath, "utf8");
      return {
        fileName,
        routeId: routeIdsByFileName.get(fileName) ?? path.basename(fileName, ".graphql"),
        operationName: extractOperationName(source, fileName),
        source,
      };
    }),
  );

  return [
    {
      filePath: path.join(generatedDir, "schema.generated.ts"),
      content: [
        "// This file is auto-generated by packages/openclinxr/graphql/scripts/generate-static-artifacts.ts.",
        "// Do not edit directly.",
        "",
        `export const openClinXrAdminSchemaSdl = ${JSON.stringify(schemaSdl)};`,
        "",
      ].join("\n"),
    },
    {
      filePath: path.join(generatedDir, "documents.generated.ts"),
      content: [
        "// This file is auto-generated by packages/openclinxr/graphql/scripts/generate-static-artifacts.ts.",
        "// Do not edit directly.",
        "",
        "import type { AdminGraphqlDocument } from \"../documents.js\";",
        "",
        "export const adminGraphqlDocuments = [",
        ...documents.map(
          (document) =>
            `  ${JSON.stringify(
              {
                routeId: document.routeId,
                operationName: document.operationName,
                source: document.source,
              },
              null,
              2,
            ).replaceAll("\n", "\n  ")},`,
        ),
        "] satisfies AdminGraphqlDocument[];",
        "",
      ].join("\n"),
    },
  ];
}

async function findOutOfDateFiles(files: GeneratedFile[]): Promise<string[]> {
  const results: string[] = [];
  for (const file of files) {
    const current = await fs.readFile(file.filePath, "utf8").catch((error: unknown) => {
      if (isNodeErrnoException(error) && error.code === "ENOENT") {
        return undefined;
      }

      throw error;
    });

    if (current !== file.content) {
      results.push(file.filePath);
    }
  }

  return results;
}

function extractOperationName(source: string, fileName: string): string {
  const match = /\b(?:query|mutation|subscription)\s+([A-Za-z_][A-Za-z0-9_]*)/.exec(source);
  if (!match?.[1]) {
    throw new Error(`Unable to find named GraphQL operation in ${fileName}`);
  }

  return match[1];
}

function isNodeErrnoException(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && "code" in error;
}
