/**
 * Public interface of @openclinxr/xr-scene.
 *
 * Named lists, not `export *`. A star republishes a module wholesale, so a symbol added inside
 * becomes public with nobody deciding it should be. Generated by `pnpm arch:narrow-entrypoint`
 * from what the tree actually consumes, then proved by `pnpm packages:typecheck:agent`.
 */
export {
  computeMeshBounds,
  frameCamera,
} from "./camera-fit-to-bounds.js";

export {
  mountStationEnvironmentForRuntime,
  resolveCompiledRoomFromRuntimeEnvironment,
} from "./compiled-room-runtime-mount.js";
export type {
  EncounterActorFramingInput,
} from "./encounter-actor-framing.js";
export {
  addGeneratedHumanoidRoleContinuityWardrobeCue,
  applyCleanEncounterVisualReviewActorFraming,
} from "./encounter-actor-framing.js";
export type {
  HeadBoxGeometry,
  Vec3,
} from "./head-box-from-geometry.js";
export {
  deriveHeadBoxFromPoints,
  isFittedHairMeshName,
} from "./head-box-from-geometry.js";
export {
  assertHumanoidRootUpright,
} from "./humanoid-load-guard.js";
export {
  MPFB_GOWN_ADULT_PATIENT_RUNTIME_PATH,
  resolveHumanoidVariantOrCastPath,
  resolveLocalHumanoidRuntimeAssetFileName,
  resolveLocalHumanoidRuntimeAssetUrl,
  resolvePoolCastPathWithSiblings,
} from "./humanoid-runtime-asset-url.js";
export {
  assignMissingRoomPrimitiveMaterials,
  isGltfMissingAuthoredMaterial,
} from "./infinigen-room-primitive-materials.js";
export {
  collectActorWorldBoxes,
  deriveInteriorPreviewCamera,
  loadInfinigenEnvironmentIntoStation,
} from "./infinigen-station-environment.js";
export {
  bootIsolatedSubjectLab,
} from "./isolated-subject-lab.js";
export {
  applyExamFormBootPresentation,
  bootLearnerExamFormFromApi,
  createLearnerExamFormRunState,
  learnerExamResumeNextStation,
} from "./learner-exam-form-boot.js";
export {
  resolveLearnerExamScenarios,
  scenariosFromFixtureSequence,
} from "./learner-exam-scenario-source.js";
export type {
  LightingRig,
  LightingRigLight,
  RigLightType,
} from "./lighting-rig-contract.js";
export {
  LIGHTING_RIG_SCHEMA_VERSION,
} from "./lighting-rig-contract.js";
export {
  parseLightingRig,
} from "./lighting-rig-validation.js";
export {
  createPrimitiveActorMesh,
} from "./primitive-actor-mesh.js";
export {
  applyRealGarmentEvidenceSurfaces,
  sleeveDeformCueForAssetPath,
} from "./real-garment-evidence-surfaces.js";
export {
  createVirtualDeviceActorAffordance,
} from "./virtual-device-actor.js";
