/**
 * Public interface of @openclinxr/xr-capture-evidence.
 *
 * Named lists, not `export *`. A star republishes a module wholesale, so a symbol added inside
 * becomes public with nobody deciding it should be. Generated by `pnpm arch:narrow-entrypoint`
 * from what the tree actually consumes, then proved by `pnpm packages:typecheck:agent`.
 */
export {
  isActorCloseRealismCaptureMode,
  isActorPoseReviewCaptureMode,
  isGeneratedSceneOverviewCaptureMode,
  isHumanoidFaceDetailCaptureMode,
  isHumanoidMouthGazePoseReviewCaptureMode,
  isPhysicsClinicalTouchCapture,
  isSceneOnlyVisualReviewCaptureMode,
  selectedCaptureMode,
  shouldShowInSceneEvidencePanels,
  shouldShowInSceneIdentityLabels,
  shouldShowPrimitiveAssetFallbacks,
  shouldShowRuntimeAffordanceMarkers,
} from "./capture-mode.js";
export {
  shouldShowActorRealismRequirementPanel,
} from "./evidence-panels.js";
export {
  bundleUsesOnlyApprovedLocalFixtureAssets,
  publishRuntimeActorSlotAssignmentEvidence,
  recordLearnerRuntimeUseGateEvidence,
  resolveRuntimeSlotAssignment,
  runtimeBundleAssets,
  shouldUseLearnerRuntimeAssetBundle,
} from "./learner-runtime-evidence.js";
export {
  isRealGarmentSleeveDeformCapture,
} from "./real-garment-capture.js";
export {
  formatSceneAssetEvidenceStatus,
  formatUnknownError,
  recordSceneAssetStatus,
  recordXrEntryEvidence,
  refreshDeclaredEquipmentMountEvidenceFromScene,
  roundPerformanceNow,
  runtimeAssetAffordanceCueIds,
  sceneAssetSlotIsReady,
  clearSceneAssetStatusRecords,
} from "./scene-asset-evidence.js";
export type {
  DeclaredEquipmentMountEvidence,
  OpenClinXrXrEntryEvidence,
} from "./scene-asset-evidence.js";
export {
  buildCaseDefinedHumanoidPerformanceContractEvidence,
  buildRuntimeSceneManifestEvidence,
  formatCaseDefinedHumanoidPerformanceContractEvidence,
  isGeneratedPlaceholderSourceForDifferentScenario,
  shouldSuppressGeneratedEnvironmentShell,
  shouldSuppressGeneratedEquipmentModel,
} from "./scene-manifest-evidence.js";
export {
  shouldRenderRoomPropInVisualReview,
} from "./visual-review-filter.js";
export {
  isDeterministicCaptureClock,
  isEdBayVisibleCaptureMode,
} from "./capture-clock-validation.js";
