/**
 * Public interface of @openclinxr/xr-dialogue (root ".").
 *
 * Consumer-driven contracts: "." serves runtime-app consumers (apps/ui-xr).
 * Package, tools, and evidence consumers bind the class-pure subpaths
 * ./package-actor-turn, ./package-viseme, ./viseme-runtime, ./viseme-morph,
 * ./viseme-timeline, ./tooling-actor-audio, and ./evidence-viseme.
 *
 * Named lists, not `export *`. A star republishes a module wholesale, so a symbol added inside
 * becomes public with nobody deciding it should be. Generated by `pnpm arch:narrow-entrypoint`
 * from what the tree actually consumes, then proved by `pnpm packages:typecheck:agent`.
 */

export type { LiveActorTurnConsumption } from "./actor-turn-plan-consumption.js";
/** The emotion label the UI-XR expression weights derive from. */
export type { UiXrExpressionEmotion } from "./actor-turn-plan-consumption.js";
/** Per-emotion expression weights for the UI-XR face rig. */
export type { UiXrExpressionWeights } from "./actor-turn-plan-consumption.js";
export {
  consumeLiveActorTurn,
  emotionForDialogueText,
  expressionWeightsForEmotion,
  LIVE_ACTOR_TURN_CONSUMPTION_SEAM,
  liveActorTurnFromPayload,
  liveCaptionFromPlan,
  registerLiveActorTurn,
  resetLiveActorTurnRegistry,
  resolveLiveActorTurnForTrace,
} from "./actor-turn-plan-consumption.js";
export type {
  ActorTurnLiveSlot,
  ActorTurnPlayback,
  ActorTurnPlaybackAdapters,
  ActorTurnPlaybackStartContext,
} from "./actor-turn-playback.js";
export {
  ACTOR_TURN_PLAYBACK_SEAM,
  playFrozenActorTurn,
  playFrozenActorTurnOnSlot,
  resetActorTurnPlaybackStarts,
} from "./actor-turn-playback.js";
export type {
  ActorTurnExecutionArtifacts,
  ActorTurnPlayerAdapter,
  ActorTurnPlayerAdapterContext,
  ActorTurnPlayerAdapters,
  IdentityBoundRef,
} from "./actor-turn-player.js";
export {
  ACTOR_TURN_PLAYER_SEAM,
  digestActorTurnPlan,
  playIdentityBoundActorTurn,
} from "./actor-turn-player.js";
export { isPedsAsthmaScenario } from "./peds-scenario-validation.js";
export {
  initSpeakFixtureBridge,
} from "./speak-fixture-bridge.js";
export {
  formatActiveActorRealismRequirementLines,
  formatHumanoidSpeechAffectEvidence,
} from "./speech-hud-formatting.js";
export {
  attachBakedCuesToSpeech,
  loadBakedMouthCuesForUtterance,
  mouthCuesToPhonemeCues,
} from "./viseme-baked-cues.js";
export { applyNamedSpeechVisemes, applyGeneratedScalarVisemeToRoot } from "./viseme-runtime-wire.js";
/** The minimal speech-slot surface the viseme wire drives. */
export type { SpeechSlotLike } from "./viseme-runtime-wire.js";
/** A phoneme with its timing cue for the viseme timeline drive. */
export type { PhonemeCue } from "./viseme-timeline-drive.js";
export { MOUTH_OPEN_CAP, collectResolvedMorphTargets, resolveMorphIndex } from "./viseme-morph-apply.js";
export { applyBlinkClosureToRoot } from "./blink-runtime-wire.js";
export { applyGazeToHumanoid } from "./gaze-drives-eyes.js";
export { initialDialogueTextForScenario } from "./initial-dialogue-text.js";
export { phonemesForText, visemesForText } from "./dialogue-visemes.js";
