/**
 * Public interface of @openclinxr/domain.
 *
 * Named lists, not `export *`. A star republishes a module wholesale, so a symbol added inside
 * becomes public with nobody deciding it should be. Generated by `pnpm arch:narrow-entrypoint`
 * from what the tree actually consumes, then proved by `pnpm packages:typecheck:agent`.
 */
export {
  buildScenarioGovernanceCopy,
  findUnsafeClaimLanguage,
  safeUserFacingClaimLanguage,
  scoreUseCopy,
  validationStageCopy,
} from "./claim-language.js";
export {
  createStationRun,
  evaluateRequiredTraceTags,
  transitionStation,
} from "./station-state.js";
export type {
  StationPhase,
  StationRun,
} from "./station-state.js";
export {
  AUTHORED_CONTENT_IDENTITY_EVIDENCE_PREFIX,
  AUTHORED_CONTENT_IDENTITY_OMITTED_NESTED_KEYS,
  AUTHORED_CONTENT_IDENTITY_OMITTED_ROOT_KEYS,
  authoredContentIdentity,
  authoredContentIdentityEvidenceRef,
  authoredContentIdentityFromEvidenceRefs,
  canonicalizeAuthoredValue,
} from "./authored-content-identity.js";
export {
  SCENARIO_BANK_AUTONOMOUS_APPROVAL_ERROR,
  SCENARIO_BANK_PARTIAL_APPROVAL_ERROR,
  SCENARIO_BANK_STALE_APPROVAL_ERROR,
  approveScenarioBankVersion,
  assemblyVisibleRevisions,
  createScenarioBankDraft,
  forkDraftFromImmutableVersion,
  markScenarioBankReviewReady,
  updateScenarioBankDraft,
} from "./scenario-bank-lifecycle.js";
export type {
  CompletedHumanReview,
  ScenarioBankRevision,
} from "./scenario-bank-lifecycle.js";
