/**
 * Public interface of @openclinxr/domain.
 *
 * Named lists, not `export *`. A star republishes a module wholesale, so a symbol added inside
 * becomes public with nobody deciding it should be. Generated by `pnpm arch:narrow-entrypoint`
 * from what the tree actually consumes, then proved by `pnpm packages:typecheck:agent`.
 */

export {
  authoredContentIdentity,
  authoredContentIdentityEvidenceRef,
  authoredContentIdentityFromEvidenceRefs,
} from "./authored-content-identity.js";
export {
  findUnsafeClaimLanguage,
} from "./claim-language.js";
export type {
  CompletedHumanReview,
  ScenarioBankRevision,
} from "./scenario-bank-lifecycle.js";
export {
  approveScenarioBankVersion,
  assemblyVisibleRevisions,
  createScenarioBankDraft,
  forkDraftFromImmutableVersion,
  markScenarioBankReviewReady,
  SCENARIO_BANK_AUTONOMOUS_APPROVAL_ERROR,
  SCENARIO_BANK_PARTIAL_APPROVAL_ERROR,
  SCENARIO_BANK_STALE_APPROVAL_ERROR,
  updateScenarioBankDraft,
} from "./scenario-bank-lifecycle.js";
export type {
  ScheduledEvent,
  StationRun,
} from "./station-state.js";
export {
  createStationRun,
  evaluateRequiredTraceTags,
  getScheduledEventsDue,
  transitionStation,
} from "./station-state.js";
