/**
 * Public interface of @openclinxr/voice-gateway.
 *
 * Named lists, not `export *`. A star republishes a module wholesale, so a symbol added inside
 * becomes public with nobody deciding it should be. Generated by `pnpm arch:narrow-entrypoint`
 * from what the tree actually consumes, then proved by `pnpm packages:typecheck:agent`.
 */

export {
  collectVoiceStream,
  LocalVoiceProviderAdapter,
  MockVoiceProviderAdapter,
} from "./adapters.js";
export {
  createDefaultVoiceGateway,
  createRealtimeVoiceGatewayPosture,
  selectRealtimeVoiceProtocol,
  VoiceGateway,
} from "./gateway.js";
export type {
  AudioEvent,
  RealtimeVoiceGatewayPosture,
  RealtimeVoiceGatewayPostureInput,
  RealtimeVoiceProtocolLaneId,
  VoiceProviderAdapter,
  VoiceRequestPolicy,
} from "./types.js";
export {
  realtimeVoiceProtocol,
  supportedRealtimeVoiceControlTypes,
} from "./types.js";
