import {expect,it} from "vitest";
import {readFileSync} from "node:fs";
import {measureSurface} from "../../../../packages/openclinxr-verification/architecture-rules/src/checks/public-surface/resolve.js";
import {measureExportSurface,checkExportSurface} from "../../../../packages/openclinxr-verification/architecture-rules/src/checks/export-surface-budgets.js";
const root=new URL("../../../../",import.meta.url);
const original={"name": "@openclinxr/xr-dialogue", "version": "0.1.0", "private": true, "type": "module", "exports": {".": {"types": "./dist/index.d.ts", "default": "./dist/index.js"}}, "scripts": {"lint": "biome lint --no-errors-on-unmatched .", "typecheck": "tsgo --noEmit -p tsconfig.vitest.json", "test": "vitest run --root .", "build": "tsgo --build", "clean": "rm -rf dist *.tsbuildinfo"}, "dependencies": {"@openclinxr/asset-registry": "workspace:*", "@openclinxr/scenario-fixtures": "workspace:*", "@openclinxr/shared-schemas": "workspace:*", "@openclinxr/xr-pose": "workspace:*", "three": "catalog:"}, "devDependencies": {"@types/three": "catalog:", "typescript": "catalog:", "vitest": "catalog:", "@cellix/config-vitest": "workspace:*", "@cellix/config-typescript": "workspace:*"}, "files": ["dist"]};
const descriptor={types:"./dist/actor-audio-runtime.d.ts",default:"./dist/actor-audio-runtime.js"};
function assertManifest(actual:unknown){expect(actual).toEqual({...original,exports:{...original.exports,"./actor-audio-runtime":descriptor}});}
it("RED explicit single factory subpath preserves every existing package manifest property",()=>assertManifest(JSON.parse(readFileSync(new URL("packages/openclinxr/xr-dialogue/package.json",root),"utf8"))));
it("positive exact subpath descriptor passes identical manifest oracle",()=>assertManifest({...original,exports:{...original.exports,"./actor-audio-runtime":descriptor}}));
it("negative dependency addition and extra unchecked subpath fail identical oracle",()=>{expect(()=>assertManifest({...original,dependencies:{...original.dependencies,unsafe:"1"},exports:{...original.exports,"./actor-audio-runtime":descriptor}})).toThrow();expect(()=>assertManifest({...original,exports:{...original.exports,"./actor-audio-runtime":descriptor,"./unsafe":descriptor}})).toThrow();});
it("RED actual compiler supported entrypoint exposes only the consumed factory",()=>{const report=measureSurface(new URL(".",root).pathname);const pkg=report.packages.find(p=>p.packageDir==="packages/openclinxr/xr-dialogue")!;const entry=pkg.entrypoints.find(e=>e.specifier==="./actor-audio-runtime");expect(entry).toBeDefined();expect(entry?.symbols.map(s=>s.name)).toEqual(["createActorAudioRuntime"]);});
it("original root export ceiling stays47 and actual export checker refuses growth",()=>{const m=measureExportSurface().find(p=>p.pkg==="xr-dialogue")!;expect(m.exports).toBe(47);expect(checkExportSurface([m])).toEqual([]);expect(checkExportSurface([{...m,exports:48}])).toEqual([expect.objectContaining({pkg:"xr-dialogue",detail:expect.stringContaining("ceiling 47")})]);});
