/**
 * Public interface of @openclinxr/scenario-runtime.
 *
 * Named lists, not `export *`. A star republishes a module wholesale, so a symbol added inside
 * becomes public with nobody deciding it should be. Generated by `pnpm arch:narrow-entrypoint`
 * from what the tree actually consumes, then proved by `pnpm packages:typecheck:agent`.
 */


export type {
  PublicationTargetUse,
  ReviewerEvidence,
} from "@openclinxr/review-workflow";
export type {
  AssembledExamAdmittedPhaseEvent,
  AssembledExamLedgerResumeProjection,
  AssembledExamResumeDecision,
} from "./assembled-exam-orchestrator.js";
export {
  assembledExamOrchestratorClaimBoundary,
  resumeAssembledExam,
} from "./assembled-exam-orchestrator.js";
export {
  createDefaultScenarioRuntime,
  createScenarioRuntimeWithPersistenceHooks,
} from "./default-runtime-factory.js";
export {
  buildInitialSceneSpec,
  initialSceneSpecPermitsPromotion,
  REQUIRED_STATE_OUTCOMES,
  requiredStateOutcomePromotes,
} from "./initial-scene-spec.js";
export {
  createDurableStoreFromPersistenceHooks,
} from "./provider-support.js";
export type {
  AssembledStationContext,
  DurableStorePersistenceHooks,
  ProviderHealthSnapshot,
  RouteRuntimeActorInteractionInput,
  ScenarioRuntimeActorTurn,
  ScenarioRuntimeDurableStore,
} from "./runtime-types.js";
export type {
  ScenarioCatalogPort,
} from "./scenario-catalog.js";
export {
  resolveScenarioById,
} from "./scenario-catalog.js";
export {
  ScenarioRuntime,
} from "./scenario-runtime.js";
