import { existsSync, readdirSync, statSync } from "node:fs";
import { dirname, join, resolve as pathResolve } from "node:path";
import { fileURLToPath } from "node:url";
import { NodeIO } from "@gltf-transform/core";
import { describe, expect, it } from "vitest";

/**
 * The factory cannot reproduce its own shipped output. Both garments on the library bodies exist ONLY
 * as baked triangles in a tracked GLB — their source assets are on no disk in this repo — so every
 * re-bake silently degrades the figure.
 *
 * MEASURED 2026-08-11, and this was found by a REVERT, not by a gate. #307 swapped the library bodies
 * onto MPFB's mixamo_unity rig, all three of its contracts passed, and the landed figure had **no
 * trousers**. Measured against the branch's true merge-base (`40a065c2`):
 *
 *   body-param-adult_lean_female-library.glb   | before                        | after #307
 *   -------------------------------------------|-------------------------------|------------
 *   openclinxr_footwear_casual_shoe_L/R_mesh    | 162 t each                    | 162 t each
 *   hm08_basemesh_adult_lean_female             | 26,756 t                      | 26,756 t
 *   makeclothes_library_cargo_pants_…_mesh      | **2,530 t**                   | **GONE**
 *   makeclothes_library_civilian_shirt_…        | 11,524 t                      | 11,524 t
 *
 * CAUSE, located: `body-param-cli.ts:514-545`. The "#220 find-or-stop" calls
 * `examineLowerGarmentCandidates`, writes the candidate list, then does
 * `const acceptedLower = lowerExamined.find((c) => c.accepted) ?? null; if (acceptedLower) { … }`.
 * The `throw` inside that block fires only when an ACCEPTED candidate has missing files. **The
 * none-accepted branch falls through silently** — a find-or-stop that finds nothing and does not stop.
 *
 * AND THERE IS NOTHING LEFT TO FIND. Searched the whole tree and the Blender install:
 *
 *   Scrub_Shirt.mhclo          0 found
 *   cortu_cargo_pants.mhclo    0 found
 *   .openclinxr/evidence/issue-151/staging/   EMPTY on main (and gitignored)
 *   .openclinxr-local/provider-cache/garments/sources/makehuman-shirts01/
 *       namuhekam_male_polo_shirt · toigo_basic_tucked_t-shirt · elvs_crude_t-shirt_male
 *       — three UPPER garments. **No lower-body garment source exists anywhere.**
 *
 * So the 2,530 triangles of cargo pants in the tracked GLB came from a bake whose input is gone. #307
 * did not break the trousers; it REVEALED that they cannot be rebuilt. That is the D9 dark-factory
 * defect in its purest form: the pipeline's output is not a function of its inputs, because the inputs
 * are missing and the pipeline does not say so.
 *
 * WHY (2) IS THE COUNTERWEIGHT. The cheapest way to make "every garment is reproducible" true is to
 * stop shipping the garment nobody can rebuild — which is precisely the regression #307 landed and I
 * reverted. (2) refuses that: each library body must still ship at least one upper AND one lower
 * garment mesh. A fix must ACQUIRE a source, not delete the evidence.
 *
 * THE CHEAP FIXES THIS REFUSES, probed 2026-08-11 before planting:
 *
 *   treatment                                   | (1) reproducible | (2) still dressed | result
 *   --------------------------------------------|------------------|-------------------|--------
 *   a) today                                    |       FAIL       |        pass       | REFUSED
 *   b) drop the unreproducible garment (= #307) |    pass (vacuous)|      **FAIL**     | REFUSED
 *   c) point at a source path that does not exist|      **FAIL**   |        pass       | REFUSED
 *   d) acquire CC0/CC-BY sources and record them|       pass       |        pass       | ALL PASS
 *
 * (b) is not hypothetical — it is the state I reverted an hour ago, and it passed three other contracts.
 *
 * WHICH ARE REDS AND WHICH ARE NETS (#227): (1) is a RED and fails today on both library bodies.
 * (2) and (3) PASS today and are the known-good columns — (3) in particular shows the bar is
 * achievable, because the footwear meshes ARE reproducible: they are generated by a script in this
 * repo and need no third-party source at all.
 *
 * NOT TESTED: nothing is baked, rendered, or graded here. This asserts that a source EXISTS, never that
 * re-running the bake reproduces the same triangles — that is a stronger claim needing a real bake and
 * a mesh comparison. Nothing here says the shipped garments are correct, well-fitted, or licence-clean;
 * #295 owns fit quality and the licence ledger owns provenance. Nothing here covers the Anny rail's
 * garments or `mpfb-ob-patient-aisha`, which carries no garment mesh at all.
 */

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = pathResolve(HERE, "../../..");

const LIBRARY_BODIES = [
  "apps/ui-xr/public/xr-assets/humanoids/candidates/body-param-adult_lean_female-library.glb",
  "apps/ui-xr/public/xr-assets/humanoids/candidates/body-param-adult_heavy_male-library.glb",
] as const;

/** Where third-party garment sources are cached. */
const GARMENT_CACHE = join(REPO_ROOT, ".openclinxr-local/provider-cache/garments");

/** Meshes generated by a script in this repo — reproducible without any third-party source. */
const PROCEDURAL_GENERATORS: ReadonlyArray<{ meshPrefix: string; generator: string }> = [
  {
    meshPrefix: "openclinxr_footwear_",
    generator: "tools/openclinxr/asset-pipeline/makeclothes/embed_library_footwear.py",
  },
];

/** Fitted third-party garments carry this prefix and must resolve to a cached `.mhclo`. */
const LIBRARY_GARMENT_PREFIX = "makeclothes_library_";

const io = new NodeIO();

function everyMhcloStem(): Set<string> {
  const stems = new Set<string>();
  const walk = (dir: string): void => {
    if (!existsSync(dir)) return;
    for (const entry of readdirSync(dir)) {
      const full = join(dir, entry);
      if (statSync(full).isDirectory()) walk(full);
      else if (entry.toLowerCase().endsWith(".mhclo")) {
        stems.add(entry.slice(0, -".mhclo".length).toLowerCase().replaceAll("-", "_"));
      }
    }
  };
  walk(GARMENT_CACHE);
  return stems;
}

type GarmentMesh = { body: string; mesh: string; triangles: number; kind: "library" | "procedural" | "other" };

async function garmentMeshes(rel: string): Promise<GarmentMesh[]> {
  const doc = await io.read(join(REPO_ROOT, rel));
  const out: GarmentMesh[] = [];
  for (const mesh of doc.getRoot().listMeshes()) {
    const name = mesh.getName();
    if (name.startsWith("hm08_basemesh")) continue;
    let triangles = 0;
    for (const prim of mesh.listPrimitives()) triangles += (prim.getIndices()?.getCount() ?? 0) / 3;
    const kind = name.startsWith(LIBRARY_GARMENT_PREFIX)
      ? "library"
      : PROCEDURAL_GENERATORS.some((g) => name.startsWith(g.meshPrefix))
        ? "procedural"
        : "other";
    out.push({ body: rel.split("/").pop()!, mesh: name, triangles: Math.round(triangles), kind });
  }
  return out;
}

/** A library garment resolves when some cached `.mhclo` stem appears in its mesh name. */
function resolvesToCachedSource(meshName: string, stems: ReadonlySet<string>): boolean {
  const normalised = meshName.toLowerCase().replaceAll("-", "_");
  for (const stem of stems) {
    if (stem.length >= 4 && normalised.includes(stem)) return true;
  }
  return false;
}

const measured = (await Promise.all(LIBRARY_BODIES.map(garmentMeshes))).flat();
const cachedStems = everyMhcloStem();

describe("every garment a library body ships can be rebuilt from a source in this repo", () => {
  it.fails(
    "(1) RED: each fitted library garment resolves to a cached .mhclo source — today both came from bakes whose inputs are gone",
    () => {
      const unreproducible = measured
        .filter((m) => m.kind === "library" && !resolvesToCachedSource(m.mesh, cachedStems))
        .map((m) => `${m.body}: ${m.mesh} (${m.triangles}t) has no source in provider-cache/garments`);
      expect(unreproducible, "shipped garments with no rebuildable source").toEqual([]);
    },
  );

  it("(2) NET COUNTERWEIGHT: each library body still ships an upper AND a lower garment — deleting the unreproducible one is refused", () => {
    for (const rel of LIBRARY_BODIES) {
      const body = rel.split("/").pop()!;
      const mine = measured.filter((m) => m.body === body && m.kind === "library");
      const upper = mine.filter((m) => /shirt|top|gown|scrub|cardigan/i.test(m.mesh));
      const lower = mine.filter((m) => /pants|trouser|skirt|short/i.test(m.mesh));
      expect(upper.length, `${body}: upper garment meshes (${mine.map((m) => m.mesh).join(", ")})`)
        .toBeGreaterThanOrEqual(1);
      expect(lower.length, `${body}: lower garment meshes (${mine.map((m) => m.mesh).join(", ")})`)
        .toBeGreaterThanOrEqual(1);
    }
  });

  it("(3) NET known-good: the footwear meshes ARE reproducible — generated by a script in this repo, no third-party source needed", () => {
    for (const g of PROCEDURAL_GENERATORS) {
      expect(existsSync(join(REPO_ROOT, g.generator)), `${g.generator} exists`).toBe(true);
    }
    const procedural = measured.filter((m) => m.kind === "procedural");
    expect(procedural.length, "procedural garment meshes found").toBeGreaterThanOrEqual(2);
    for (const m of procedural) {
      expect(m.triangles, `${m.body}: ${m.mesh} has geometry`).toBeGreaterThan(0);
    }
  });
});
