import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

import { measure, measureDeciles, REPO, SKIRT_DECILES_DEFAULT } from "./garment-decile-sharpness.js";
import type { DecileRow } from "./garment-decile-sharpness.js";

/**
 * OBSERVABLE: the hospital gown's shell is sharp everywhere, including the skirt, where the fold wave
 * never runs. This is the floor that made #747's fold sweep saturate.
 *
 * MEASURED by the orchestrator on 2026-08-28 at main `6ffa5977`. Share of interior edges folding past
 * 60 degrees, geometric normals, welded by position at 5dp, in deciles of each garment's own y range.
 * IMMUTABLE — flip the assertions and append a `## FIXED (#750)` block below; do not rewrite these.
 *
 *   decile        gown    scrub top   cardigan
 *   d0 hem       13.0%      11.7%      10.2%     <- ambient rim creasing on ALL THREE, not a defect
 *   d1           10.4%       1.7%       4.4%
 *   d2           11.1%       1.2%       3.8%
 *   d3            9.8%       0.0%       7.4%
 *   d4           15.0%       0.0%       2.0%
 *   d5           29.6%       0.0%       0.0%
 *   d6           22.5%       0.0%       0.0%
 *   d7           20.8%       1.5%       4.4%
 *   d8           19.5%       0.0%       0.0%
 *   d9 collar    11.4%       0.0%       0.0%
 *
 * The fold wave runs in d4-d8. The gown's SKIRT, d1-d3, reads 9.8-11.1% against 0.0-7.4% for two
 * clean garments in the same bands, in geometry the fold never touches.
 *
 * ## WHY CLAUSE (1) LIVES HERE AND NOT IN #747
 *
 * Clause (1) is #747's, relocated VERBATIM — same relative ceiling, same message, same zero-tolerance
 * against the non-gown population. #747 swept the fold wave count 16 -> 4 and the whole-garment sharp
 * fraction moved 20.80% -> 15.46% and saturated, with gather depth unchanged at 0.4575 in every cell.
 * No fold parameter reaches the remaining floor, so a clause demanding the WHOLE garment reach ambient
 * could never be satisfied inside #747's scope. It is the target both cards serve and it belongs with
 * the larger blocker. #747 keeps an inverted guard that fails if this file stops asserting it.
 *
 * ## CAUSE NOT DETERMINED
 *
 * Three readings, unranked, possibly all wrong: the gown's shell is generated by a different code path
 * from the garments that render clean; the `closed_gown_drape` topology class creases where the open
 * classes do not; or a modifier in the gown's bake produces it. Two constraints measured on the way
 * here: the gown shares `torso_rows, torso_cols = 11, 16` with the open cardigan, so the parametric
 * grid is not the difference, and the exported bodice carries ~300 azimuth columns per ring, so
 * whatever subdivides the shell is a candidate.
 *
 * ## THE CHEAP GREENS, AND WHY EACH IS REFUSED
 *
 * Counterweight (3) pins the comparators: both clause (1) and clause (2) are RELATIVE, so degrading a
 * clean garment raises the ceiling until the gown fits under it.
 *
 * Counterweight (4) pins the population and the hem exclusion: d0 is ambient on all three garments and
 * is excluded on purpose, but excluding more bands than d0 would drop the very skirt this card is
 * about.
 *
 * Counterweight (5) keeps #747's inverted guard in place, so the relocation cannot become a deletion.
 */

const ORIGIN = join(REPO, "tools/openclinxr/evidence/the-hospital-gown-surface-is-as-smooth-as-a-garment-that-renders.test.ts");
const SKIRT_DECILES = SKIRT_DECILES_DEFAULT;
const COMPARATOR_SKIRT_CEILING = 0.111;
const rowsPromise = measure();
const decilesPromise = measureDeciles();

const pct = (f: number) => `${(f * 100).toFixed(2)}%`;

describe("the gown shell is not sharp where no fold runs (#750)", () => {
  it.fails("(1) no gown is rougher than the roughest garment that renders acceptably", async () => {
    const rows = await rowsPromise;
    const clean = rows.filter((r) => !r.gown);
    const gowns = rows.filter((r) => r.gown);
    expect(clean.length, "the comparator population must be measured").toBeGreaterThan(0);
    expect(gowns.length, "both hospital-gown primitives must be measured").toBe(2);
    const ceiling = Math.max(...clean.map((r) => r.sharpFraction));
    const worstGown = gowns.reduce((a, b) => (a.sharpFraction >= b.sharpFraction ? a : b));
    expect(
      worstGown.sharpFraction,
      `${worstGown.label} has ${pct(worstGown.sharpFraction)} of its interior edges folding past `
        + `${SHARP_DEGREES} degrees, against a ceiling of ${pct(ceiling)} set by the roughest garment `
        + `on this tree that renders acceptably. The ceiling is measured here, not chosen, so it `
        + `tracks the fleet. Rows: ${rows.map((r) => `${r.label} ${pct(r.sharpFraction)}`).join("; ")}`,
    ).toBeLessThanOrEqual(ceiling);
  });


  it.fails("(2) the gown's skirt is no sharper than a clean garment's, where no fold runs", async () => {
    const rows = await decilesPromise;
    const gowns = rows.filter((r) => r.gown);
    const clean = rows.filter((r) => !r.gown);
    expect(gowns.length, "both hospital-gown primitives must be measured").toBe(2);
    expect(clean.length, "the comparator population must be measured").toBeGreaterThan(0);
    const skirtOf = (r: DecileRow) => Math.max(...SKIRT_DECILES.map((d) => r.deciles[d] ?? 0));
    const ceiling = Math.max(...clean.map(skirtOf));
    const worst = gowns.reduce((a, b) => (skirtOf(a) >= skirtOf(b) ? a : b));
    expect(
      skirtOf(worst),
      `${worst.label}'s skirt (deciles ${SKIRT_DECILES.join(", ")}) peaks at ${pct(skirtOf(worst))} `
        + `against ${pct(ceiling)} for the roughest clean garment in the same bands. The fold wave runs `
        + `in d4-d8, so this is geometry no fold parameter reaches — #747 swept the wave count 16 to 4 `
        + `and this floor did not move. d0 is excluded because rim creasing is 10-13% on all three `
        + `garments and is ambient. Rows: ${rows.map((r) => `${r.label} `
        + `[${SKIRT_DECILES.map((d) => pct(r.deciles[d] ?? 0)).join("/")}]`).join("; ")}`,
    ).toBeLessThanOrEqual(ceiling);
  });

  it("(3) COUNTERWEIGHT: the comparators are not degraded to raise either ceiling", async () => {
    const rows = await decilesPromise;
    const skirtOf = (r: DecileRow) => Math.max(...SKIRT_DECILES.map((d) => r.deciles[d] ?? 0));
    for (const row of rows.filter((r) => !r.gown)) {
      expect(
        skirtOf(row),
        `${row.label}'s skirt peaks at ${pct(skirtOf(row))}. Clauses (1) and (2) are both RELATIVE, so `
          + `a degraded comparator raises the ceiling until the gown fits under it. The bound is `
          + `${pct(COMPARATOR_SKIRT_CEILING)} — the open cardigan's measured 7.4% with 1.5x headroom `
          + `for rebake variation. A comparator above it is a regression in that garment, not a licence `
          + `to relax this file.`,
      ).toBeLessThanOrEqual(COMPARATOR_SKIRT_CEILING);
    }
  });

  it("(4) COUNTERWEIGHT: only the ambient hem band is excluded", () => {
    expect(
      SKIRT_DECILES,
      "d0 is excluded because rim creasing measures 10-13% on the gown, the scrub top and the "
        + "cardigan alike. Excluding any band above d0 would drop the skirt this card is about. "
        + "Restore [1, 2, 3].",
    ).toEqual([1, 2, 3]);
  });

  it("(5) COUNTERWEIGHT: #747 still guards the clause this file inherited", () => {
    const src = readFileSync(ORIGIN, "utf8");
    expect(
      /SUPERSEDED by #750/u.test(src),
      `${ORIGIN} must keep the inverted guard naming this file. A relocation with no marker at the `
        + "origin is indistinguishable from a deleted clause.",
    ).toBe(true);
  });
});
