export type TeamId =
  | "coordinator"
  | "core"
  | "physicians"
  | "adversarial"
  | "leadership"
  | "legal";

export type AgentDefinition = {
  id: string;
  name: string;
  team: TeamId;
  mission: string;
  owns: string[];
  outputs: string[];
  escalationTriggers: string[];
  memoryTopics: string[];
  toolPermissions: string[];
  rubricDimensions: string[];
};

const commonOutputs = [
  "Iteration notes",
  "Memory updates",
  "Rubric-linked findings",
  "Open risks and decisions",
];

const commonToolPermissions = [
  "read-local-artifacts",
  "write-agent-memory",
  "cite-source-records",
];

export const agentRoster: AgentDefinition[] = [
  {
    id: "chief-coordinator",
    name: "Chief Coordinator",
    team: "coordinator",
    mission: "Coordinate the full Core, Adversarial, and Senior Leadership loop without letting the planning process drift.",
    owns: ["Iteration agenda", "Team sequencing", "Escalation decisions", "Final synthesis"],
    outputs: ["Iteration brief", "Team work orders", "Synthesis memo", "Final plan candidate"],
    escalationTriggers: ["Critical risk persists", "Score plateau detected", "Leadership blocker appears"],
    memoryTopics: ["loop-performance", "unresolved-decisions", "coordination-patterns"],
    toolPermissions: [...commonToolPermissions, "run-agent-cli-tools"],
    rubricDimensions: ["implementation_readiness", "adversarial_robustness"],
  },
  {
    id: "memory-archivist",
    name: "Memory Archivist",
    team: "coordinator",
    mission: "Keep agent memory searchable, current, and free of stale claims that would mislead future iterations.",
    owns: ["Memory hygiene", "Index updates", "Superseded claims", "Cross-agent links"],
    outputs: ["Memory index updates", "Claim maps", "Stale-memory reports"],
    escalationTriggers: ["Contradictory memory found", "Unindexed critical decision found"],
    memoryTopics: ["memory-quality", "superseded-claims", "cross-agent-links"],
    toolPermissions: [...commonToolPermissions, "build-memory-index"],
    rubricDimensions: ["evidence_discipline", "implementation_readiness"],
  },
  {
    id: "rubric-steward",
    name: "Rubric Steward",
    team: "coordinator",
    mission: "Score outputs consistently and identify whether the agent factory is improving across iterations.",
    owns: ["Rubric consistency", "Score history", "Plateau detection", "Weight-change proposals"],
    outputs: ["Scorecards", "Delta analysis", "Rubric change recommendations"],
    escalationTriggers: ["Score regression", "Repeated unscored claims", "Rubric weight dispute"],
    memoryTopics: ["score-history", "rubric-weights", "plateau-patterns"],
    toolPermissions: [...commonToolPermissions, "run-score-tools"],
    rubricDimensions: ["adversarial_robustness", "implementation_readiness"],
  },
  {
    id: "source-librarian",
    name: "Source Librarian",
    team: "coordinator",
    mission: "Maintain source discipline and prevent unsupported claims from entering leadership packets.",
    owns: ["Source ledger", "Source quality classification", "Evidence debt", "Claim-to-source matrix"],
    outputs: ["Source records", "Evidence debt report", "Claim support matrix"],
    escalationTriggers: ["Current claim lacks verification", "Vendor source used as validation evidence"],
    memoryTopics: ["source-ledger", "evidence-debt", "claim-classes"],
    toolPermissions: [...commonToolPermissions, "internet-research-when-approved"],
    rubricDimensions: ["evidence_discipline", "market_gtm_strength"],
  },
  {
    id: "solution-architect",
    name: "Solution Architect",
    team: "core",
    mission: "Turn the OpenClinXR concept into a coherent technical and product system plan.",
    owns: ["System boundaries", "Component responsibilities", "Integration strategy", "Implementation readiness"],
    outputs: commonOutputs,
    escalationTriggers: ["Architecture boundary conflict", "Unowned subsystem", "Implementation sequence unclear"],
    memoryTopics: ["architecture-decisions", "component-boundaries", "dependency-map"],
    toolPermissions: commonToolPermissions,
    rubricDimensions: ["technical_feasibility", "architecture_coherence", "implementation_readiness"],
  },
  {
    id: "xr-systems-architect",
    name: "XR Systems Architect",
    team: "core",
    mission: "Protect the plan from unrealistic headset, WebXR, rendering, asset, and interaction assumptions.",
    owns: ["Quest-class constraints", "WebXR/OpenXR strategy", "3D rendering", "Interaction model", "Asset pipeline"],
    outputs: commonOutputs,
    escalationTriggers: ["Frame-rate risk", "Latency risk", "Unsupported device assumption"],
    memoryTopics: ["webxr", "quest-performance", "asset-pipeline", "interaction-model"],
    toolPermissions: commonToolPermissions,
    rubricDimensions: ["technical_feasibility", "cost_performance_efficiency", "architecture_coherence"],
  },
  {
    id: "clinical-simulation-lead",
    name: "Clinical Simulation Lead",
    team: "core",
    mission: "Ensure scenarios, faculty workflows, and debriefs reflect real clinical simulation practice.",
    owns: ["Scenario realism", "Faculty workflow", "Learner progression", "Debriefing model"],
    outputs: commonOutputs,
    escalationTriggers: ["Unsafe simulation claim", "Faculty burden too high", "Scenario realism gap"],
    memoryTopics: ["simulation-workflows", "faculty-review", "debriefing", "learner-progression"],
    toolPermissions: commonToolPermissions,
    rubricDimensions: ["clinical_validity", "ux_workflow_fit", "specialty_clinical_generalizability"],
  },
  {
    id: "psychometrics-lead",
    name: "Psychometrics Lead",
    team: "core",
    mission: "Keep validity, reliability, fairness, score use, and consequence claims defensible.",
    owns: ["Kane argument", "G-theory", "Reliability", "Fairness", "Rater calibration", "Summative gates"],
    outputs: commonOutputs,
    escalationTriggers: ["Summative claim appears", "Reliability evidence missing", "Fairness review missing"],
    memoryTopics: ["validity", "g-theory", "fairness", "rater-calibration", "consequence-validity"],
    toolPermissions: commonToolPermissions,
    rubricDimensions: ["psychometric_defensibility", "evidence_discipline", "clinical_validity"],
  },
  {
    id: "data-trace-architect",
    name: "Data And Trace Architect",
    team: "core",
    mission: "Design trace, replay, audit, and analytics structures that support defensible review.",
    owns: ["Trace schema", "Event taxonomy", "Replay model", "Audit export", "Data lineage"],
    outputs: commonOutputs,
    escalationTriggers: ["Trace field lacks owner", "Replay requirement unsupported", "Audit export gap"],
    memoryTopics: ["trace-schema", "event-taxonomy", "replay", "audit-export"],
    toolPermissions: commonToolPermissions,
    rubricDimensions: ["architecture_coherence", "psychometric_defensibility", "security_privacy"],
  },
  {
    id: "security-privacy-lead",
    name: "Security And Privacy Lead",
    team: "core",
    mission: "Design zero-trust, consent, privacy, tenant isolation, audit, and incident-response safeguards.",
    owns: ["Access control", "Tenant isolation", "Consent", "Retention", "Encryption", "Incident response"],
    outputs: commonOutputs,
    escalationTriggers: ["Cross-tenant risk", "Consent ambiguity", "Third-party data flow unresolved"],
    memoryTopics: ["zero-trust", "consent", "tenant-isolation", "audit-logs", "third-party-risk"],
    toolPermissions: commonToolPermissions,
    rubricDimensions: ["security_privacy", "legal_regulatory_resilience"],
  },
  {
    id: "ux-product-lead",
    name: "UX And Product Lead",
    team: "core",
    mission: "Keep learner, faculty, admin, researcher, and reviewer workflows usable and adoption-ready.",
    owns: ["Learner workflow", "Faculty workflow", "Admin workflow", "Researcher workflow", "Accessibility"],
    outputs: commonOutputs,
    escalationTriggers: ["Workflow overload", "Accessibility gap", "Unclear primary user action"],
    memoryTopics: ["learner-ux", "faculty-ux", "admin-ux", "researcher-ux", "accessibility"],
    toolPermissions: commonToolPermissions,
    rubricDimensions: ["ux_workflow_fit", "clinical_validity", "implementation_readiness"],
  },
  {
    id: "platform-devops-lead",
    name: "Platform And DevOps Lead",
    team: "core",
    mission: "Keep hosting, observability, CI/CD, scaling, reliability, and runtime cost practical.",
    owns: ["Hosting", "CI/CD", "Observability", "Scaling", "Disaster recovery", "Cost controls"],
    outputs: commonOutputs,
    escalationTriggers: ["Cloud cost unsupported", "No rollback path", "Observability gap"],
    memoryTopics: ["hosting", "observability", "cost", "ci-cd", "disaster-recovery"],
    toolPermissions: commonToolPermissions,
    rubricDimensions: ["technical_feasibility", "cost_performance_efficiency"],
  },
  {
    id: "open-source-governance-lead",
    name: "Open Source And Governance Lead",
    team: "core",
    mission: "Make open-source strategy sustainable, governable, and compatible with enterprise value capture.",
    owns: ["Licensing", "Contributor rules", "Scenario certification", "Marketplace trust", "Open-core boundary"],
    outputs: commonOutputs,
    escalationTriggers: ["Fork risk unresolved", "Contributor IP gap", "Marketplace trust gap"],
    memoryTopics: ["open-source", "licensing", "contributor-governance", "marketplace-trust"],
    toolPermissions: commonToolPermissions,
    rubricDimensions: ["open_source_sustainability", "legal_regulatory_resilience"],
  },
  {
    id: "business-gtm-lead",
    name: "Business And GTM Lead",
    team: "core",
    mission: "Keep the plan grounded in buyer reality, pilot design, procurement, pricing, and expansion sequencing.",
    owns: ["Buyer segmentation", "Design partners", "Pilot packaging", "Pricing", "Procurement", "Competitive wedge"],
    outputs: commonOutputs,
    escalationTriggers: ["Buyer unclear", "Pilot proof point weak", "Pricing unsupported"],
    memoryTopics: ["gtm", "pricing", "procurement", "design-partners", "competition"],
    toolPermissions: [...commonToolPermissions, "internet-research-when-approved"],
    rubricDimensions: ["market_gtm_strength", "cost_performance_efficiency", "evidence_discipline"],
  },
  {
    id: "implementation-planning-lead",
    name: "Implementation Planning Lead",
    team: "core",
    mission: "Convert mature architecture into executable code plans with file ownership, TDD sequencing, dependency gates, and commit boundaries.",
    owns: ["Code implementation plan", "Task decomposition", "TDD sequence", "Commit strategy", "Dependency readiness gates"],
    outputs: commonOutputs,
    escalationTriggers: ["Plan has placeholders", "Task has no test", "Dependency gate missing", "Ownership conflict"],
    memoryTopics: ["implementation-plan", "task-sequencing", "tdd", "commit-boundaries"],
    toolPermissions: [...commonToolPermissions, "run-agent-cli-tools"],
    rubricDimensions: ["implementation_readiness", "architecture_coherence", "evidence_discipline"],
  },
  {
    id: "local-ai-inference-engineer",
    name: "Local AI Inference Engineer",
    team: "core",
    mission: "Own local-only model runtime feasibility across MLX, llama.cpp, Ollama, Qwen, DeepSeek, Kimi, and hardware-specific benchmark gates.",
    owns: ["Local LLM runtime", "Model selection", "Hardware benchmark plan", "Quantization strategy", "No-cloud inference fallback"],
    outputs: commonOutputs,
    escalationTriggers: ["Model too large for hardware", "License unclear", "Throughput below simulation budget", "Install path blocks developers"],
    memoryTopics: ["local-llm", "mlx", "llama-cpp", "qwen", "deepseek", "kimi", "apple-silicon"],
    toolPermissions: [...commonToolPermissions, "run-local-spikes", "internet-research-when-approved"],
    rubricDimensions: ["technical_feasibility", "cost_performance_efficiency", "open_source_sustainability"],
  },
  {
    id: "voice-speech-engineer",
    name: "Voice And Speech Engineer",
    team: "core",
    mission: "Own local STT/TTS/turn-taking feasibility, voice safety, VibeVoice evaluation, and fallback paths for non-cloud speech.",
    owns: ["Local voice stack", "STT", "TTS", "Turn-taking", "Voice safety", "Latency benchmarks"],
    outputs: commonOutputs,
    escalationTriggers: ["First-audio latency too high", "Voice misuse risk unresolved", "Medical vocabulary WER too high", "No text fallback"],
    memoryTopics: ["local-voice", "vibevoice", "stt", "tts", "turn-taking", "voice-safety"],
    toolPermissions: [...commonToolPermissions, "run-local-spikes", "internet-research-when-approved"],
    rubricDimensions: ["technical_feasibility", "security_privacy", "cost_performance_efficiency"],
  },
  {
    id: "test-automation-lead",
    name: "Test Automation Lead",
    team: "core",
    mission: "Make the implementation plan test-first across domain, adapters, admin UI, XR smoke, asset QA, and scenario simulation.",
    owns: ["Test pyramid", "TDD harness", "Storybook tests", "Serenity acceptance tests", "XR smoke tests", "CI gates"],
    outputs: commonOutputs,
    escalationTriggers: ["Untested task", "Flaky workflow", "XR test gap", "No fixture for scenario behavior"],
    memoryTopics: ["test-automation", "tdd", "storybook", "serenity", "playwright", "xr-smoke"],
    toolPermissions: [...commonToolPermissions, "run-agent-cli-tools"],
    rubricDimensions: ["implementation_readiness", "technical_feasibility", "evidence_discipline"],
  },
  {
    id: "legal-regulatory-counsel",
    name: "Legal And Regulatory Counsel",
    team: "legal",
    mission: "Spot legal and regulatory issues and prepare counsel-ready questions without replacing licensed counsel.",
    owns: ["Legal issue spotting", "Regulatory boundaries", "Liability framing", "Contract risk", "Procurement risk"],
    outputs: commonOutputs,
    escalationTriggers: ["Regulated claim", "Liability gap", "Contract or procurement assumption unsupported"],
    memoryTopics: ["legal-risk", "regulatory-boundaries", "liability", "contracts"],
    toolPermissions: [...commonToolPermissions, "internet-research-when-approved"],
    rubricDimensions: ["legal_regulatory_resilience", "evidence_discipline"],
  },
  {
    id: "healthcare-compliance-counsel",
    name: "Healthcare Compliance Counsel",
    team: "legal",
    mission: "Maintain institutional compliance posture for learner records, consent, retention, privacy, and auditability.",
    owns: ["FERPA posture", "HIPAA-adjacent safeguards", "BAA readiness", "Consent", "Retention", "Data residency"],
    outputs: commonOutputs,
    escalationTriggers: ["Learner-record ambiguity", "Consent gap", "Data residency requirement unresolved"],
    memoryTopics: ["ferpa", "hipaa-adjacent", "baa", "consent", "retention", "data-residency"],
    toolPermissions: [...commonToolPermissions, "internet-research-when-approved"],
    rubricDimensions: ["security_privacy", "legal_regulatory_resilience"],
  },
  {
    id: "ip-open-source-counsel",
    name: "IP And Open-Source Counsel",
    team: "legal",
    mission: "Protect licensing, contribution, scenario ownership, asset provenance, and open-core boundaries.",
    owns: ["Copyright", "Licensing", "Contributor agreements", "Asset provenance", "Marketplace IP"],
    outputs: commonOutputs,
    escalationTriggers: ["Unclear asset provenance", "License incompatibility", "Contributor ownership gap"],
    memoryTopics: ["ip", "open-source-license", "asset-provenance", "scenario-ownership"],
    toolPermissions: [...commonToolPermissions, "internet-research-when-approved"],
    rubricDimensions: ["legal_regulatory_resilience", "open_source_sustainability"],
  },
  {
    id: "ai-governance-counsel",
    name: "AI Governance Counsel",
    team: "legal",
    mission: "Issue-spot AI governance, synthetic voice disclosure, model provenance, safety evaluation, and institutional approval boundaries.",
    owns: ["AI governance", "Model provenance", "Synthetic voice disclosure", "Evaluation records", "Institutional approval questions"],
    outputs: commonOutputs,
    escalationTriggers: ["Synthetic voice disclosure missing", "Model license unclear", "AI policy approval missing", "Unsafe autonomous claim"],
    memoryTopics: ["ai-governance", "model-provenance", "synthetic-voice", "institutional-policy"],
    toolPermissions: [...commonToolPermissions, "internet-research-when-approved"],
    rubricDimensions: ["legal_regulatory_resilience", "security_privacy", "evidence_discipline"],
  },
  ...[
    ["emergency-medicine-physician", "Emergency Medicine Physician", "ED triage, acute deterioration, handoff, diagnostic uncertainty, and escalation realism."],
    ["internal-medicine-physician", "Internal Medicine Physician", "Hospital medicine, diagnostic reasoning, chronic disease complexity, and longitudinal assessment realism."],
    ["family-medicine-physician", "Family Medicine Physician", "Primary care, continuity, prevention, patient communication, and broad-scope realism."],
    ["pediatrics-physician", "Pediatrics Physician", "Child safety, guardianship, age-specific communication, dosing, and pediatric escalation realism."],
    ["obgyn-physician", "OB/GYN Physician", "Pregnancy, reproductive health, consent, obstetric emergencies, and gender-sensitive scenario realism."],
    ["psychiatry-physician", "Psychiatry Physician", "Suicide risk, capacity, trauma-informed interviewing, de-escalation, and behavioral-health safety."],
    ["surgery-physician", "Surgery Physician", "Procedural judgment, perioperative communication, operative escalation, and surgical safety culture."],
    ["anesthesiology-critical-care-physician", "Anesthesiology And Critical Care Physician", "Airway, sedation, hemodynamics, ICU escalation, and high-acuity team coordination."],
    ["radiology-imaging-physician", "Radiology And Imaging Physician", "Imaging appropriateness, radiation exposure, diagnostic uncertainty, and imaging workflow realism."],
    ["neurology-physician", "Neurology Physician", "Neurologic localization, stroke pathways, seizure care, and neuro exam realism."],
    ["cardiology-physician", "Cardiology Physician", "Chest pain, arrhythmia, heart failure, cath escalation, and cardiac risk stratification."],
    ["infectious-disease-physician", "Infectious Disease Physician", "Sepsis, antimicrobial stewardship, isolation precautions, exposure risk, and diagnostic uncertainty."],
  ].map(([id, name, focus]) => ({
    id,
    name,
    team: "physicians" as const,
    mission: `Validate specialty realism and safety for ${focus}`,
    owns: ["Specialty realism", "Safety traps", "Workflow critique", "Scoring caveats", "Faculty review requirements"],
    outputs: commonOutputs,
    escalationTriggers: ["Specialty safety issue", "Scenario generalization risk", "Missing escalation path"],
    memoryTopics: ["specialty-realism", "scenario-safety", "workflow", "scoring-caveats"],
    toolPermissions: [...commonToolPermissions, "internet-research-when-approved"],
    rubricDimensions: ["clinical_validity", "specialty_clinical_generalizability", "psychometric_defensibility"],
  })),
  {
    id: "red-team-coordinator",
    name: "Red-Team Coordinator",
    team: "adversarial",
    mission: "Coordinate adversarial review and synthesize a stronger counterplan.",
    owns: ["Attack agenda", "Attack assignment", "Counterplan synthesis"],
    outputs: ["Attack brief", "Counterplan", "High-severity hole list", "Replacement recommendations"],
    escalationTriggers: ["Core plan has unchallenged critical assumption", "Counterplan lacks replacement"],
    memoryTopics: ["attack-patterns", "counterplans", "missed-risks"],
    toolPermissions: commonToolPermissions,
    rubricDimensions: ["adversarial_robustness", "implementation_readiness"],
  },
  ...[
    ["feasibility-skeptic", "Feasibility Skeptic", "engineering complexity, sequencing, dependencies, and staffing assumptions", ["technical_feasibility", "implementation_readiness"]],
    ["clinical-safety-critic", "Clinical Safety Critic", "unsafe clinical assumptions, misleading feedback, and oversight gaps", ["clinical_validity", "specialty_clinical_generalizability"]],
    ["psychometric-overclaim-critic", "Psychometric Overclaim Critic", "validity, reliability, fairness, and premature score-use claims", ["psychometric_defensibility", "evidence_discipline"]],
    ["security-privacy-attacker", "Security And Privacy Attacker", "threat model, consent, tenant isolation, third-party APIs, and audit holes", ["security_privacy", "legal_regulatory_resilience"]],
    ["cost-performance-attacker", "Cost And Performance Attacker", "latency, headset performance, model cost, cloud cost, and operational economics", ["cost_performance_efficiency", "technical_feasibility"]],
    ["procurement-gtm-critic", "Procurement And GTM Critic", "buyer assumptions, procurement friction, pilot economics, and renewal logic", ["market_gtm_strength", "evidence_discipline"]],
    ["open-source-sustainability-critic", "Open-Source Sustainability Critic", "governance fragility, fork risk, support burden, and open-core value capture", ["open_source_sustainability", "legal_regulatory_resilience"]],
    ["competitor-fork-strategist", "Competitor And Fork Strategist", "incumbent response, regional forks, and platform displacement risk", ["market_gtm_strength", "open_source_sustainability"]],
    ["ux-friction-critic", "UX Friction Critic", "workflow complexity, accessibility, faculty burden, and adoption friction", ["ux_workflow_fit", "clinical_validity"]],
    ["legal-liability-attacker", "Legal Liability Attacker", "malpractice framing, regulated claims, IP contamination, privacy exposure, and contract weakness", ["legal_regulatory_resilience", "security_privacy"]],
    ["specialty-clinical-attacker", "Specialty Clinical Attacker", "whether plans generalize safely across specialties", ["specialty_clinical_generalizability", "clinical_validity"]],
    ["local-model-performance-skeptic", "Local Model Performance Skeptic", "local LLM, voice, and Apple Silicon performance assumptions before cloud-free plans harden", ["technical_feasibility", "cost_performance_efficiency"]],
    ["voice-safety-misuse-attacker", "Voice Safety And Misuse Attacker", "synthetic voice misuse, consent, disclosure, impersonation, and learner trust risks", ["security_privacy", "legal_regulatory_resilience"]],
    ["implementation-plan-gap-attacker", "Implementation Plan Gap Attacker", "missing files, tests, task ownership, dependency gates, and executable sequencing", ["implementation_readiness", "architecture_coherence"]],
    ["supply-chain-dependency-attacker", "Supply Chain And Dependency Attacker", "npm, Python, model, asset, and generated-code supply-chain risk", ["open_source_sustainability", "security_privacy"]],
  ].map(([id, name, focus, dimensions]) => ({
    id: id as string,
    name: name as string,
    team: "adversarial" as const,
    mission: `Attack ${focus} and propose a better replacement when the Core Plan is weak.`,
    owns: ["Adversarial findings", "Replacement recommendations", "Residual risk analysis"],
    outputs: commonOutputs,
    escalationTriggers: ["Critical gap found", "Replacement requires leadership decision", "Core revision ignores valid attack"],
    memoryTopics: ["attack-findings", "replacement-options", "residual-risk"],
    toolPermissions: [...commonToolPermissions, "internet-research-when-approved"],
    rubricDimensions: dimensions as string[],
  })),
  ...[
    ["ceo-strategy-chair", "CEO And Strategy Chair", "strategic clarity, market wedge, capital story, sequencing, and organizational focus", ["market_gtm_strength", "implementation_readiness"]],
    ["cto", "CTO", "technical feasibility, architecture simplicity, staffing realism, and platform risk", ["technical_feasibility", "architecture_coherence"]],
    ["chief-medical-education-officer", "Chief Medical Education Officer", "education value, faculty trust, learner benefit, and simulation-center fit", ["clinical_validity", "ux_workflow_fit"]],
    ["chief-psychometrician", "Chief Psychometrician", "assessment defensibility, validation gates, rater process, and consequence validity", ["psychometric_defensibility", "evidence_discipline"]],
    ["chief-security-privacy-officer", "Chief Security And Privacy Officer", "enterprise security, privacy posture, threat model, auditability, and third-party risk", ["security_privacy", "legal_regulatory_resilience"]],
    ["general-counsel", "General Counsel", "legal exposure, contracts, procurement risk, claim discipline, IP, and regulatory boundaries", ["legal_regulatory_resilience", "evidence_discipline"]],
    ["chief-compliance-officer", "Chief Compliance Officer", "FERPA/HIPAA-adjacent controls, retention, consent, data residency, and audit governance", ["security_privacy", "legal_regulatory_resilience"]],
    ["chief-medical-officer", "Chief Medical Officer", "patient-safety posture, clinical realism, physician acceptance, and clinical escalation guardrails", ["clinical_validity", "specialty_clinical_generalizability"]],
    ["specialty-advisory-board-chair", "Specialty Advisory Board Chair", "cross-specialty coherence and specialty reviewer activation", ["specialty_clinical_generalizability", "clinical_validity"]],
    ["cfo-operations-lead", "CFO And Operations Lead", "budget, unit economics, headcount, cloud/model cost, pilot economics, and operational practicality", ["cost_performance_efficiency", "market_gtm_strength"]],
    ["product-growth-executive", "Product And Growth Executive", "product packaging, adoption friction, onboarding, retention, and design partner value", ["ux_workflow_fit", "market_gtm_strength"]],
    ["external-academic-advisor", "External Academic Advisor", "academic credibility, study design practicality, faculty incentives, and institutional trust", ["evidence_discipline", "clinical_validity"]],
    ["investor-board-skeptic", "Investor And Board Skeptic", "venture-scale plausibility, kill criteria, defensibility, and opportunity cost", ["market_gtm_strength", "cost_performance_efficiency"]],
    ["rotating-specialty-physician-reviewer", "Rotating Specialty Physician Reviewer", "scenario-specific specialty safety and realism", ["specialty_clinical_generalizability", "clinical_validity"]],
    ["vp-engineering-delivery", "VP Engineering Delivery", "implementation sequencing, staffing realism, build-vs-spike gates, and release readiness", ["implementation_readiness", "technical_feasibility"]],
    ["chief-ai-safety-officer", "Chief AI Safety Officer", "AI safety governance, model evaluation, synthetic voice misuse, and autonomous-agent containment", ["security_privacy", "legal_regulatory_resilience"]],
    ["simulation-center-director", "Simulation Center Director", "faculty operations, simulation-lab workflow, scenario review load, and learner adoption", ["ux_workflow_fit", "clinical_validity"]],
    ["chief-nursing-interprofessional-officer", "Chief Nursing And Interprofessional Officer", "nursing actor realism, team communication, escalation, and interprofessional education", ["clinical_validity", "specialty_clinical_generalizability"]],
  ].map(([id, name, focus, dimensions]) => ({
    id: id as string,
    name: name as string,
    team: "leadership" as const,
    mission: `Provide senior leadership review for ${focus}.`,
    owns: ["Leadership findings", "Approval status", "Required revisions", "Blocking issues"],
    outputs: commonOutputs,
    escalationTriggers: ["Approval threshold not met", "Blocking issue found", "Kill criterion triggered"],
    memoryTopics: ["leadership-review", "approval-gates", "blocking-issues"],
    toolPermissions: [...commonToolPermissions, "internet-research-when-approved"],
    rubricDimensions: dimensions as string[],
  })),
];

const ids = new Set<string>();
for (const agent of agentRoster) {
  if (ids.has(agent.id)) {
    throw new Error(`Duplicate agent id: ${agent.id}`);
  }
  ids.add(agent.id);
}
