import { existsSync, readdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Test file root freeze (ArchUnit-style; "tools/openclinxr/evidence/ root never gains a .test.ts").
 *
 * WHY: tools/openclinxr/evidence/ holds 560 .test.ts files in ONE flat directory, and the
 * repo's own delegation protocol tells every worker to plant a RED there. Seven of the
 * seventeen conflict-resolving merges in 1,500 commits were test files. Shared test files
 * are the largest serialization class in this repo at 33.1% of excess-writer events, ahead
 * of source modules at 23.9%.
 *
 * WHAT IS COUNTED:
 *   Root-level .test.ts files directly under tools/openclinxr/evidence/ (no subdirectories).
 *
 * RATCHET SEMANTICS (same as checks/file-size-budgets.ts and checks/stand-in-freeze.ts):
 *   The count is frozen at the current measurement (560) and may only FALL. A new root-level
 *   test file raises the count and fails the gate. The fix is to plant the RED in a
 *   subdirectory named for its subject, never at the root. Do NOT raise the frozen number.
 *
 * ESCAPE ROUTE: A test file in a SUBDIRECTORY is never counted, so the escape route is
 * always open. Workers MUST plant REDs into a subdirectory (e.g. tools/openclinxr/evidence/<subject>/).
 *
 * DO NOT MOVE the existing 560 files. Moving them would be one enormous diff and would break
 * every path that references them; the ratchet exists so the count comes down as REDs are
 * retired and new ones land in subdirectories.
 */

const EVIDENCE_ROOT = "tools/openclinxr/evidence";

function findWorkspaceRoot(): string {
  let dir = dirname(fileURLToPath(import.meta.url));
  for (let i = 0; i < 12; i += 1) {
    try {
      readFileSync(join(dir, "pnpm-workspace.yaml"));
      return dir;
    } catch {
      dir = dirname(dir);
    }
  }
  throw new Error("workspace root (pnpm-workspace.yaml) not found");
}

/** Count root-level .test.ts files in tools/openclinxr/evidence/ (non-recursive). */
export function countRootTestFiles(): number {
  const root = findWorkspaceRoot();
  const evidenceDir = join(root, EVIDENCE_ROOT);
  if (!existsSync(evidenceDir)) return 0;
  let count = 0;
  for (const entry of readdirSync(evidenceDir, { withFileTypes: true })) {
    if (!entry.isFile()) continue;
    if (entry.name.endsWith(".test.ts") || entry.name.endsWith(".test.tsx") || entry.name.endsWith(".test.mts")) {
      count += 1;
    }
  }
  return count;
}

/**
 * Frozen root-level test file count. Generated by running countRootTestFiles() against a
 * clean tree. This number may only be LOWERED; never raise it to excuse a new root-level test.
 */
export const ROOT_TEST_FILE_FREEZE = 560;

export type RootTestFreezeViolation = { detail: string };

/**
 * Fails if the current root-level count EXCEEDS the frozen count.
 */
export function checkRootTestFileFreeze(
  freeze: number = ROOT_TEST_FILE_FREEZE,
  measured: number = countRootTestFiles(),
): RootTestFreezeViolation[] {
  const violations: RootTestFreezeViolation[] = [];
  if (measured > freeze) {
    violations.push({
      detail:
        `tools/openclinxr/evidence/ root has ${measured} .test.ts file(s) > frozen ${freeze}. ` +
        "A new root-level test file is a serialization hotspot: 33.1% of excess-writer events, " +
        "seven of seventeen conflict merges were test files. FIX: plant the RED in a subdirectory " +
        "named for its subject (e.g. tools/openclinxr/evidence/<subject>/). Counts only shrink — " +
        "do NOT raise this number.",
    });
  }
  return violations;
}

/**
 * Fails if the freeze sits ABOVE the current measurement — the ratchet must tighten.
 */
export function checkRootTestFileFreezeIsHonest(
  freeze: number = ROOT_TEST_FILE_FREEZE,
  measured: number = countRootTestFiles(),
): RootTestFreezeViolation[] {
  const violations: RootTestFreezeViolation[] = [];
  if (measured < freeze) {
    violations.push({
      detail:
        `tools/openclinxr/evidence/ root frozen at ${freeze} but now measures ${measured}. ` +
        "Lower the freeze entry to the measurement so the ceiling keeps tracking the tree.",
    });
  }
  return violations;
}