/**
 * Public interface of @openclinxr/xr-runtime-state.
 *
 * Named lists, not `export *`. A star republishes a module wholesale, so a symbol added inside
 * becomes public with nobody deciding it should be. Generated by `pnpm arch:narrow-entrypoint`
 * from what the tree actually consumes, then proved by `pnpm packages:typecheck:agent`.
 */

export {
  bodyDirectionWithinAllowance,
  composedIdleBodyHeading,
  IDLE_BODY_DIRECTION_ALLOWANCE_RADIANS,
} from "./composed-body-direction.js";
export type {
  GeneratedDriveScalarInput,
  GeneratedDriveScalarValue,
} from "./generated-drive-scalar.js";
export {
  generatedDriveScalar,
} from "./generated-drive-scalar.js";
export {
  INFINIGEN_ENVIRONMENT_ASSETS,
} from "./infinigen-environment-assets.js";
export type { ActorPlacementSsotEvidence } from "./runtime-actor-placements.js";
// The placement SSOT repair and its evidence shape are consumed by apps/ui-xr and asserted by
// xr-scene's framing-guard RED. Neither could reach them: they were defined in
// runtime-actor-placements.ts and never re-exported, which the entrypoint-import ratchet
// (architecture-rules/src/checks/entrypoint-imports-resolve.ts) recorded as its second entry.
export {
  ADDITIONAL_CAST_FRAMING_XZ,
  additionalCastPlacementFallback,
  ensureActorPlacementsForStagedSlots,
  ensureAndPublishActorPlacementSsot,
} from "./runtime-actor-placements.js";
export type {
  RuntimeSlotAssignment,
} from "./runtime-actor-slots.js";
export {
  assignRuntimeActorSlots,
} from "./runtime-actor-slots.js";
export {
  resolveLocalEnvironmentRuntimeAssetFileName,
  resolveLocalEquipmentRuntimeAssetFileName,
} from "./runtime-local-asset-filenames.js";
export type {
  ActorPlayerRuntimeMetadataSummary,
  CaseDefinedHumanoidPerformanceContractEvidence,
  CaseDefinedHumanoidRuntimeHandoffEvidence,
  ConversationTurnStateEvidence,
  EnvironmentStateEvidence,
  ExamAssemblyPersistenceSink,
  ExamFormRunState,
  ExamineeLocomotionEvidence,
  ExamRunStationOutcome,
  HumanoidSpeechEvidence,
  LearnerCanonicalExamPhaseView,
  LearnerCanonicalPhaseTraceStore,
  LearnerExamFlowPhase,
  LearnerRuntimeUseGateEvidence,
  LocomotionAttemptDiagnosticsEvidence,
  LocomotionVectorEvidence,
  ManualEvidenceCopyDisposition,
  ManualPerformanceCaptureSummary,
  ManualPerformanceDraft,
  ManualPerformanceFrameStats,
  ManualPerformanceInputEvidence,
  ManualPerformanceReproducibilityEvidence,
  ManualPerformanceTraceLatencyEvidence,
  ReadableVrTextPanelEvidence,
  ReadableVrTextPanelEvidenceSet,
  RigPoseEvidence,
  RuntimeEvidencePosture,
  RuntimeInteractionEvidence,
  RuntimeMaterializationEvidenceAttachmentSummary,
  RuntimeRemainingRuntimeBlockerReasons,
  RuntimeSceneManifestEvidence,
  SceneAssetEvidence,
  TraceReadinessSummary,
  XrExperienceModeEvidence,
  XrHandGestureStateEvidence,
  XrHandSelectStateEvidence,
  XrInputSourceEvidence,
  XrRuntimeReadinessDecision,
  XrRuntimeState,
  XrTraceActionHandoffAction,
  XrTraceActionHandoffEvidence,
  XrTraceInteractionEvidenceSummary,
} from "./runtime-state.js";
export {
  actorIdForTraceTag,
  actorResponseTextFromApiResult,
  admitLearnerCanonicalPhaseEvent,
  advanceExamFormRunStation,
  applyLearnerExamFlowIntent,
  buildConversationTurnStateEvidence,
  buildIwsdkStationMcpSmokePlan,
  buildManualPerformanceCaptureSummary,
  buildManualPerformanceDraft,
  buildManualPerformanceEvidencePayload,
  buildManualPerformanceInputEvidence,
  buildManualPerformanceReproducibility,
  buildReadableVrTextPanelEvidence,
  buildRuntimeEvidencePosture,
  buildRuntimeFrameStats,
  buildXrRuntimeReadinessDecision,
  buildXrTraceActionHandoffEvidence,
  buildXrTraceInteractionEvidenceSummary,
  completeTraceAction,
  createInitialRuntimeState,
  createLearnerCanonicalPhaseTraceStore,
  createMultiStationExamRuntime,
  createRuntimeStateFromBundle,
  currentExamFormRunStation,
  eventTypeForTraceTag,
  examFormRunScenarioSequence,
  formatExamFormRunClock,
  formatManualEvidenceCopyStatus,
  formatStationClock,
  handGestureLocomotionOriginMeters,
  handGestureRelativeOffsetMeters,
  isImmersiveFrameEvidenceActive,
  iwsdkStationMcpSmokePlanHash,
  iwsdkStationSceneObjectNames,
  iwsdkStationSceneObjects,
  LEARNER_CANONICAL_PHASE_TYPES,
  LEARNER_EXAM_PHASE_NOT_EVIDENCE_FOR,
  localHandMeshPath,
  mapHandGestureLocomotionVector,
  meshHandModelProfile,
  meshHandRepresentationKind,
  nextExamFormRunStation,
  persistExamFormRunQueueSnapshot,
  primitiveHandModelProfile,
  primitiveHandRepresentationKind,
  readRuntimeActorEquipmentMaterializationGate,
  remoteActorTurnForTraceTag,
  restoreLearnerCanonicalPhaseTraceFromJson,
  stepEmotionStateFromCaseMachine,
  summarizeTraceReadiness,
  tickExamFormRunClock,
  viewLearnerCanonicalExamPhase,
  xrExperienceModeEvidence,
} from "./runtime-state.js";
export {
  authoredSafetyCriticalTraceTagsForScenario,
  authoredTraceTagsForScenario,
  deriveRuntimeTraceActionTagsFromBundle,
  deriveScenarioTraceActionTags,
  resolveRemoteActorTurnForTraceTag,
  scenarioActorIdsForScenario,
} from "./scenario-conversation-surface.js";
export {
  authoredPlantOffsetMeters,
  supportedActorPlacementPosition,
} from "./supported-actor-placement.js";
