/**
 * Public interface of @openclinxr/xr-trace-readiness.
 *
 * Named lists, not `export *`. A star republishes a module wholesale, so a symbol added inside
 * becomes public with nobody deciding it should be. Generated by `pnpm arch:narrow-entrypoint`
 * from what the tree actually consumes, then proved by `pnpm packages:typecheck:agent`.
 */
export type {
  PedsActorListenerCueContext,
} from "./types.js";
export {
  buildHumanoidSpeechEvidence,
  buildRuntimeReproducibilityEvidence,
  createFrameAccumulator,
  createTraceSelectLatencyRecorder,
  formatLearnerRuntimeUseGate,
  formatMaterializationAttachmentSummary,
  formatRemainingRuntimeBlockerReasons,
  formatRuntimePostureLane,
  formatRuntimeReadinessDecision,
  formatTechnicalGapStatus,
  formatTraceInteractionEvidenceSummary,
  recordFrame,
  recordTraceSelectLatency,
  updateManualEvidencePanel,
  updateRuntimePosturePanel,
  updateTraceActionHandoffEvidence,
  updateTraceInteractionEvidenceSummary,
  updateTraceReadiness,
  updateXrStatus,
} from "./trace-panels.js";
export {
  ROOM_ENVIRONMENTAL_REALISM_CUE_IDS,
  formatEnvironmentRoomSummary,
  updateEnvironmentStateForTrace,
} from "./environment-trace.js";
export {
  applyPedsActorPlayerSequenceListenerCues,
  formatActorPlayerRuntimeMetadataSummary,
  pedsActorPlayerRuntimeTurns,
  recordPedsActorPlayerRuntimePlaybackEvidence,
} from "./peds-actor-playback.js";
