import { existsSync, readdirSync, readFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

/**
 * Shrink-only freeze of relative imports that reach another package's src/.
 * In-package imports stay legal. A new specifier fails until the reach is removed.
 * A listed specifier that disappears fails until this list drops it in the same change.
 * claimScope: new cross-package relative src imports are refused.
 * notEvidenceFor: that the public export surface shrank.
 */

const ROOT = path.resolve(import.meta.dirname, "../../../../../");
const SKIP = new Set([
  "node_modules",
  "dist",
  "coverage",
  "build",
  ".git",
  ".claude",
  ".grok",
  ".openclinxr",
  ".turbo",
]);
const EXT = new Set([".ts", ".tsx", ".js", ".mjs", ".cjs", ".mts"]);

function walk(dir: string, out: string[]): void {
  for (const ent of readdirSync(dir, { withFileTypes: true })) {
    if (SKIP.has(ent.name)) continue;
    const p = path.join(dir, ent.name);
    if (ent.isDirectory()) walk(p, out);
    else if (EXT.has(path.extname(ent.name))) out.push(p);
  }
}

function packageRoot(file: string): string | null {
  let dir = path.dirname(file);
  while (dir.startsWith(ROOT)) {
    if (existsSync(path.join(dir, "package.json"))) return dir;
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return null;
}

function crossPackageSrcReaches(): string[] {
  const files: string[] = [];
  walk(ROOT, files);
  const hits: string[] = [];
  const re = /(?:from\s+|import\s*\(\s*|require\s*\(\s*)['"](\.[^'"]+)['"]/g;
  for (const file of files) {
    const text = readFileSync(file, "utf8");
    const importerPkg = packageRoot(file);
    let match: RegExpExecArray | null;
    const seen = new Set<string>();
    while ((match = re.exec(text))) {
      const spec = match[1] ?? "";
      const resolved = path.normalize(path.join(path.dirname(file), spec));
      const targetPkg = packageRoot(resolved);
      if (!importerPkg || !targetPkg || importerPkg === targetPkg) continue;
      const relTarget = path.relative(targetPkg, resolved);
      if (!relTarget.split(path.sep).includes("src")) continue;
      const key = `${path.relative(ROOT, file)} -> ${spec}`;
      if (seen.has(key)) continue;
      seen.add(key);
      hits.push(key);
    }
  }
  hits.sort();
  return hits;
}

const FROZEN: readonly string[] = [
  "apps/ui-xr/src/learner-debrief/counterfactual/counterfactual-replay.test.ts -> ../../../../../packages/openclinxr/review-workflow/src/counterfactual-debrief/counterfactual-debrief.js",
  "apps/ui-xr/src/static-assets.test.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "apps/ui-xr/src/the-normal-consumer-replays-and-invalidates-the-frozen-scene.test.ts -> ../../../packages/openclinxr/review-workflow/src/accepted-scene-plan-review-mod.js",
  "apps/ui-xr/src/the-normal-consumer-replays-and-invalidates-the-frozen-scene.test.ts -> ../../../packages/openclinxr/session-state/src/accepted-scene-plan.js",
  "apps/ui-xr/src/the-normal-consumer-replays-and-invalidates-the-frozen-scene.test.ts -> ../../../packages/openclinxr/xr-scene/src/encounter-actor-framing.js",
  "apps/ui-xr/src/the-runtime-reproduces-the-frozen-room-digest.test.ts -> ../../../packages/openclinxr/xr-scene/src/encounter-actor-framing.js",
  "apps/ui-xr/tests/actor-audio-compat.ts -> ../../../packages/openclinxr/xr-dialogue/src/actor-audio-playback-clock.js",
  "apps/ui-xr/tests/actor-audio-compat.ts -> ../../../packages/openclinxr/xr-dialogue/src/actor-audio-prepared-data.js",
  "packages/openclinxr-verification/architecture-rules/src/archunit-tests/the-factory-does-not-import-the-apps-it-feeds.test.ts -> ../../../../apps/ui-xr/src/station-environment.js",
  "packages/openclinxr/motion-compiler/src/an-action-binds-to-an-authored-source.test.ts -> ../../scenario-fixtures/src/index.js",
  "packages/openclinxr/motion-compiler/src/compile-motion-program.ts -> ../../scenario-fixtures/src/touch-response-clip.js",
  "packages/openclinxr/motion-compiler/src/primitives/guard-body-region.ts -> ../../../asset-registry/src/pose-bone-resolver.js",
  "packages/openclinxr/motion-compiler/src/regions/region-anchors.ts -> ../../../asset-registry/src/pose-bone-resolver.js",
  "packages/openclinxr/motion-compiler/src/the-guard-primitive-hits-four-targets-on-three-rigs.test.ts -> ../../scenario-fixtures/src/index.js",
  "packages/openclinxr/motion-compiler/src/the-llm-planner-cannot-emit-bone-tracks.test.ts -> ../../review-workflow/src/scenario-publication.js",
  "packages/openclinxr/motion-compiler/src/the-llm-planner-cannot-emit-bone-tracks.test.ts -> ../../scenario-fixtures/src/ed-chest-pain.js",
  "packages/openclinxr/motion-compiler/src/the-planner-emits-a-validated-motion-program.test.ts -> ../../scenario-fixtures/src/adult-abdominal-pain.js",
  "packages/openclinxr/motion-compiler/src/the-planner-schema-admits-no-unknown-payload.test.ts -> ../../scenario-fixtures/src/ed-chest-pain.js",
  "packages/openclinxr/motion-compiler/src/the-resolved-clip-id-is-what-the-compiler-produces.test.ts -> ../../scenario-fixtures/src/scenario-bank.js",
  "packages/openclinxr/motion-compiler/src/the-seed-is-derived-from-five-case-inputs.test.ts -> ../../scenario-fixtures/src/adult-abdominal-pain.js",
  "tools/agent-factory/agent-loop-plan.ts -> ../../packages/openclinxr/agent-loop/src/index.js",
  "tools/agent-factory/agent-loop-plan.ts -> ../../packages/openclinxr/agent-loop/src/types.js",
  "tools/agent-factory/append-role-memory-lesson.ts -> ../../packages/openclinxr/agent-loop/src/role-harness-policy.js",
  "tools/agent-factory/check-source-ledger.test.ts -> ../../packages/openclinxr/arena/iwsdk-spike/src/index.js",
  "tools/agent-factory/check-source-ledger.ts -> ../../packages/openclinxr/arena/iwsdk-spike/src/index.js",
  "tools/agent-factory/generate-harness-agents.ts -> ../../packages/openclinxr/agent-loop/src/grok-repo-agent-spawn.js",
  "tools/agent-factory/generate-harness-agents.ts -> ../../packages/openclinxr/agent-loop/src/role-harness-policy.js",
  "tools/agent-factory/generate-harness-manifest.ts -> ../../packages/openclinxr/agent-loop/src/harness-neutral-manifest.js",
  "tools/agent-factory/prove-grok-harness.ts -> ../../packages/openclinxr/agent-loop/src/grok-repo-agent-spawn.js",
  "tools/agent-factory/prove-grok-harness.ts -> ../../packages/openclinxr/agent-loop/src/grok-tier-routing.js",
  "tools/agent-factory/prove-grok-harness.ts -> ../../packages/openclinxr/agent-loop/src/grok-token-introspection.js",
  "tools/agent-factory/prove-grok-harness.ts -> ../../packages/openclinxr/agent-loop/src/index.js",
  "tools/agent-factory/prove-grok-harness.ts -> ../../packages/openclinxr/agent-loop/src/role-harness-policy.js",
  "tools/agent-factory/validate-harness-boundaries.ts -> ../../packages/openclinxr/agent-loop/src/harness-neutral-manifest.js",
  "tools/agent-factory/validate-harness-boundaries.ts -> ../../packages/openclinxr/agent-loop/src/role-harness-policy.js",
  "tools/openclinxr/api-mongo-boot.ts -> ../../apps/api/src/index.js",
  "tools/openclinxr/api-mongo-boot.ts -> ../../packages/openclinxr/data-mongodb/src/index.js",
  "tools/openclinxr/architecture/narrow-entrypoint.ts -> ../../../packages/openclinxr-verification/architecture-rules/src/checks/export-surface-budgets.ts",
  "tools/openclinxr/architecture/narrow-entrypoint.ts -> ../../../packages/openclinxr-verification/architecture-rules/src/checks/unused-entrypoint-exports.ts",
  "tools/openclinxr/architecture/public-surface/acceptance.ts -> ../../../../packages/openclinxr-verification/architecture-rules/src/checks/public-surface/acceptance-criteria.js",
  "tools/openclinxr/architecture/public-surface/acceptance.ts -> ../../../../packages/openclinxr-verification/architecture-rules/src/checks/public-surface/gates.js",
  "tools/openclinxr/architecture/public-surface/acceptance.ts -> ../../../../packages/openclinxr-verification/architecture-rules/src/checks/public-surface/resolve.js",
  "tools/openclinxr/architecture/public-surface/acceptance.ts -> ../../../../packages/openclinxr-verification/architecture-rules/src/checks/public-surface/runner.js",
  "tools/openclinxr/architecture/public-surface/verify.ts -> ../../../../packages/openclinxr-verification/architecture-rules/src/checks/public-surface/resolve.js",
  "tools/openclinxr/architecture/public-surface/verify.ts -> ../../../../packages/openclinxr-verification/architecture-rules/src/checks/public-surface/runner.js",
  "tools/openclinxr/architecture/unused-exports-report.ts -> ../../../packages/openclinxr-verification/architecture-rules/src/checks/unused-entrypoint-exports.ts",
  "tools/openclinxr/architecture/write-context-ceilings.ts -> ../../../packages/openclinxr-verification/architecture-rules/src/checks/context-field-budgets.ts",
  "tools/openclinxr/architecture/write-context-ceilings.ts -> ../../../packages/openclinxr-verification/architecture-rules/src/checks/export-surface-budgets.ts",
  "tools/openclinxr/architecture/write-context-ceilings.ts -> ../../../packages/openclinxr-verification/architecture-rules/src/checks/test-import-surface.ts",
  "tools/openclinxr/architecture/write-package-agent-index.ts -> ../../../packages/openclinxr-verification/architecture-rules/src/checks/package-agent-index.ts",
  "tools/openclinxr/asset-pipeline/makeclothes/body-param-cli.ts -> ../../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/asset-pipeline/motion/index.ts -> ../../../../packages/openclinxr/motion-compiler/src/index.ts",
  "tools/openclinxr/asset-pipeline/trellis/factory-case-cli.ts -> ../../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/asset-pipeline/trellis/factory-case-cli.ts -> ../../../../packages/openclinxr/scenario-fixtures/src/scenario-bank.js",
  "tools/openclinxr/dark-factory/export-actor-phenotype.ts -> ../../../packages/openclinxr/scenario-fixtures/src/actor-phenotype-export.js",
  "tools/openclinxr/dark-factory/multi-case-runner.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/dark-factory/multi-case-runner.ts -> ../../../packages/openclinxr/asset-registry/src/actor-placement.js",
  "tools/openclinxr/dark-factory/multi-case-runner.ts -> ../../../packages/openclinxr/asset-registry/src/runtime-bundles.js",
  "tools/openclinxr/dark-factory/multi-case-runner.ts -> ../../../packages/openclinxr/factory-stations/src/lip_sync/fixture-wav.js",
  "tools/openclinxr/dark-factory/multi-case-runner.ts -> ../../../packages/openclinxr/scenario-fixtures/src/ed-chest-pain.js",
  "tools/openclinxr/dark-factory/multi-case-runner.ts -> ../../../packages/openclinxr/scenario-fixtures/src/scenario-bank.js",
  "tools/openclinxr/dark-factory/multi-case-runner.ts -> ../../../packages/openclinxr/shared-schemas/src/index.js",
  "tools/openclinxr/delegation/score.ts -> ../../../packages/openclinxr/agent-loop/src/model-pricing.js",
  "tools/openclinxr/encounter-runtime-emission.ts -> ../../packages/openclinxr/scenario-fixtures/src/index.js",
  "tools/openclinxr/encounter-runtime-emission.ts -> ../../packages/openclinxr/scenario-runtime/src/index.js",
  "tools/openclinxr/encounter-runtime-emission.ts -> ../../packages/openclinxr/shared-schemas/src/index.js",
  "tools/openclinxr/evidence/a-case-without-a-preset-still-produces-actor-params.test.ts -> ../../../packages/openclinxr/scenario-fixtures/src/actor-phenotype-export.js",
  "tools/openclinxr/evidence/a-cast-eligible-gowned-mpfb-patient-exists.test.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/a-cast-recast-does-not-red-the-api-shell.test.ts -> ../../../packages/openclinxr/asset-registry/src/cast-asset-constants.js",
  "tools/openclinxr/evidence/a-declared-body-shape-reaches-the-baked-body.test.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/a-declared-body-shape-reaches-the-baked-body.test.ts -> ../../../packages/openclinxr/scenario-fixtures/src/actor-phenotype-export.js",
  "tools/openclinxr/evidence/a-described-patient-gets-a-body-that-height.test.ts -> ../../../packages/openclinxr/scenario-fixtures/src/index.js",
  "tools/openclinxr/evidence/a-stale-measurement-stops-deciding-readiness.test.ts -> ../../../packages/openclinxr/asset-registry/src/measured-station-geometry-freshness.js",
  "tools/openclinxr/evidence/a-stale-measurement-stops-deciding-readiness.test.ts -> ../../../packages/openclinxr/rest/src/api-route-support.js",
  "tools/openclinxr/evidence/a-station-cast-is-visually-separable.test.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/a-succeeded-job-does-not-reference-artifacts-nobody-wrote.test.ts -> ../../../packages/openclinxr/capability-gateway/src/asset-generation-jobs.js",
  "tools/openclinxr/evidence/actor-floor-contact-all-stations.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/actor-garment-presence-in-scene.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/actor-identity-and-wardrobe.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/actor-placement-ssot.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/actor-slot-assignment.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/actor-slot-assignment.ts -> ../../../packages/openclinxr/scenario-fixtures/src/scenario-bank.js",
  "tools/openclinxr/evidence/actors-blink-with-their-eyelids.test.ts -> ../../../packages/openclinxr/xr-dialogue/src/viseme-runtime-wire.js",
  "tools/openclinxr/evidence/an-adult-actor-derives-a-body-profile-from-its-descriptor.test.ts -> ../../../packages/openclinxr/scenario-fixtures/src/descriptor-phenotype-lookup.js",
  "tools/openclinxr/evidence/an-adult-actor-derives-a-body-profile-from-its-descriptor.test.ts -> ../../../packages/openclinxr/scenario-fixtures/src/index.js",
  "tools/openclinxr/evidence/an-aliased-viseme-target-is-cleared-when-it-stops-being-active.test.ts -> ../../../packages/openclinxr/xr-dialogue/src/viseme-timeline-drive.js",
  "tools/openclinxr/evidence/anny-school-age-mpfb2-eye-cagematch.ts -> ../../../packages/openclinxr/arena/model-vetting/src/index.js",
  "tools/openclinxr/evidence/anny-skin-track-a-pbr-cagematch.ts -> ../../../packages/openclinxr/arena/model-vetting/src/index.js",
  "tools/openclinxr/evidence/api-bun-python-proxy-runtime-smoke.ts -> ../../../packages/openclinxr/voice-gateway/src/index.js",
  "tools/openclinxr/evidence/api-python-backend-runtime-smoke.ts -> ../../../packages/openclinxr/voice-gateway/src/index.js",
  "tools/openclinxr/evidence/arm-abduction-ceiling.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/asset-capability-job-evidence.ts -> ../../../packages/openclinxr/capability-gateway/src/asset-generation-jobs.js",
  "tools/openclinxr/evidence/asset-capability-job-evidence.ts -> ../../../packages/openclinxr/capability-gateway/src/index.js",
  "tools/openclinxr/evidence/asset-production-readiness-benchmark.ts -> ../../../packages/openclinxr/asset-registry/src/index.js",
  "tools/openclinxr/evidence/asset-production-readiness-benchmark.ts -> ../../../packages/openclinxr/asset-registry/src/runtime-bundles-entry.js",
  "tools/openclinxr/evidence/audible-lip-sync-proof/manager-lifecycle.test.mjs -> ../../../../apps/ui-xr/src/prepared-actor-audio.ts",
  "tools/openclinxr/evidence/audible-lip-sync-proof/ordinary-host-adapter.test.ts -> ../../../../apps/ui-xr/src/ordinary-actor-turn-speech.js",
  "tools/openclinxr/evidence/audible-lip-sync-proof/ordinary-host-adapter.test.ts -> ../../../../apps/ui-xr/src/prepared-actor-audio.js",
  "tools/openclinxr/evidence/audible-lip-sync-proof/playback.mjs -> ../../../../apps/ui-xr/src/prepared-actor-audio.ts",
  "tools/openclinxr/evidence/audible-lip-sync-proof/preparation-ingress.test.mjs -> ../../../../apps/ui-xr/src/prepared-actor-audio.ts",
  "tools/openclinxr/evidence/audible-lip-sync-proof/source-clock.test.mjs -> ../../../../apps/ui-xr/src/prepared-actor-audio.ts",
  "tools/openclinxr/evidence/audible-lip-sync-proof/source-wiring.test.mjs -> ../../../../apps/ui-xr/src/prepared-actor-audio.ts",
  "tools/openclinxr/evidence/audible-lip-sync-proof/typed-prepared-failure-cleanup.test.mjs -> ../../../../apps/ui-xr/src/ordinary-actor-turn-speech.ts",
  "tools/openclinxr/evidence/audible-lip-sync-proof/typed-prepared-failure-cleanup.test.mjs -> ../../../../apps/ui-xr/src/prepared-actor-audio.ts",
  "tools/openclinxr/evidence/audible-lip-sync-proof/typed-prepared-ownership.test.mjs -> ../../../../apps/ui-xr/src/ordinary-actor-turn-speech.ts",
  "tools/openclinxr/evidence/audible-lip-sync-proof/typed-prepared-ownership.test.mjs -> ../../../../apps/ui-xr/src/prepared-actor-audio.ts",
  "tools/openclinxr/evidence/authored-exam-reaches-learner.ts -> ../../../apps/api/src/index.js",
  "tools/openclinxr/evidence/authored-exam-reaches-learner.ts -> ../../../packages/openclinxr/graphql/src/documents.js",
  "tools/openclinxr/evidence/authored-exam-reaches-learner.ts -> ../../../packages/openclinxr/rest/src/api-types.js",
  "tools/openclinxr/evidence/authored-exam-reaches-learner.ts -> ../../../packages/openclinxr/scenario-fixtures/src/index.js",
  "tools/openclinxr/evidence/authored-exam-reaches-learner.ts -> ../../../packages/openclinxr/shared-schemas/src/index.js",
  "tools/openclinxr/evidence/authored-offset-on-the-posed-humanoid.ts -> ../../../packages/openclinxr/scenario-fixtures/src/index.js",
  "tools/openclinxr/evidence/azurite-asset-upload-smoke.ts -> ../../../packages/openclinxr/asset-registry/src/asset-writer-mod.js",
  "tools/openclinxr/evidence/azurite-asset-upload-smoke.ts -> ../../../packages/openclinxr/asset-registry/src/object-store-mod.js",
  "tools/openclinxr/evidence/bedside-admission-cold-boots/capture.ts -> ../../../../packages/openclinxr/asset-registry/src/case-frozen-scene-plans.js",
  "tools/openclinxr/evidence/bedside-admission-cold-boots/capture.ts -> ../../../../packages/openclinxr/asset-registry/src/runtime-bundles.js",
  "tools/openclinxr/evidence/blueprint-voice-simulation-spike.test.ts -> ../../../packages/openclinxr/exam-assembly/src/index.js",
  "tools/openclinxr/evidence/blueprint-voice-simulation-spike.test.ts -> ../../../packages/openclinxr/scenario-fixtures/src/index.js",
  "tools/openclinxr/evidence/blueprint-voice-simulation-spike.ts -> ../../../packages/openclinxr/asset-registry/src/index.js",
  "tools/openclinxr/evidence/blueprint-voice-simulation-spike.ts -> ../../../packages/openclinxr/exam-assembly/src/index.js",
  "tools/openclinxr/evidence/blueprint-voice-simulation-spike.ts -> ../../../packages/openclinxr/model-gateway/src/index.js",
  "tools/openclinxr/evidence/blueprint-voice-simulation-spike.ts -> ../../../packages/openclinxr/scenario-fixtures/src/index.js",
  "tools/openclinxr/evidence/blueprint-voice-simulation-spike.ts -> ../../../packages/openclinxr/scenario-runtime/src/index.js",
  "tools/openclinxr/evidence/blueprint-voice-simulation-spike.ts -> ../../../packages/openclinxr/scenario-runtime/src/runtime-types.js",
  "tools/openclinxr/evidence/blueprint-voice-simulation-spike.ts -> ../../../packages/openclinxr/session-state/src/index.js",
  "tools/openclinxr/evidence/blueprint-voice-simulation-spike.ts -> ../../../packages/openclinxr/shared-schemas/src/index.js",
  "tools/openclinxr/evidence/blueprint-voice-simulation-spike.ts -> ../../../packages/openclinxr/telemetry/src/index.js",
  "tools/openclinxr/evidence/blueprint-voice-simulation-spike.ts -> ../../../packages/openclinxr/voice-gateway/src/index.js",
  "tools/openclinxr/evidence/blueprint-voice-simulation-spike.ts -> ../../../packages/openclinxr/voice-gateway/src/types.js",
  "tools/openclinxr/evidence/body-param-reaches-vertices.ts -> ../../../packages/openclinxr/asset-registry/src/humanoid-body-mesh.js",
  "tools/openclinxr/evidence/bundleless-station-identity.ts -> ../../../packages/openclinxr/asset-registry/src/runtime-bundles.js",
  "tools/openclinxr/evidence/bundleless-station-identity.ts -> ../../../packages/openclinxr/scenario-fixtures/src/index.js",
  "tools/openclinxr/evidence/cagematch-report-page.ts -> ../../../packages/openclinxr/arena/model-vetting/src/cagematch-report.js",
  "tools/openclinxr/evidence/cast-identity-all-stations.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/cast-identity-ssot.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/cast-identity-ssot.ts -> ../../../packages/openclinxr/scenario-fixtures/src/scenario-bank.js",
  "tools/openclinxr/evidence/cast-identity-ssot.ts -> ../../../packages/openclinxr/xr-dialogue/src/initial-dialogue-text.js",
  "tools/openclinxr/evidence/clinical-touch/the-shipped-ed-patient-has-a-playable-rlq-response.test.ts -> ../../../../packages/openclinxr/asset-registry/src/runtime-bundle-lookups.js",
  "tools/openclinxr/evidence/clinical-touch/the-shipped-ed-patient-has-a-playable-rlq-response.test.ts -> ../../../../packages/openclinxr/asset-registry/src/runtime-bundles.js",
  "tools/openclinxr/evidence/clinical-touch/the-shipped-ed-patient-has-a-playable-rlq-response.test.ts -> ../../../../packages/openclinxr/scenario-fixtures/src/ed-chest-pain.js",
  "tools/openclinxr/evidence/clinical-touch/the-shipped-ed-patient-has-a-playable-rlq-response.test.ts -> ../../../../packages/openclinxr/xr-pose/src/index.js",
  "tools/openclinxr/evidence/clinical-touch/the-shipped-ed-patient-has-a-playable-rlq-response.test.ts -> ../../../../packages/openclinxr/xr-pose/src/supine-deck-plant.js",
  "tools/openclinxr/evidence/clinical-touch/the-shipped-ed-patient-has-a-playable-rlq-response.test.ts -> ../../../../packages/openclinxr/xr-station/src/index.js",
  "tools/openclinxr/evidence/clinicians-do-not-wear-patterned-party-shoes.test.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.ts",
  "tools/openclinxr/evidence/declared-actors-rendered.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/declared-actors-rendered.ts -> ../../../packages/openclinxr/scenario-fixtures/src/scenario-bank.js",
  "tools/openclinxr/evidence/dialogue-visemes-follow-pronunciation.test.ts -> ../../../packages/openclinxr/xr-dialogue/src/dialogue-visemes.js",
  "tools/openclinxr/evidence/dispatch-binds-the-role-charter.test.ts -> ../../../packages/openclinxr/agent-loop/src/grok-repo-agent-spawn.js",
  "tools/openclinxr/evidence/dispatch-binds-the-role-charter.test.ts -> ../../../packages/openclinxr/agent-loop/src/role-harness-policy.js",
  "tools/openclinxr/evidence/doorway-overview-camera.ts -> ../../../packages/openclinxr/asset-registry/src/environment-descriptors.js",
  "tools/openclinxr/evidence/doorway-overview-camera.ts -> ../../../packages/openclinxr/asset-registry/src/environment-zone-templates-mod.js",
  "tools/openclinxr/evidence/environment-artifacts.ts -> ../../../packages/openclinxr/asset-registry/src/runtime-bundles.js",
  "tools/openclinxr/evidence/eyes-have-an-iris.test.ts -> ../../../packages/openclinxr/asset-registry/src/morph-target-resolver.ts",
  "tools/openclinxr/evidence/faculty-review-gate.ts -> ../../../apps/api/src/index.js",
  "tools/openclinxr/evidence/faculty-review-gate.ts -> ../../../packages/openclinxr/exam-assembly/src/index.js",
  "tools/openclinxr/evidence/faculty-review-gate.ts -> ../../../packages/openclinxr/graphql/src/documents.js",
  "tools/openclinxr/evidence/faculty-review-gate.ts -> ../../../packages/openclinxr/rest/src/api-types.js",
  "tools/openclinxr/evidence/faculty-review-gate.ts -> ../../../packages/openclinxr/rest/src/exam-assembly-pool.js",
  "tools/openclinxr/evidence/faculty-review-gate.ts -> ../../../packages/openclinxr/scenario-fixtures/src/index.js",
  "tools/openclinxr/evidence/faculty-review-gate.ts -> ../../../packages/openclinxr/shared-schemas/src/index.js",
  "tools/openclinxr/evidence/faculty-review-gate.ts -> ../../../packages/openclinxr/ui-route-admin/src/scenario-review-gate-constants.js",
  "tools/openclinxr/evidence/fixture-surface-distinct.ts -> ../../../packages/openclinxr/asset-registry/src/environment-descriptors.js",
  "tools/openclinxr/evidence/foot-plant/bound-clip-foot-plant.ts -> ../../../../packages/openclinxr/asset-registry/src/approach-executor.js",
  "tools/openclinxr/evidence/foot-plant/bound-clip-foot-plant.ts -> ../../../../packages/openclinxr/asset-registry/src/bedside-approach-path.js",
  "tools/openclinxr/evidence/foot-plant/bound-clip-foot-plant.ts -> ../../../../packages/openclinxr/asset-registry/src/index.js",
  "tools/openclinxr/evidence/foot-plant/bound-clip-foot-track.ts -> ../../../../packages/openclinxr/asset-registry/src/approach-executor-mod.js",
  "tools/openclinxr/evidence/foot-plant/idle-standing-sway-foot-slide.ts -> ../../../../packages/openclinxr/xr-humanoid-animation/src/index.js",
  "tools/openclinxr/evidence/foot-plant/the-walk-clip-faces-the-same-way-it-travels.test.ts -> ../../../../packages/openclinxr/asset-registry/src/approach-executor.js",
  "tools/openclinxr/evidence/foot-plant/the-walk-clip-faces-the-same-way-it-travels.test.ts -> ../../../../packages/openclinxr/xr-humanoid-animation/src/case-owned-approach-runtime.js",
  "tools/openclinxr/evidence/foot-plant/the-walk-clip-plants-its-feet.test.ts -> ../../../../packages/openclinxr/asset-registry/src/approach-executor.js",
  "tools/openclinxr/evidence/foot-plant/the-walk-clip-plants-its-feet.test.ts -> ../../../../packages/openclinxr/asset-registry/src/bedside-approach-path.js",
  "tools/openclinxr/evidence/foot-plant/the-walk-clip-plants-its-feet.test.ts -> ../../../../packages/openclinxr/asset-registry/src/index.js",
  "tools/openclinxr/evidence/garment-palette-role-source.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/garment-selection-by-role.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/gaze-eye-bones-resolve-on-every-rail.test.ts -> ../../../packages/openclinxr/asset-registry/src/pose-bone-resolver.js",
  "tools/openclinxr/evidence/generator-sweep-harness.ts -> ../../../packages/openclinxr/asset-registry/src/environment-descriptors.js",
  "tools/openclinxr/evidence/generator-sweep-harness.ts -> ../../../packages/openclinxr/scenario-fixtures/src/index.js",
  "tools/openclinxr/evidence/humanoid-body-signature.ts -> ../../../packages/openclinxr/asset-registry/src/humanoid-body-mesh.js",
  "tools/openclinxr/evidence/humanoid-cast-path-resolution.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/humanoid-realism-gate.test.ts -> ../../../packages/openclinxr/scenario-fixtures/src/index.js",
  "tools/openclinxr/evidence/humanoid-source-side-by-side-cagematch.ts -> ../../../packages/openclinxr/arena/model-vetting/src/index.js",
  "tools/openclinxr/evidence/humanoid-vetting/see-through-pixels.ts -> ../../../../apps/arena/model-vetting-studio/src/candidate-capture-geometry.ts",
  "tools/openclinxr/evidence/humanoid-vision-score.ts -> ../../../packages/openclinxr/agent-loop/src/model-pricing.js",
  "tools/openclinxr/evidence/idle-arm-hang.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/inpatient-supine-staging.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/inpatient-supine-staging.ts -> ../../../packages/openclinxr/scenario-fixtures/src/index.js",
  "tools/openclinxr/evidence/isolated-foot-grounder/capture.ts -> ../../../../packages/openclinxr/asset-registry/src/case-frozen-scene-plans.js",
  "tools/openclinxr/evidence/isolated-foot-grounder/capture.ts -> ../../../../packages/openclinxr/asset-registry/src/runtime-bundles.js",
  "tools/openclinxr/evidence/issue-278-cast.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/issue-278-cast.ts -> ../../../packages/openclinxr/asset-registry/src/humanoid-body-mesh.js",
  "tools/openclinxr/evidence/issue-289-runtime-hide.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/issue-290-claim-region-extent.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/iwer-controller-input-probe-check.test.ts -> ../../../apps/arena/ui-xr-iwsdk-spike/src/sidecar-state.js",
  "tools/openclinxr/evidence/iwer-controller-input-probe-check.ts -> ../../../apps/arena/ui-xr-iwsdk-spike/src/sidecar-state.js",
  "tools/openclinxr/evidence/iwer-sidecar-emulation-evidence-check.test.ts -> ../../../packages/openclinxr/arena/iwsdk-spike/src/index.js",
  "tools/openclinxr/evidence/iwer-sidecar-emulation-evidence-check.ts -> ../../../packages/openclinxr/arena/iwsdk-spike/src/index.js",
  "tools/openclinxr/evidence/iwsdk-agent-tooling-evidence-check.test.ts -> ../../../packages/openclinxr/arena/iwsdk-spike/src/index.js",
  "tools/openclinxr/evidence/iwsdk-agent-tooling-evidence-check.ts -> ../../../packages/openclinxr/arena/iwsdk-spike/src/index.js",
  "tools/openclinxr/evidence/iwsdk-compatibility-evidence-check.ts -> ../../../packages/openclinxr/arena/iwsdk-spike/src/index.js",
  "tools/openclinxr/evidence/iwsdk-evidence-contract-check.test.ts -> ../../../packages/openclinxr/arena/iwsdk-spike/src/index.js",
  "tools/openclinxr/evidence/iwsdk-evidence-contract-check.ts -> ../../../packages/openclinxr/arena/iwsdk-spike/src/index.js",
  "tools/openclinxr/evidence/iwsdk-managed-browser-evidence-check.ts -> ../../../packages/openclinxr/arena/iwsdk-spike/src/index.js",
  "tools/openclinxr/evidence/iwsdk-mcp-inventory-evidence.test.ts -> ../../../packages/openclinxr/arena/iwsdk-spike/src/index.js",
  "tools/openclinxr/evidence/iwsdk-mcp-inventory-evidence.ts -> ../../../packages/openclinxr/arena/iwsdk-spike/src/index.js",
  "tools/openclinxr/evidence/iwsdk-metadata-drift-evidence-check.ts -> ../../../packages/openclinxr/arena/iwsdk-spike/src/index.js",
  "tools/openclinxr/evidence/iwsdk-operator-steering-blockers.test.ts -> ../../../packages/openclinxr/arena/iwsdk-spike/src/index.js",
  "tools/openclinxr/evidence/iwsdk-preinstall-check.ts -> ../../../packages/openclinxr/arena/iwsdk-spike/src/index.js",
  "tools/openclinxr/evidence/iwsdk-sidecar-metrics-check.ts -> ../../../packages/openclinxr/arena/iwsdk-spike/src/index.js",
  "tools/openclinxr/evidence/iwsdk-ui-xr-parity.test.ts -> ../../../packages/openclinxr/arena/iwsdk-spike/src/index.js",
  "tools/openclinxr/evidence/iwsdk-workspace-posture-check.ts -> ../../../packages/openclinxr/arena/iwsdk-spike/src/index.js",
  "tools/openclinxr/evidence/learners-see-mpfb-not-anny.test.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/learners-see-mpfb-not-anny.test.ts -> ../../../packages/openclinxr/asset-registry/src/cast-asset-constants.js",
  "tools/openclinxr/evidence/library-figure-finish-parity.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/library-humanoid-staged.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/licence/selected-scene-asset-lineage.ts -> ../../../../packages/openclinxr/asset-registry/src/runtime-bundles-entry.js",
  "tools/openclinxr/evidence/licence/the-replacement-walk-preserves-approach-behaviour.ts -> ../../../../packages/openclinxr/asset-registry/src/approach-executor-mod.js",
  "tools/openclinxr/evidence/licence/the-replacement-walk-preserves-approach-behaviour.ts -> ../../../../packages/openclinxr/asset-registry/src/approach-executor.js",
  "tools/openclinxr/evidence/live-scenario-actor-cast.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/local-model-quality-benchmark.ts -> ../../../packages/openclinxr/model-gateway/src/index.js",
  "tools/openclinxr/evidence/local-voice-live-dialog-benchmark.ts -> ../../../packages/openclinxr/voice-gateway/src/index.js",
  "tools/openclinxr/evidence/materialize-guard-withdraw-clip.ts -> ../../../packages/openclinxr/asset-registry/src/pose-bone-resolver.js",
  "tools/openclinxr/evidence/medical-equipment-artifacts.ts -> ../../../packages/openclinxr/asset-registry/src/runtime-bundles.js",
  "tools/openclinxr/evidence/model-vetting-capture-manifest.ts -> ../../../packages/openclinxr/arena/model-vetting/src/index.js",
  "tools/openclinxr/evidence/model-vetting-glb-grade-capture.ts -> ../../../packages/openclinxr/arena/model-vetting/src/index.js",
  "tools/openclinxr/evidence/model-vetting-local-candidate-mirror.test.ts -> ../../../packages/openclinxr/arena/model-vetting/src/index.js",
  "tools/openclinxr/evidence/model-vetting-local-candidate-mirror.ts -> ../../../packages/openclinxr/arena/model-vetting/src/index.js",
  "tools/openclinxr/evidence/model-vetting-report.test.ts -> ../../../packages/openclinxr/arena/model-vetting/src/index.js",
  "tools/openclinxr/evidence/model-vetting-report.ts -> ../../../packages/openclinxr/arena/model-vetting/src/index.js",
  "tools/openclinxr/evidence/model-vetting-runtime-mapping-evidence.ts -> ../../../packages/openclinxr/arena/model-vetting/src/index.js",
  "tools/openclinxr/evidence/model-vetting-turntable-capture.ts -> ../../../packages/openclinxr/arena/model-vetting/src/index.js",
  "tools/openclinxr/evidence/mpfb-actors-can-speak.test.ts -> ../../../packages/openclinxr/asset-registry/src/morph-target-resolver.ts",
  "tools/openclinxr/evidence/mpfb-visemes-measure.ts -> ../../../packages/openclinxr/asset-registry/src/morph-target-resolver.ts",
  "tools/openclinxr/evidence/multi-station-exam-assembly.ts -> ../../../packages/openclinxr/exam-assembly/src/index.js",
  "tools/openclinxr/evidence/multi-station-exam-assembly.ts -> ../../../packages/openclinxr/rest/src/exam-assembly-pool.js",
  "tools/openclinxr/evidence/multi-station-exam-assembly.ts -> ../../../packages/openclinxr/scenario-fixtures/src/index.js",
  "tools/openclinxr/evidence/natural-blink-emotion/speech-emotion-video/bake-speech.ts -> ../../../../../packages/openclinxr/factory-stations/src/lip_sync/fixture-wav.ts",
  "tools/openclinxr/evidence/natural-blink-emotion/speech-emotion-video/bake-speech.ts -> ../../../../../packages/openclinxr/factory-stations/src/lip_sync/run.ts",
  "tools/openclinxr/evidence/natural-blink-emotion/speech-emotion-video/bake-speech.ts -> ../../../../../packages/openclinxr/xr-dialogue/src/viseme-utterance-hash.ts",
  "tools/openclinxr/evidence/natural-blink-emotion/speech-emotion-video/page.mjs -> ../../../../../packages/openclinxr/xr-dialogue/src/index.ts",
  "tools/openclinxr/evidence/natural-blink-emotion/speech-emotion-video/page.mjs -> ../../../../../packages/openclinxr/xr-humanoid-animation/src/index.ts",
  "tools/openclinxr/evidence/natural-blink-emotion/speech-emotion-video/page.mjs -> ../../../../../packages/openclinxr/xr-pose/src/clinical-idle-posture.ts",
  "tools/openclinxr/evidence/no-actor-can-be-cast-onto-the-anny-rail.test.ts -> ../../../packages/openclinxr/asset-registry/src/cast-asset-constants.js",
  "tools/openclinxr/evidence/no-actor-can-be-cast-onto-the-anny-rail.test.ts -> ../../../packages/openclinxr/scenario-fixtures/src/index.js",
  "tools/openclinxr/evidence/no-learner-meets-an-anny-patient.test.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/no-learner-meets-an-anny-patient.test.ts -> ../../../packages/openclinxr/asset-registry/src/cast-asset-constants.js",
  "tools/openclinxr/evidence/no-shipped-actor-wears-the-colour-of-their-skin.test.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.ts",
  "tools/openclinxr/evidence/no-shipped-humanoid-is-anny-and-every-face-has-units.test.ts -> ../../../packages/openclinxr/scenario-fixtures/src/scenario-bank.js",
  "tools/openclinxr/evidence/patient-attire-by-care-setting.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/patient-opening-utterance.ts -> ../../../packages/openclinxr/scenario-fixtures/src/scenario-bank.js",
  "tools/openclinxr/evidence/patient-opening-utterance.ts -> ../../../packages/openclinxr/xr-dialogue/src/initial-dialogue-text.js",
  "tools/openclinxr/evidence/per-station-actor-integrity.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/physician-resolves-to-own-mpfb-body.test.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/physician-resolves-to-own-mpfb-body.test.ts -> ../../../packages/openclinxr/asset-registry/src/cast-asset-constants.js",
  "tools/openclinxr/evidence/physics-placement-cagematch.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/physics-placement-cagematch.ts -> ../../../packages/openclinxr/asset-registry/src/environment-descriptors.js",
  "tools/openclinxr/evidence/physics-placement-cagematch.ts -> ../../../packages/openclinxr/asset-registry/src/runtime-bundles.js",
  "tools/openclinxr/evidence/pipeline-candidate-index.test.ts -> ../../../packages/openclinxr/arena/model-vetting/src/pipeline-candidate.js",
  "tools/openclinxr/evidence/pipeline-candidate-index.ts -> ../../../packages/openclinxr/arena/model-vetting/src/pipeline-candidate.js",
  "tools/openclinxr/evidence/promote-candidate.test.ts -> ../../../packages/openclinxr/arena/model-vetting/src/pipeline-candidate.js",
  "tools/openclinxr/evidence/promote-candidate.ts -> ../../../packages/openclinxr/arena/model-vetting/src/pipeline-candidate.js",
  "tools/openclinxr/evidence/promotion-path-reaches-learner.ts -> ../../../apps/api/src/index.js",
  "tools/openclinxr/evidence/promotion-path-reaches-learner.ts -> ../../../packages/openclinxr/graphql/src/documents.js",
  "tools/openclinxr/evidence/promotion-path-reaches-learner.ts -> ../../../packages/openclinxr/rest/src/api-types.js",
  "tools/openclinxr/evidence/promotion-path-reaches-learner.ts -> ../../../packages/openclinxr/scenario-fixtures/src/index.js",
  "tools/openclinxr/evidence/promotion-path-reaches-learner.ts -> ../../../packages/openclinxr/shared-schemas/src/index.js",
  "tools/openclinxr/evidence/realtime-voice-transport-spike.ts -> ../../../apps/api/src/index.js",
  "tools/openclinxr/evidence/realtime-voice-transport-spike.ts -> ../../../apps/arena/mock-realtime-voice-server/src/index.js",
  "tools/openclinxr/evidence/realtime-voice-transport-spike.ts -> ../../../packages/openclinxr/voice-gateway/src/index.js",
  "tools/openclinxr/evidence/realvisxl-direct-texture-cagematch.ts -> ../../../packages/openclinxr/arena/model-vetting/src/index.js",
  "tools/openclinxr/evidence/review-glb-optimization-visual-cagematch.ts -> ../../../packages/openclinxr/arena/model-vetting/src/index.js",
  "tools/openclinxr/evidence/say-fixture-rate/the-say-fixture-rate-follows-prosody-speed.test.ts -> ../../../../packages/openclinxr/factory-stations/src/lip_sync/fixture-wav.ts",
  "tools/openclinxr/evidence/scenario-actor-casting.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/scenario-derived-conversation-surface.ts -> ../../../packages/openclinxr/scenario-fixtures/src/scenario-bank.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-00/build-report.ts -> ../../../../../../packages/openclinxr/asset-registry/src/approach-executor.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-00/measurement-rubric.ts -> ../../../../../../packages/openclinxr/asset-registry/src/approach-executor.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-00/measurement-rubric.ts -> ../../../../../../packages/openclinxr/asset-registry/src/bedside-clearance.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-00/rubric-controls.ts -> ../../../../../../packages/openclinxr/asset-registry/src/approach-executor.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-00/rubric-controls.ts -> ../../../../../../packages/openclinxr/asset-registry/src/bedside-approach-path.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-00/rubric-controls.ts -> ../../../../../../packages/openclinxr/asset-registry/src/index.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-01s/the-selected-scenario-reaches-the-route-through-the-client.test.ts -> ../../../../../../apps/api/src/index.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-01s/the-selected-scenario-reaches-the-route-through-the-client.test.ts -> ../../../../../../packages/openclinxr/asset-registry/src/runtime-bundles.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-01s/the-selected-scenario-reaches-the-route-through-the-client.test.ts -> ../../../../../../packages/openclinxr/rest/src/index.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-01s/the-selected-scenario-reaches-the-route-through-the-client.test.ts -> ../../../../../../packages/openclinxr/scenario-fixtures/src/index.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-01s/the-selected-scenario-reaches-the-route-through-the-client.test.ts -> ../../../../../../packages/openclinxr/shared-schemas/src/index.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-01s/the-selected-scenario-reaches-the-route-through-the-client.test.ts -> ../../../../../../packages/openclinxr/xr-station/src/index.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-05/runtime-approach-measurement.ts -> ../../../../../../packages/openclinxr/asset-registry/src/actor-posture.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-05/runtime-approach-measurement.ts -> ../../../../../../packages/openclinxr/asset-registry/src/approach-executor.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-05/runtime-approach-measurement.ts -> ../../../../../../packages/openclinxr/asset-registry/src/case-approach-intent.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-05/runtime-approach-measurement.ts -> ../../../../../../packages/openclinxr/asset-registry/src/index.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-05/runtime-approach-measurement.ts -> ../../../../../../packages/openclinxr/asset-registry/src/runtime-bundles-entry.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-05/runtime-approach-measurement.ts -> ../../../../../../packages/openclinxr/asset-registry/src/runtime-bundles.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-05/runtime-approach-measurement.ts -> ../../../../../../packages/openclinxr/xr-humanoid-animation/src/case-owned-approach-runtime.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-05/runtime-approach-measurement.ts -> ../../../../../../packages/openclinxr/xr-humanoid-animation/src/mounted-approach-geometry.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-05/runtime-approach-measurement.ts -> ../../../../../../packages/openclinxr/xr-pose/src/actor-floor-composition.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-05/runtime-approach-measurement.ts -> ../../../../../../packages/openclinxr/xr-runtime-state/src/supported-actor-placement.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-05/runtime-approach-measurement.ts -> ../../../../../../packages/openclinxr/xr-scene/src/encounter-actor-framing.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-05/runtime-approach-measurement.ts -> ../../../../../../packages/openclinxr/xr-station-room/src/mounted-support-observation.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-05/runtime-approach-measurement.ts -> ../../../../../../packages/openclinxr/xr-station/src/index.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-05/ui-xr-bedside-approach-capture.ts -> ../../../../../../packages/openclinxr/asset-registry/src/runtime-bundles.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-06/baseline-replay-probe.ts -> ../../../../../../packages/openclinxr/asset-registry/src/actor-posture.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-06/baseline-replay-probe.ts -> ../../../../../../packages/openclinxr/asset-registry/src/case-approach-intent.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-06/baseline-replay-probe.ts -> ../../../../../../packages/openclinxr/asset-registry/src/runtime-bundles-entry.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-06/baseline-replay-probe.ts -> ../../../../../../packages/openclinxr/xr-humanoid-animation/src/mounted-approach-geometry.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-06/baseline-replay-probe.ts -> ../../../../../../packages/openclinxr/xr-runtime-state/src/bedside-approach-execution.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-06/baseline-replay-probe.ts -> ../../../../../../packages/openclinxr/xr-station/src/index.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-06/freeze-case-scene-plan.ts -> ../../../../../../packages/openclinxr/asset-registry/src/case-approach-intent.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-06/freeze-case-scene-plan.ts -> ../../../../../../packages/openclinxr/asset-registry/src/runtime-bundles-entry.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-06/freeze-case-scene-plan.ts -> ../../../../../../packages/openclinxr/asset-registry/src/scene-plan-freeze.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-06/freeze-case-scene-plan.ts -> ../../../../../../packages/openclinxr/session-state/src/accepted-scene-plan.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-06/freeze-case-scene-plan.ts -> ../../../../../../packages/openclinxr/xr-humanoid-animation/src/mounted-approach-geometry.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-06/freeze-case-scene-plan.ts -> ../../../../../../packages/openclinxr/xr-scene/src/encounter-actor-framing.js",
  "tools/openclinxr/evidence/scene-closure/proofs/sc-06/freeze-case-scene-plan.ts -> ../../../../../../packages/openclinxr/xr-station/src/index.js",
  "tools/openclinxr/evidence/scene-closure/the-measurement-rubric-rejects-broken-controls.test.ts -> ../../../../packages/openclinxr/asset-registry/src/approach-executor.js",
  "tools/openclinxr/evidence/scene-closure/the-measurement-rubric-rejects-broken-controls.test.ts -> ../../../../packages/openclinxr/asset-registry/src/bedside-approach-path.js",
  "tools/openclinxr/evidence/scene-closure/the-measurement-rubric-rejects-broken-controls.test.ts -> ../../../../packages/openclinxr/asset-registry/src/bedside-clearance.js",
  "tools/openclinxr/evidence/scene-closure/the-measurement-rubric-rejects-broken-controls.test.ts -> ../../../../packages/openclinxr/asset-registry/src/index.js",
  "tools/openclinxr/evidence/seated-actor-seat-placement.ts -> ../../../packages/openclinxr/asset-registry/src/environment-descriptors.js",
  "tools/openclinxr/evidence/seated-actor-seat-placement.ts -> ../../../packages/openclinxr/asset-registry/src/environment-zone-templates.js",
  "tools/openclinxr/evidence/seated-hands-rest.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/seated-posture-wiring.ts -> ../../../packages/openclinxr/asset-registry/src/actor-posture-mod.js",
  "tools/openclinxr/evidence/seated-posture-wiring.ts -> ../../../packages/openclinxr/asset-registry/src/runtime-bundles.js",
  "tools/openclinxr/evidence/settled-execution-observation/the-settled-branch-execution-is-observed.test.ts -> ../../../../packages/openclinxr/xr-humanoid-animation/src/case-owned-approach-runtime-mod.js",
  "tools/openclinxr/evidence/settled-execution-observation/the-settled-branch-execution-is-observed.test.ts -> ../../../../packages/openclinxr/xr-humanoid-animation/src/stance-lock-mod.js",
  "tools/openclinxr/evidence/settled-posture-diagnosis/the-settled-correction-execution-is-measured.test.ts -> ../../../../packages/openclinxr/xr-humanoid-animation/src/stance-lock-mod.js",
  "tools/openclinxr/evidence/shared-asset-library-cache-evidence.ts -> ../../../packages/openclinxr/capability-gateway/src/asset-generation-jobs.js",
  "tools/openclinxr/evidence/shipped-head-of-bed-incline.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/shipped-head-of-bed-incline.ts -> ../../../packages/openclinxr/scenario-fixtures/src/index.js",
  "tools/openclinxr/evidence/station-chart-honesty.ts -> ../../../packages/openclinxr/scenario-fixtures/src/scenario-bank.js",
  "tools/openclinxr/evidence/station-fixture-vocabulary.test.ts -> ../../../packages/openclinxr/asset-registry/src/environment-descriptors.js",
  "tools/openclinxr/evidence/station-fixture-vocabulary.ts -> ../../../packages/openclinxr/asset-registry/src/environment-descriptors.js",
  "tools/openclinxr/evidence/station-room-not-empty.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/station-vitals-honesty.ts -> ../../../packages/openclinxr/scenario-fixtures/src/scenario-bank.js",
  "tools/openclinxr/evidence/supine-flex/the-supine-foot-flex-does-not-accumulate.test.ts -> ../../../../packages/openclinxr/xr-pose/src/hob-contact-metrics.js",
  "tools/openclinxr/evidence/supine-flex/the-supine-foot-flex-does-not-accumulate.test.ts -> ../../../../packages/openclinxr/xr-pose/src/hob-extremity-flex.js",
  "tools/openclinxr/evidence/supine-flex/the-supine-foot-flex-does-not-accumulate.test.ts -> ../../../../packages/openclinxr/xr-pose/src/supine-deck-plant.js",
  "tools/openclinxr/evidence/supine-patient-on-deck.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/the-adapter-extracts-a-reply-from-a-reasoning-model.test.ts -> ../../../packages/openclinxr/model-gateway/src/index.js",
  "tools/openclinxr/evidence/the-api-readiness-surface-weighs-shipped-geometry.test.ts -> ../../../packages/openclinxr/asset-registry/src/index.js",
  "tools/openclinxr/evidence/the-api-readiness-surface-weighs-shipped-geometry.test.ts -> ../../../packages/openclinxr/rest/src/api-route-support.js",
  "tools/openclinxr/evidence/the-api-readiness-surface-weighs-shipped-geometry.test.ts -> ../../../packages/openclinxr/scenario-fixtures/src/index.js",
  "tools/openclinxr/evidence/the-arm-chain-is-the-real-rigs-arm-chain.test.ts -> ../../../packages/openclinxr/motion-compiler/src/ik/solve-chain.js",
  "tools/openclinxr/evidence/the-baked-visemes-are-reachable.test.ts -> ../../../packages/openclinxr/asset-registry/src/morph-target-resolver.js",
  "tools/openclinxr/evidence/the-baked-visemes-are-reachable.test.ts -> ../../../packages/openclinxr/xr-dialogue/src/viseme-runtime-wire.js",
  "tools/openclinxr/evidence/the-blueprint-voice-loop-routes-the-transcript-it-received.test.ts -> ../../../packages/openclinxr/exam-assembly/src/index.js",
  "tools/openclinxr/evidence/the-blueprint-voice-loop-routes-the-transcript-it-received.test.ts -> ../../../packages/openclinxr/scenario-fixtures/src/index.js",
  "tools/openclinxr/evidence/the-blueprint-voice-loop-routes-the-transcript-it-received.test.ts -> ../../../packages/openclinxr/session-state/src/internal.js",
  "tools/openclinxr/evidence/the-blueprint-voice-loop-routes-the-transcript-it-received.test.ts -> ../../../packages/openclinxr/voice-gateway/src/adapters.js",
  "tools/openclinxr/evidence/the-blueprint-voice-loop-routes-the-transcript-it-received.test.ts -> ../../../packages/openclinxr/voice-gateway/src/index.js",
  "tools/openclinxr/evidence/the-capture-selects-the-subjects-motion-clip.test.ts -> ../../../apps/arena/model-vetting-studio/src/candidate-capture.js",
  "tools/openclinxr/evidence/the-dark-station-has-a-named-mechanism.test.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.ts",
  "tools/openclinxr/evidence/the-gateway-falls-over-when-a-provider-fails.test.ts -> ../../../packages/openclinxr/model-gateway/src/index.js",
  "tools/openclinxr/evidence/the-loaded-mesh-matches-the-cast.test.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/the-loaded-mesh-matches-the-cast.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/the-local-rung-does-not-leak-reasoning-to-a-learner.test.ts -> ../../../packages/openclinxr/model-gateway/src/index.js",
  "tools/openclinxr/evidence/the-lookup-does-not-invent-a-persons-sex.test.ts -> ../../../packages/openclinxr/scenario-fixtures/src/descriptor-phenotype-lookup.js",
  "tools/openclinxr/evidence/the-lookup-does-not-invent-a-persons-sex.test.ts -> ../../../packages/openclinxr/scenario-fixtures/src/index.js",
  "tools/openclinxr/evidence/the-measured-geometry-artifact-knows-when-it-is-stale.test.ts -> ../../../packages/openclinxr/asset-registry/src/measured-station-geometry-freshness.js",
  "tools/openclinxr/evidence/the-mouth-capture-artifact-answers-for-the-current-tree.test.ts -> ../../../packages/openclinxr/asset-registry/src/measured-station-geometry-freshness.js",
  "tools/openclinxr/evidence/the-non-gowned-casts-are-all-mpfb.test.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/the-parent-drives-a-real-viseme-at-runtime.test.ts -> ../../../packages/openclinxr/asset-registry/src/morph-target-resolver.js",
  "tools/openclinxr/evidence/the-readiness-verdict-reads-measured-geometry.test.ts -> ../../../packages/openclinxr/asset-registry/src/index.js",
  "tools/openclinxr/evidence/the-runtime-reaches-a-real-model-not-the-mock.test.ts -> ../../../packages/openclinxr/model-gateway/src/index.js",
  "tools/openclinxr/evidence/the-runtime-reaches-the-baked-viseme-targets.test.ts -> ../../../packages/openclinxr/asset-registry/src/morph-target-resolver.js",
  "tools/openclinxr/evidence/the-seated-parent-is-seated-and-her-clip-plays.test.ts -> ../../../packages/openclinxr/asset-registry/src/actor-posture.js",
  "tools/openclinxr/evidence/the-size-gate-judges-only-what-is-being-committed.test.ts -> ../../../packages/openclinxr-verification/architecture-rules/src/checks/file-size-budgets.ts",
  "tools/openclinxr/evidence/the-spawn-prompt-states-the-planted-contract-convention.test.ts -> ../../../packages/openclinxr/agent-loop/src/grok-repo-agent-spawn.ts",
  "tools/openclinxr/evidence/the-spawn-prompt-states-the-planted-contract-convention.test.ts -> ../../../packages/openclinxr/agent-loop/src/role-harness-policy.ts",
  "tools/openclinxr/evidence/the-spawn-prompt-states-the-planted-contract-convention.test.ts -> ../../../packages/openclinxr/agent-loop/src/worker-directives.ts",
  "tools/openclinxr/evidence/the-street-patients-are-cast-on-the-mpfb-rail.test.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/evidence/the-supine-map-binds-the-rig-it-poses.test.ts -> ../../../packages/openclinxr/asset-registry/src/pose-bone-resolver.js",
  "tools/openclinxr/evidence/the-viseme-driver-opens-the-jaw.test.ts -> ../../../packages/openclinxr/xr-dialogue/src/viseme-timeline-drive.js",
  "tools/openclinxr/evidence/ui-xr-parent-nurse-sleeve-deform-capture.ts -> ../../../packages/openclinxr/asset-registry/src/humanoid-asset-path.js",
  "tools/openclinxr/evidence/ui-xr-viseme-drive-capture.ts -> ../../../packages/openclinxr/model-gateway/src/index.js",
  "tools/openclinxr/evidence/ui-xr-viseme-drive-capture.ts -> ../../../packages/openclinxr/scenario-fixtures/src/index.js",
  "tools/openclinxr/evidence/ui-xr-viseme-drive-capture.ts -> ../../../packages/openclinxr/scenario-runtime/src/index.js",
  "tools/openclinxr/evidence/ui-xr-viseme-drive-capture.ts -> ../../../packages/openclinxr/shared-schemas/src/index.js",
  "tools/openclinxr/evidence/viseme-timing-weights-phonemes-by-duration.test.ts -> ../../../packages/openclinxr/xr-dialogue/src/dialogue-visemes.js",
  "tools/openclinxr/evidence/viseme-timing-weights-phonemes-by-duration.test.ts -> ../../../packages/openclinxr/xr-dialogue/src/viseme-runtime-wire.js",
  "tools/openclinxr/evidence/visual-qa-evidence-check.test.ts -> ../../../packages/openclinxr/capability-gateway/src/index.js",
  "tools/openclinxr/evidence/visual-qa-evidence-check.ts -> ../../../packages/openclinxr/capability-gateway/src/asset-generation-jobs.js",
  "tools/openclinxr/evidence/visual-qa-evidence-check.ts -> ../../../packages/openclinxr/capability-gateway/src/index.js",
  "tools/openclinxr/factory/actor-audio-integration/ordinary-turn-and-cue-authority.test.ts -> ../../../../apps/ui-xr/src/ordinary-actor-turn-speech.js",
  "tools/openclinxr/factory/actor-audio-integration/ordinary-turn-and-cue-authority.test.ts -> ../../../../apps/ui-xr/src/prepared-actor-audio.js",
  "tools/openclinxr/factory/actor-audio-package-integration/ordinary-host-adapter.test.ts -> ../../../../packages/openclinxr/xr-dialogue/src/actor-audio-runtime.js",
  "tools/openclinxr/factory/actor-audio-package-integration/public-admission.test.ts -> ../../../../packages/openclinxr-verification/architecture-rules/src/checks/public-surface/apply-map.js",
  "tools/openclinxr/factory/actor-audio-package-integration/public-admission.test.ts -> ../../../../packages/openclinxr-verification/architecture-rules/src/checks/public-surface/gates.js",
  "tools/openclinxr/factory/actor-audio-package-integration/public-admission.test.ts -> ../../../../packages/openclinxr-verification/architecture-rules/src/checks/public-surface/resolve.js",
  "tools/openclinxr/factory/actor-audio-package-integration/runtime-lifecycle.test.ts -> ../../../../packages/openclinxr/xr-dialogue/src/actor-audio-runtime.js",
  "tools/openclinxr/factory/actor-audio-package-integration/typed-prepared-failure-cleanup.test.mjs -> ../../../../packages/openclinxr/xr-dialogue/src/actor-audio-runtime.js",
  "tools/openclinxr/factory/actor-audio-package-subpath-integration/public-subpath.test.ts -> ../../../../packages/openclinxr-verification/architecture-rules/src/checks/export-surface-budgets.js",
  "tools/openclinxr/factory/actor-audio-package-subpath-integration/public-subpath.test.ts -> ../../../../packages/openclinxr-verification/architecture-rules/src/checks/public-surface/resolve.js",
  "tools/openclinxr/factory/cagematch-report-pages.test.ts -> ../../../packages/openclinxr/arena/model-vetting/src/cagematch-report.js",
  "tools/openclinxr/factory/cagematch-report-pages.ts -> ../../../packages/openclinxr/arena/model-vetting/src/cagematch-report.js",
  "tools/openclinxr/factory/encounter-asset-generation-queue.test.ts -> ../../../packages/openclinxr/capability-gateway/src/index.js",
  "tools/openclinxr/factory/encounter-asset-generation-queue.test.ts -> ../../../packages/openclinxr/scenario-fixtures/src/index.js",
  "tools/openclinxr/factory/encounter-asset-generation-queue.ts -> ../../../packages/openclinxr/asset-registry/src/index.js",
  "tools/openclinxr/factory/encounter-asset-generation-queue.ts -> ../../../packages/openclinxr/asset-registry/src/runtime-bundles.js",
  "tools/openclinxr/factory/encounter-asset-generation-queue.ts -> ../../../packages/openclinxr/capability-gateway/src/index.js",
  "tools/openclinxr/factory/encounter-asset-generation-queue.ts -> ../../../packages/openclinxr/scenario-fixtures/src/scenario-bank-maturity.js",
  "tools/openclinxr/factory/encounter-asset-generation-queue.ts -> ../../../packages/openclinxr/scenario-fixtures/src/scenario-bank.js",
  "tools/openclinxr/factory/encounter-asset-generation-queue.ts -> ../../../packages/openclinxr/shared-schemas/src/index.js",
  "tools/openclinxr/factory/encounter-asset-generation-worker.ts -> ../../../packages/openclinxr/capability-gateway/src/asset-generation-jobs.js",
  "tools/openclinxr/factory/encounter-asset-generation-worker.ts -> ../../../packages/openclinxr/capability-gateway/src/azure-storage-queue-client.js",
  "tools/openclinxr/factory/encounter-asset-generation-worker.ts -> ../../../packages/openclinxr/capability-gateway/src/index.js",
  "tools/openclinxr/factory/encounter-asset-generation-worker.ts -> ../../../packages/openclinxr/data-sources-mongoose-models/src/index.js",
  "tools/openclinxr/factory/encounter-local-factory-operation-manifest.ts -> ../../../packages/openclinxr/asset-registry/src/runtime-bundles.js",
  "tools/openclinxr/factory/encounter-local-factory-operation-manifest.ts -> ../../../packages/openclinxr/scenario-fixtures/src/index.js",
  "tools/openclinxr/factory/encounter-local-launch-selection.test.ts -> ../../../packages/openclinxr/asset-registry/src/runtime-bundles-entry.js",
  "tools/openclinxr/factory/encounter-materialization-evidence.ts -> ../../../packages/openclinxr/scenario-fixtures/src/scenario-bank.js",
  "tools/openclinxr/factory/encounter-publication-payloads.test.ts -> ../../../packages/openclinxr/asset-registry/src/runtime-bundles-entry.js",
  "tools/openclinxr/factory/encounter-publication-payloads.test.ts -> ../../../packages/openclinxr/scenario-fixtures/src/index.js",
  "tools/openclinxr/factory/encounter-publication-payloads.ts -> ../../../packages/openclinxr/asset-registry/src/runtime-bundles.js",
  "tools/openclinxr/factory/encounter-publication-payloads.ts -> ../../../packages/openclinxr/capability-gateway/src/asset-generation-jobs.js",
  "tools/openclinxr/factory/encounter-publication-payloads.ts -> ../../../packages/openclinxr/capability-gateway/src/index.js",
  "tools/openclinxr/factory/encounter-publication-payloads.ts -> ../../../packages/openclinxr/shared-schemas/src/index.js",
  "tools/openclinxr/factory/encounter-runtime-selection-review-packet.ts -> ../../../packages/openclinxr/data-mongodb/src/index.js",
  "tools/openclinxr/factory/encounter-runtime-selection-review-packet.ts -> ../../../packages/openclinxr/scenario-fixtures/src/pediatric-asthma.js",
  "tools/openclinxr/factory/equipment-lane/equipment-catalog-cli.ts -> ../../../../packages/openclinxr/data-mongodb/src/index.js",
  "tools/openclinxr/factory/equipment-lane/inventory.ts -> ../../../../packages/openclinxr/scenario-fixtures/src/scenario-bank.ts",
  "tools/openclinxr/factory/generated-ed-station-runtime-bundle.ts -> ../../../packages/openclinxr/asset-registry/src/asset-writer-mod.js",
  "tools/openclinxr/factory/generated-ed-station-runtime-bundle.ts -> ../../../packages/openclinxr/asset-registry/src/object-store-mod.js",
  "tools/openclinxr/factory/generated-ed-station-runtime-bundle.ts -> ../../../packages/openclinxr/asset-registry/src/runtime-asset-review.js",
  "tools/openclinxr/factory/generated-ed-station-runtime-bundle.ts -> ../../../packages/openclinxr/asset-registry/src/runtime-bundles.js",
  "tools/openclinxr/factory/generated-ed-station-runtime-bundle.ts -> ../../../packages/openclinxr/scenario-fixtures/src/index.js",
  "tools/openclinxr/factory/generated-human-rigging-artifacts.ts -> ../../../packages/openclinxr/asset-registry/src/runtime-bundles.js",
  "tools/openclinxr/factory/generated-physics-config-artifacts.ts -> ../../../packages/openclinxr/arena/physics-touch-contract/src/factory/habitus-tables.js",
  "tools/openclinxr/factory/generated-physics-config-artifacts.ts -> ../../../packages/openclinxr/arena/physics-touch-contract/src/factory/physics-config-v1.js",
  "tools/openclinxr/factory/publish-generated-learner-runtime-bundle.test.ts -> ../../../packages/openclinxr/asset-registry/src/runtime-bundles-entry.js",
  "tools/openclinxr/factory/publish-generated-learner-runtime-bundle.ts -> ../../../packages/openclinxr/asset-registry/src/runtime-bundles-entry.js",
  "tools/openclinxr/factory/scene-closure-case-source.ts -> ../../../packages/openclinxr/shared-schemas/src/index.js",
  "tools/openclinxr/factory/scene-generation-review-decision-export.ts -> ../../../packages/openclinxr/asset-registry/src/runtime-asset-review.js",
  "tools/openclinxr/factory/the-placement-node-carries-the-authored-offset.test.ts -> ../../../packages/openclinxr/asset-registry/src/actor-placement.js",
  "tools/openclinxr/factory/the-placement-node-carries-the-authored-offset.test.ts -> ../../../packages/openclinxr/asset-registry/src/runtime-bundles.js",
  "tools/openclinxr/factory/the-placement-node-carries-the-authored-offset.test.ts -> ../../../packages/openclinxr/scenario-fixtures/src/index.js",
  "tools/openclinxr/measure-station-geometry.ts -> ../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/openclaw/board-brief.ts -> ../../../packages/openclinxr/agent-loop/src/done-when-rules.js",
  "tools/openclinxr/openclaw/contract-verify-cli.ts -> ../../../packages/openclinxr/agent-loop/src/done-when-rules.js",
  "tools/openclinxr/openclaw/contract-verify-cli.ts -> ../../../packages/openclinxr/agent-loop/src/slice-team.js",
  "tools/openclinxr/openclaw/dispatch-worker.ts -> ../../../packages/openclinxr/agent-loop/src/done-when-rules.js",
  "tools/openclinxr/openclaw/dispatch-worker.ts -> ../../../packages/openclinxr/agent-loop/src/grok-repo-agent-spawn.js",
  "tools/openclinxr/openclaw/dispatch-worker.ts -> ../../../packages/openclinxr/agent-loop/src/role-harness-policy.js",
  "tools/openclinxr/openclaw/dispatch-worker.ts -> ../../../packages/openclinxr/agent-loop/src/slice-team.js",
  "tools/openclinxr/openclaw/every-published-humanoid-is-cast-or-declared.test.ts -> ../../../packages/openclinxr/asset-registry/src/actor-casting.js",
  "tools/openclinxr/openclaw/grok-agent-cli.ts -> ../../../packages/openclinxr/agent-loop/src/grok-repo-agent-spawn.js",
  "tools/openclinxr/openclaw/grok-agent-cli.ts -> ../../../packages/openclinxr/agent-loop/src/slice-team.js",
  "tools/openclinxr/openclaw/grok-tier-cli.test.ts -> ../../../packages/openclinxr/agent-loop/src/grok-repo-agent-spawn.js",
  "tools/openclinxr/openclaw/grok-tier-cli.test.ts -> ../../../packages/openclinxr/agent-loop/src/grok-tier-routing.js",
  "tools/openclinxr/openclaw/grok-tier-cli.test.ts -> ../../../packages/openclinxr/agent-loop/src/role-harness-policy.js",
  "tools/openclinxr/openclaw/grok-tier-cli.ts -> ../../../packages/openclinxr/agent-loop/src/grok-tier-routing.js",
  "tools/openclinxr/openclaw/grok-tier-cli.ts -> ../../../packages/openclinxr/agent-loop/src/grok-token-introspection.js",
  "tools/openclinxr/openclaw/grok-tier-cli.ts -> ../../../packages/openclinxr/agent-loop/src/task-cost-rollup.js",
  "tools/openclinxr/openclaw/grok-token-io.ts -> ../../../packages/openclinxr/agent-loop/src/grok-tier-routing.js",
  "tools/openclinxr/openclaw/grok-token-io.ts -> ../../../packages/openclinxr/agent-loop/src/grok-token-introspection.js",
  "tools/openclinxr/openclaw/integrate.ts -> ../../../packages/openclinxr/agent-loop/src/done-when-rules.js",
  "tools/openclinxr/openclaw/openclaw-slice-runner.ts -> ../../../packages/openclinxr/agent-loop/src/slice-team.js",
  "tools/openclinxr/openclaw/openclaw-sweep.ts -> ../../../packages/openclinxr/agent-loop/src/done-when-live.js",
  "tools/openclinxr/openclaw/slice-team-cli.ts -> ../../../packages/openclinxr/agent-loop/src/grok-repo-agent-spawn.js",
  "tools/openclinxr/openclaw/slice-team-cli.ts -> ../../../packages/openclinxr/agent-loop/src/role-harness-policy.js",
  "tools/openclinxr/openclaw/slice-team-cli.ts -> ../../../packages/openclinxr/agent-loop/src/slice-team.js",
  "tools/openclinxr/openclaw/slice-team-cli.ts -> ../../../packages/openclinxr/agent-loop/src/spawn-isolation.js",
  "tools/openclinxr/openclaw/worktree-promote.ts -> ../../../packages/openclinxr/agent-loop/src/role-harness-policy.js",
  "tools/openclinxr/scenario-authoring-roundtrip.ts -> ../../packages/openclinxr/scenario-fixtures/src/index.js",
  "tools/openclinxr/scenario-authoring-roundtrip.ts -> ../../packages/openclinxr/scenario-runtime/src/index.js",
  "tools/openclinxr/scenario-authoring-roundtrip.ts -> ../../packages/openclinxr/shared-schemas/src/index.js",
  "tools/openclinxr/wire-api-durable-store-consumer.ts -> ../../packages/openclinxr/scenario-fixtures/src/index.js",
  "tools/openclinxr/wire-api-durable-store-consumer.ts -> ../../packages/openclinxr/scenario-runtime/src/index.js",
  "tools/openclinxr/wire-api-durable-store-consumer.ts -> ../../packages/openclinxr/shared-schemas/src/index.js"
];

describe("nothing reaches across a package boundary by path", () => {
  it("matches the shrink-only freeze of relative imports into another package src", () => {
    expect(crossPackageSrcReaches()).toEqual(FROZEN);
  });
});
