/**
 * Public interface of @openclinxr/xr-actor-dialogue.
 *
 * Named lists, not `export *`. A star republishes a module wholesale, so a symbol added inside
 * becomes public with nobody deciding it should be. Generated by `pnpm arch:narrow-entrypoint`
 * from what the tree actually consumes, then proved by `pnpm packages:typecheck:agent`.
 */

export {
  createActorDialogueStore,
} from "./store.js";
export type {
  ActorDialogueAdaptiveEvidence,
  ActorDialoguePlaybackEvidence,
  ActorDialogueSequence,
  ActorDialogueTurn,
} from "./types.js";
