/**
 * Public interface of @openclinxr/xr-scene-cues.
 *
 * Named lists, not `export *`. A star republishes a module wholesale, so a symbol added inside
 * becomes public with nobody deciding it should be. Generated by `pnpm arch:narrow-entrypoint`
 * from what the tree actually consumes, then proved by `pnpm packages:typecheck:agent`.
 */
export {
  addPediatricRespiratoryEquipmentCues,
  applyCleanEncounterVisualReviewActorFraming,
  recordDynamicSceneObjectNamingEvidence,
  recordPediatricRespiratoryEquipmentCue,
  recordRoleDistinctHumanoidCue,
} from "./cue-evidence.js";
export {
  createAffordanceMarker,
  createHumanoidExpressionCue,
  createHumanoidEyeFocusCue,
  createHumanoidEyeGazeCue,
  createHumanoidInteractionCollisionCues,
  createHumanoidSpeechMouthCue,
  createRuntimeHumanoidDetailCues,
} from "./humanoid-cues.js";
export {
  createActorNameplate,
  createVirtualDeviceActorAffordance,
} from "./nameplates.js";
export {
  createDetailedEdRoomProps,
  updateEnvironmentRealismAnimations,
} from "./room-props.js";
export {
  clinicalPanelLinesForBundle,
  createClinicalPanel,
  createReadableVrTextPanel,
} from "./scene-panels.js";
export {
  applyEnvironmentStateVisuals,
  applyRuntimeEquipmentTraceVisuals,
  runtimeEquipmentIdsForTag,
} from "./trace-visuals.js";
export type {
  DynamicSceneObjectNamingEvidence,
  PediatricRespiratoryEquipmentCueEvidence,
  ReadableVrTextPanel,
  RoleDistinctHumanoidCueEvidence,
  SceneCueActorFramingContext,
  SceneCueClinicalPanelContext,
  SceneCueEnvironmentVisualContext,
  SceneCueHumanoidCueContext,
  SceneCueNameplateContext,
  SceneCueNamingEvidenceContext,
  SceneCuePediatricCueEvidenceContext,
  SceneCuePediatricEquipmentContext,
  SceneCueRoleCueEvidenceContext,
  SceneCueRoomPropContext,
  SceneCueTraceVisualContext,
  SceneCueVirtualDeviceContext,
} from "./types.js";
