/**
 * Generate src/solver-map.generated.ts for the mouth registry (MADR 0061 d4).
 *
 * Scans the sibling mouth station packages for stationRole solver entries,
 * reads each solver's public-api.json "." export (exactly one runtime export
 * per d3: one constant with id, version and solve), and emits the registry's
 * solver map. Run: pnpm exec tsx scripts/generate-solver-map.ts
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const STATIONS_DIR = path.resolve(HERE, "..", "..");
const OUT_REL = path.join("src", "solver-map.generated.ts");

type SolverEntry = { packageName: string; exportName: string };

/** Sibling station packages of the same station carrying stationRole solver. */
export function discoverSolverEntries(stationsDir: string, stationId: string): SolverEntry[] {
  const entries: SolverEntry[] = [];
  for (const dirent of readdirSync(stationsDir, { withFileTypes: true }).sort((a, b) =>
    a.name.localeCompare(b.name),
  )) {
    if (!dirent.isDirectory()) continue;
    const manifestPath = path.join(stationsDir, dirent.name, "package.json");
    let manifest: { name?: string; openclinxr?: { station?: string; stationRole?: string } };
    try {
      manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as typeof manifest;
    } catch {
      continue;
    }
    if (manifest.openclinxr?.station !== stationId || manifest.openclinxr?.stationRole !== "solver") {
      continue;
    }
    if (typeof manifest.name !== "string") throw new Error(`solver at ${dirent.name} has no name`);
    const apiPath = path.join(stationsDir, dirent.name, "public-api.json");
    const api = JSON.parse(readFileSync(apiPath, "utf8")) as { entrypoints?: Record<string, string[]> };
    const dot = api.entrypoints?.["."];
    if (dot === undefined || dot.length !== 1 || dot[0] === undefined) {
      throw new Error(
        `solver ${manifest.name} must export exactly one runtime name (MADR 0061 d3), saw ${JSON.stringify(dot)}`,
      );
    }
    entries.push({ packageName: manifest.name, exportName: dot[0] });
  }
  return entries;
}

/** Render the generated map module text for solver entries. */
export function renderSolverMap(stationId: string, entries: SolverEntry[]): string {
  const imports = entries.map(
    (entry) => `import { ${entry.exportName} } from "${entry.packageName}";`,
  );
  const items = entries.map((entry) => `  ${entry.exportName},`);
  return `/**
 * GENERATED by pnpm exec tsx scripts/generate-solver-map.ts (MADR 0061 d4).
 *
 * Do not hand-edit: the map resolves every stationRole solver package of the
 * ${stationId} station to its one exported solver module. The registry is the
 * only package allowed to import solver packages (solver-importer allowlist).
 */
${imports.join("\n")}
import type { SolverModule } from "@openclinxr/station-mouth-objective";

/** Every ${stationId}-station solver module the registry may resolve by pin. */
export const mouthSolverModules: readonly SolverModule[] = [
${items.join("\n")}
];
`;
}

const station = process.argv[2] ?? "mouth";
const solverEntries = discoverSolverEntries(STATIONS_DIR, station);
if (solverEntries.length === 0) throw new Error(`no solver packages found for station ${station}`);
const outPath = path.resolve(HERE, "..", OUT_REL);
writeFileSync(outPath, renderSolverMap(station, solverEntries));
console.log(`wrote ${path.relative(process.cwd(), outPath)} with ${solverEntries.length} solver(s)`);
