/**
 * Public interface of @openclinxr/shared-schemas.
 *
 * Named lists, not `export *`. A star republishes a module wholesale, so a symbol added inside
 * becomes public with nobody deciding it should be. Generated by `pnpm arch:narrow-entrypoint`
 * from what the tree actually consumes, then proved by `pnpm packages:typecheck:agent`.
 */
export {
  ActorCardSchema,
  ActorPhenotypeSchema,
  ActorPlacementSchema,
  ActorTurnExecutionSchema,
  ActorTurnPlanSchema,
  AssetKindSchema,
  AssetNeedSchema,
  CaseEmotionPolicySchema,
  ComplianceRegionSchema,
  EmotionEventKindSchema,
  EmotionTransitionRuleSchema,
  EnvironmentSchema,
  InteractionEmotionSchema,
  ScenarioSchema,
  TouchResponseSchema,
} from "./schemas.js";
export type {
  ActorCard,
  ActorPhenotype,
  ActorTurnExecution,
  ActorTurnPlan,
  AssetKind,
  AssetManifest,
  BodyMechanics,
  CaseEmotionPolicy,
  CommunicationProfile,
  ComplianceRegion,
  DialogueEmotion,
  DynamicEncounterFactoryPlanningProjection,
  DynamicEncounterFactoryProjectionArtifact,
  EmotionEventKind,
  EmotionTransitionRule,
  ExamBlueprint,
  ExamBlueprintTiming,
  ExamStationSlot,
  InteractionEmotion,
  ModelProviderAudit,
  PatientNote,
  ProviderAuditRecord,
  ProviderHealth,
  ReviewPacket,
  Scenario,
  ScenarioGovernance,
  StationPhase,
  StationRun,
  TouchResponse,
  TraceEvent,
  VoiceProviderAudit,
} from "./schema-types.js";
export {
  validateAssetManifest,
  validateCaseEmotionPolicy,
  validateCommunicationProfile,
  validateDynamicEncounterFactoryProjectionArtifact,
  validateEnvironmentManifest,
  validateModelProviderAudit,
  validatePatientNote,
  validateProviderAuditRecord,
  validateProviderHealth,
  validateReviewPacket,
  validateScenario,
  validateTraceEvent,
  validateVoiceProviderAudit,
} from "./validators.js";
export type {
  ValidationResult,
} from "./validators.js";
export {
  ModelProviderAuditSchema,
  ProviderAuditRecordSchema,
  ProviderHealthSchema,
  TraceEventSchema,
  VoiceProviderAuditSchema,
} from "./runtime-schemas.js";
export type {
  FactoryStationSchema,
  ProductionStationId,
  StandardIssue,
  StandardResult,
  StationJsonSchema,
  StationPropertySchema,
} from "./factory-stations.js";
