/**
 * Public interface of @openclinxr/shared-schemas.
 *
 * Named lists, not `export *`. A star republishes a module wholesale, so a symbol added inside
 * becomes public with nobody deciding it should be. Generated by `pnpm arch:narrow-entrypoint`
 * from what the tree actually consumes, then proved by `pnpm packages:typecheck:agent`.
 */

export type {
  EquipmentBindingClassification,
} from "./equipment-binding.js";
export {
  classifyScenarioEquipmentBinding,
  EQUIPMENT_BINDING_PRECEDENCE,
} from "./equipment-binding.js";
export type {
  ProductionStationId,
} from "./factory-stations.js";
export {
  InitialSceneSpec,
} from "./initial-scene-spec.js";
export type {
  ActorCard,
  ActorPhenotype,
  ActorTurnExecution,
  ActorTurnPlan,
  AssetKind,
  AssetManifest,
  BodyMechanics,
  CaseEmotionPolicy,
  ComplianceRegion,
  DialogueEmotion,
  DynamicEncounterFactoryPlanningProjection,
  DynamicEncounterFactoryProjectionArtifact,
  EmotionEventKind,
  EmotionTransitionRule,
  ExamBlueprint,
  ExamBlueprintTiming,
  ExamStationSlot,
  InteractionEmotion,
  PatientNote,
  ProviderHealth,
  ReviewPacket,
  Scenario,
  ScenarioGovernance,
  StationPhase,
  StationRun,
  TouchResponse,
  TraceEvent,
} from "./schema-types.js";
export {
  ActorCardSchema,
  ActorPhenotypeSchema,
  ActorPlacementSchema,
  AssetKindSchema,
  AssetNeedSchema,
  CaseEmotionPolicySchema,
  ComplianceRegionSchema,
  EnvironmentSchema,
  ScenarioSchema,
  TouchResponseSchema,
} from "./schemas.js";
export type {
  ValidationResult,
} from "./validators.js";
export {
  validateAssetManifest,
  validateCaseEmotionPolicy,
  validateCommunicationProfile,
  validateDynamicEncounterFactoryProjectionArtifact,
  validateEnvironmentManifest,
  validateModelProviderAudit,
  validatePatientNote,
  validateProviderAuditRecord,
  validateProviderHealth,
  validateReviewPacket,
  validateScenario,
  validateTraceEvent,
  validateVoiceProviderAudit,
} from "./validators.js";
