/**
 * Cast asset filename/path constants — the naming SSOT for the scenario casting
 * resolver (actor-casting.ts) and the modules that consume or mirror cast paths.
 *
 * Split out of actor-casting.ts (#403) to keep that resolver within its
 * file-size budget; actor-casting re-exports every previously-exported symbol so
 * the import surface is unchanged.
 */

export const GENERATED = "apps/ui-xr/public/generated-humanoids";
export const RUNTIME_GENERATED = "/generated-humanoids";
/** #218 — parametric body-param library line under candidates/ (tracked GLBs). */
export const CANDIDATES = "apps/ui-xr/public/xr-assets/humanoids/candidates";
export const RUNTIME_CANDIDATES = "/xr-assets/humanoids/candidates";

/**
 * Distinct humanoid bodies on disk (by content hash). Reuse across scenarios
 * is expected; within one scenario each humanoid role must get a different body.
 *
 * #160: adult_male_street_casual is the male street body for home/ambulatory
 * patient attire (telehealth + clinic share it). Female street remains on
 * spouse/parent shells.
 */
export const ED_ADULT_CAST_GLB = "ed_chest_pain_adult_cast.glb";
export const ED_NURSE_GLB = "ed_chest_pain_nurse_adult.glb";
export const ED_SPOUSE_GLB = "ed_chest_pain_spouse_adult.glb";
export const PEDS_PARENT_GLB = "peds_anxious_parent.glb";
export const PEDS_NURSE_GLB = "peds_nurse_kevin.glb";
export const PEDS_CHILD_GLB = "peds_patient_child.glb";
/** Male street casual — blender-only rebake (#160); not a gown, not female street. */
export const ADULT_MALE_STREET_CASUAL_GLB = "adult_male_street_casual.glb";
/**
 * #218 library body class staged into ONE ED family slot (not the gown patient).
 * adult_lean_female: female spouse phenotype cue; scrub fitted by #215/#216.
 * Rejected adult_heavy_male for this slot (male body class on female actor id).
 */
export const LIBRARY_ADULT_LEAN_FEMALE_GLB = "body-param-adult_lean_female-library.glb";
/**
 * #278 — the second proven hm08 library body class (route 2 from #276).
 * adult_heavy_male: male body class (weight 0.88 macro), 8.76 cm girth spread vs lean female
 * at the same 1.76 m stature (#151). Same per-class fitted garment/scalp/footwear as lean female
 * (#277/#279). Body class must match the actor's declared sex — see the PEDS table below.
 */
export const LIBRARY_ADULT_HEAVY_MALE_GLB = "body-param-adult_heavy_male-library.glb";
/**
 * #263 — first promoted MPFB2 humanoid cast (OB triage patient Aisha Khan).
 * Byte-identical promote of the tracked candidates/ comparator to the runtime
 * cast path generated-humanoids/. MPFB rail is first-class per D11 (standard
 * rig, face shape keys, MakeHuman wardrobe); the humans freeze was Anny-only.
 */
export const MPFB_OB_PATIENT_AISHA_GLB = "mpfb-ob-patient-aisha.glb";
/**
 * #335 — the two peds MPFB bodies (nurse + child) reach the peds asthma station.
 * Generated by the same `materialize_mpfb_humanoid_candidate.py` rail as aisha;
 * both now carry upper + lower + footwear (#333) and their hide masks stop below
 * their own head joints (#334). Cast with aisha so all three peds roles are MPFB.
 */
export const MPFB_PEDS_NURSE_KEVIN_GLB = "mpfb-peds-nurse-kevin.glb";
export const MPFB_PEDS_PATIENT_CHILD_GLB = "mpfb-peds-patient-child.glb";
/**
 * #388 — peds parent is a SECOND aisha-body variant, not the OB patient GLB.
 * Recolouring mpfb-ob-patient-aisha.glb would collide with Omar's muted rose
 * in OB. Same default-macro adult-female bake as aisha, --actor-role parent
 * so garment_shell_color maps closed_casual (t-shirt + cargo) to
 * muted_rose_and_neutral. OB aisha stays cream.
 */
export const MPFB_PEDS_PARENT_AISHA_GLB = "mpfb-peds-parent-aisha.glb";
/** Dark-factory B: peds parent runtime is the motion-bind GLB (walk clip). */
export const MPFB_PEDS_PARENT_AISHA_MOTION_BIND_GLB = "mpfb-peds-parent-aisha.motion-bind.glb";
/**
 * #403 — step 2 of the MPFB2 migration: two adult MPFB bodies replace the shared
 * Anny nurse/spouse meshes (19 slots). Both are generated from the tracked Anny
 * references ed_chest_pain_nurse_adult / ed_chest_pain_spouse_adult via the same
 * materializer rail (#328: age + height measured from the reference, not literals).
 * Nurse-class roles (nurse, physician, respiratory_therapist, medical_assistant,
 * consultant) resolve to the clinical-nurse body; family-class roles resolve to the
 * family-partner body. Physician/RT/MA share the nurse body by design — a named
 * clinical-team look-alike, not a third bake.
 */
export const MPFB_CLINICAL_NURSE_ADULT_GLB = "mpfb-clinical-nurse-adult.glb";
export const MPFB_CLINICAL_PHYSICIAN_ADULT_GLB = "mpfb-clinical-physician-adult.glb";
export const MPFB_FAMILY_PARTNER_ADULT_GLB = "mpfb-family-partner-adult.glb";

/** Adult pool only — never includes the child mesh. Order is role-preference default. */
export const ADULT_POOL_GLBS = [
  ED_ADULT_CAST_GLB,
  ED_NURSE_GLB,
  ED_SPOUSE_GLB,
  PEDS_PARENT_GLB,
  PEDS_NURSE_GLB,
  ADULT_MALE_STREET_CASUAL_GLB,
] as const;

export const ED_ADULT_CAST_RUNTIME_PATH = `${RUNTIME_GENERATED}/${ED_ADULT_CAST_GLB}`;
export const ED_ADULT_CAST_ASSET_PATH = `${GENERATED}/${ED_ADULT_CAST_GLB}`;
export const ED_ADULT_CAST_PROVENANCE_PATH = `${GENERATED}/${ED_ADULT_CAST_GLB.replace(/\.glb$/u, ".provenance.json")}`;
