import { evaluateRequiredTraceTags } from "@openclinxr/domain";
import { validateReviewPacket, type PatientNote, type ReviewPacket } from "@openclinxr/shared-schemas";

export type ReviewTraceInput = {
  sequence?: number;
  tag?: string;
  atSecond: number;
  eventType?: string;
  source?: string;
  actorId?: string;
  payload?: Record<string, unknown>;
};

export type BuildReviewPacketInput = {
  stationRunId: string;
  scenarioId: string;
  requiredTraceTags: readonly string[];
  timeCriticalTraceTagThresholds?: Readonly<Record<string, number>>;
  traceEvents: readonly ReviewTraceInput[];
  patientNote?: PatientNote;
  facultyScoreDraft: ReviewPacket["facultyScoreDraft"];
};

export function buildReviewPacket(input: BuildReviewPacketInput): ReviewPacket {
  if (input.facultyScoreDraft.reviewerId.trim().length === 0) {
    throw new Error("Faculty score draft requires reviewer identity");
  }

  const { observed, missing } = evaluateRequiredTraceTags(input.requiredTraceTags, input.traceEvents);
  const sortedTraceEvents = [...input.traceEvents].sort((a, b) => traceSequence(a) - traceSequence(b));
  const unsafeEvents = input.traceEvents
    .filter((event) => event.eventType?.startsWith("unsafe."))
    .map((event) => event.eventType)
    .filter((eventType): eventType is string => Boolean(eventType));
  const modelGeneratedEvents = input.traceEvents.filter((event) => event.eventType === "actor.response.generated");
  const modelFailedEvents = input.traceEvents.filter((event) => event.eventType === "actor.response.failed");
  const voiceAudioEvents = input.traceEvents.filter((event) => event.eventType === "voice.audio.generated");
  const packet: ReviewPacket = {
    stationRunId: input.stationRunId,
    scenarioId: input.scenarioId,
    observedTraceTags: observed,
    missingRequiredTraceTags: missing,
    lateTraceTags: lateTraceTags(input.traceEvents, input.timeCriticalTraceTagThresholds ?? {}),
    unsafeEvents,
    timeline: sortedTraceEvents.map((event, index) => ({
      sequence: event.sequence ?? index,
      atSecond: event.atSecond,
      eventType: event.eventType ?? "trace.event",
      source: event.source ?? "unknown",
      ...(event.actorId ? { actorId: event.actorId } : {}),
      ...(event.tag ? { tag: event.tag } : {}),
      summary: summarizeTimelineEvent(event),
    })),
    traceQuality: {
      eventCount: input.traceEvents.length,
      modelGeneratedEventCount: modelGeneratedEvents.length,
      modelFailedEventCount: modelFailedEvents.length,
      voiceAudioEventCount: voiceAudioEvents.length,
      blockedGuardrailCount: input.traceEvents.filter(hasBlockedGuardrail).length,
      unsafeEventCount: unsafeEvents.length,
      missingRequiredTraceTagCount: missing.length,
      hasPatientNote: Boolean(input.patientNote),
      hasModelProvenance: modelGeneratedEvents.length > 0 && modelGeneratedEvents.every(hasModelProvenance),
    },
    ...(input.patientNote ? { patientNote: input.patientNote } : {}),
    facultyScoreDraft: input.facultyScoreDraft,
  };

  const validation = validateReviewPacket(packet);
  if (!validation.ok) {
    throw new Error(`Invalid review packet: ${validation.errors.join("; ")}`);
  }

  return packet;
}

function traceSequence(event: ReviewTraceInput): number {
  return event.sequence ?? Number.MAX_SAFE_INTEGER;
}

function lateTraceTags(traceEvents: readonly ReviewTraceInput[], thresholds: Readonly<Record<string, number>>): string[] {
  const lateTags: string[] = [];
  const seen = new Set<string>();

  for (const event of traceEvents) {
    if (!event.tag || seen.has(event.tag)) {
      continue;
    }
    const threshold = thresholds[event.tag];
    if (threshold !== undefined && event.atSecond > threshold) {
      lateTags.push(event.tag);
      seen.add(event.tag);
    }
  }

  return lateTags;
}

function summarizeTimelineEvent(event: ReviewTraceInput): string {
  if (event.eventType === "learner.utterance" && event.actorId) {
    const text = payloadString(event.payload, "text");
    return `Learner to ${event.actorId}: ${text ?? "utterance recorded"}`;
  }

  if (event.eventType === "actor.response.generated" && event.actorId) {
    const providerId = nestedPayloadString(event.payload, ["provenance", "providerId"]) ?? "model provider";
    const responseKind = payloadString(event.payload, "responseKind");
    return `${event.actorId} response generated by ${providerId}${responseKind ? ` (${responseKind})` : ""}`;
  }

  if (event.eventType === "actor.response.failed" && event.actorId) {
    return `${event.actorId} response generation failed`;
  }

  if (event.eventType === "voice.audio.generated" && event.actorId) {
    return `${event.actorId} voice audio generated`;
  }

  if (event.eventType === "note.submitted") {
    return "Patient note submitted";
  }

  return `${event.source ?? "unknown"} ${event.eventType ?? "trace.event"}`;
}

function hasBlockedGuardrail(event: ReviewTraceInput): boolean {
  return nestedPayloadString(event.payload, ["provenance", "guardrail", "status"]) === "blocked" || payloadString(event.payload, "responseKind") === "blocked_fallback";
}

function hasModelProvenance(event: ReviewTraceInput): boolean {
  return Boolean(recordValue(event.payload, "provenance"));
}

function payloadString(payload: Record<string, unknown> | undefined, key: string): string | undefined {
  const value = payload?.[key];
  return typeof value === "string" ? value : undefined;
}

function nestedPayloadString(payload: Record<string, unknown> | undefined, keys: readonly string[]): string | undefined {
  let value: unknown = payload;
  for (const key of keys) {
    if (!isRecord(value)) {
      return undefined;
    }
    value = value[key];
  }

  return typeof value === "string" ? value : undefined;
}

function recordValue(payload: Record<string, unknown> | undefined, key: string): Record<string, unknown> | undefined {
  const value = payload?.[key];
  return isRecord(value) ? value : undefined;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
