/**
 * Public interface of @openclinxr/xr-station.
 *
 * Named lists, not `export *`. A star republishes a module wholesale, so a symbol added inside
 * becomes public with nobody deciding it should be. Generated by `pnpm arch:narrow-entrypoint`
 * from what the tree actually consumes, then proved by `pnpm packages:typecheck:agent`.
 */

export type {
  StationApiClient,
} from "./api-client.js";
export {
  createStationApiPersistenceSink,
} from "./api-client.js";
export {
  enableCaptureRendererShadowMap,
  isCaptureShadowPath,
  markActorCastShadow,
  markFloorReceiveShadow,
} from "./capture-shadow-map.js";
export {
  roomPropSuppressedByFixtureOwnership,
  stampSuppressedDeclaredEquipmentOntoFixtures,
} from "./fixture-role-ownership.js";
export type {
  RoomPropClass,
} from "./room-prop-classification.js";
export {
  classifyRoomProp,
  PARAMETRIC_KINDS,
  resolveRoomPropBuilderEquipmentId,
  stampRoomPropAliasesOnEquipmentRoot,
} from "./room-prop-classification.js";
export type {
  BuildRoomPropInput,
} from "./room-prop-geometry.js";
export {
  buildRoomPropGroup,
} from "./room-prop-geometry.js";
export type {
  RoomPropColourInput,
} from "./room-prop-materials.js";
export {
  buildRoomPropMaterialColours,
  roomPropColourNumbers,
} from "./room-prop-materials.js";
export type {
  AssembledStationApiClient,
} from "./station-api-client.js";
export {
  buildAssembledStationStartSessionInput,
  createStationApiClient as createAssembledStationApiClient,
  syncRemoteAssembledPhase,
} from "./station-api-client.js";
export {
  anchorFixtureNearFaceToPlane,
  buildDoorLeafFixture,
  buildWallBoardFixture,
} from "./station-architecture-fixtures.js";
export {
  buildPatientChair,
  isPatientChairSlotId,
  PATIENT_CHAIR_SEAT_HEIGHT_METERS,
} from "./station-chair.js";
export {
  resolveChartFieldsForScenario,
} from "./station-chart.js";
export type {
  StationContextView,
} from "./station-context.js";
export {
  stationContextForScenario,
} from "./station-context.js";
export type {
  BuildStationEnvironmentInput,
} from "./station-environment.js";
export {
  buildStationEnvironment,
  parametricWallInnerPlane,
  resolveStationEnvironment,
} from "./station-environment.js";
export {
  buildDeclaredEquipmentGeometry,
  buildGenericClinicalEquipmentFallback,
  buildGltfEquipmentPlaceholderSlot,
  collectDeclaredEquipmentEvidenceFromScene,
  countEquipmentGeometry,
  EXAM_TABLE_LENGTH_M,
  listDeclaredEquipmentBuilderArms,
  normalizeGltfEquipmentMount,
  parametricEquipmentKindCount,
  planStationEquipmentMounts,
  REAL_EQUIPMENT_GLTF_BY_ID,
} from "./station-equipment.js";
export type {
  ParametricCompositeMeasure,
} from "./station-equipment-composite-measure.js";
export {
  measureParametricComposite,
} from "./station-equipment-composite-measure.js";
export type {
  EnvironmentRow,
  StationFixtureVocabularyReport,
} from "./station-fixture-vocabulary-inspect.js";
export {
  inspectStationFixtureVocabulary,
} from "./station-fixture-vocabulary-inspect.js";
export type {
  StationInteriorLightingApplyResult,
  StationInteriorLightingVariantId,
} from "./station-interior-lighting.js";
export {
  applyStationInteriorLighting,
  resolveStationInteriorLightingVariantId,
  STATION_INTERIOR_LIGHTING_VARIANT_IDS,
} from "./station-interior-lighting.js";
export {
  buildPatientStretcher,
  findProceduralStretcher,
  findProceduralStretcherInSceneOf,
  prepareLoadedEnvironmentShell,
  readStretcherBackSectionWorldDeg,
  readStretcherDeckSectionNames,
  readStretcherInclineDegrees,
  readStretcherPillowWorld,
  STRETCHER_DECK_TOP_METERS,
  STRETCHER_LENGTH_METERS,
  setStretcherInclineDegrees,
} from "./station-stretcher.js";
export type {
  InitialVitalsValueClass,
} from "./station-vitals.js";
export {
  classifyInitialVitalsRaw,
  resolveInitialVitalsForScenario,
} from "./station-vitals.js";
