import type { ReviewPacket, Scenario, TraceEvent } from "@openclinxr/shared-schemas";
import {
  assembleExamForm,
  createDefaultClinicalSkillsBlueprint,
  createExamStationRunQueue,
  createStep2CsStyleSeedBlueprint,
} from "@openclinxr/exam-assembly";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import {
  createMongoMemoryTestContext,
  MongoExamFormRepository,
  createMongoApiPersistenceSink,
  MongoScenarioRepository,
  MongoStationRunQueueRepository,
  MongoTraceRepository,
  MongoReviewPacketRepository,
  type MongoMemoryTestContext,
} from "./index.js";

const scenario: Scenario = {
  scenarioId: "ed_chest_pain_priority_v1",
  version: 1,
  title: "ED Chest Pain",
  status: "approved",
  review: {
    clinical: "approved",
    psychometric: "approved",
    legal: "approved",
    simulationQa: "approved",
  },
  clinicalObjectives: ["Recognize possible ACS"],
  actors: [],
  requiredTraceTags: ["ecg_request"],
  eventSchedule: [],
  reviewRubric: [],
  governance: {
    scoreUseLabel: "formative_local_only",
    syntheticCaseDisclosure: "Synthetic repository-contract fixture.",
    validationStage: "stage_1_expert_reviewed",
    validationLimitations: ["Repository fixture only; no validity evidence."],
    requiredReviewerRoles: ["clinician", "psychometrician", "legal", "simulation_qa"],
    sourceIds: ["src-test-fixture"],
    safetyCriticalTraceTags: ["ecg_request"],
    hiddenFactPolicy: {
      learnerView: "redact_hidden_facts",
      disclosureRequiresTrigger: true,
    },
  },
};

function trace(sequence: number, tag?: string, stationRunId = "run_001"): TraceEvent {
  const event: TraceEvent = {
    stationRunId,
    sequence,
    eventType: "learner.action",
    occurredAt: new Date(Date.parse("2026-05-03T15:38:58.000Z") + sequence * 1000).toISOString(),
    atSecond: sequence,
    source: "learner",
    payload: {},
  };
  if (tag) {
    event.tag = tag;
  }
  return event;
}

const reviewPacket: ReviewPacket = {
  stationRunId: "run_001",
  scenarioId: "ed_chest_pain_priority_v1",
  observedTraceTags: ["ecg_request"],
  missingRequiredTraceTags: [],
  lateTraceTags: [],
  unsafeEvents: [],
  timeline: [
    {
      sequence: 0,
      atSecond: 0,
      eventType: "station.started",
      source: "system",
      summary: "system station.started",
    },
    {
      sequence: 1,
      atSecond: 120,
      eventType: "actor.response.generated",
      source: "model-gateway",
      actorId: "patient_robert_hayes_v1",
      tag: "history_opqrst",
      summary: "patient_robert_hayes_v1 response generated by mock-model (spoken_actor_response)",
    },
  ],
  traceQuality: {
    eventCount: 2,
    modelGeneratedEventCount: 1,
    modelFailedEventCount: 0,
    voiceAudioEventCount: 0,
    blockedGuardrailCount: 0,
    unsafeEventCount: 0,
    missingRequiredTraceTagCount: 0,
    hasPatientNote: true,
    hasModelProvenance: true,
  },
  patientNote: {
    stationRunId: "run_001",
    submittedAtSecond: 1260,
    text: "Concern for ACS. ECG requested.",
  },
  facultyScoreDraft: {
    reviewerId: "faculty_001",
    status: "draft",
    comments: "Ready for faculty scoring.",
  },
};

const seedQueueScenarios: Scenario[] = Array.from({ length: 12 }, (_, index) => {
  const stationOrder = index + 1;
  const scenarioId = stationOrder === 9
    ? "clinic_abdominal_pain_interpreter_v1"
    : `seed_station_${String(stationOrder).padStart(2, "0")}_v1`;

  return {
    ...scenario,
    scenarioId,
    version: 1,
    title: stationOrder === 9 ? "Clinic abdominal pain with interpreter" : `Seed station ${stationOrder}`,
    status: stationOrder === 1 ? "approved" : "draft",
    review: stationOrder === 1
      ? scenario.review
      : {
        clinical: "draft",
        psychometric: "draft",
        legal: "draft",
        simulationQa: "draft",
      },
    requiredTraceTags: [`station_${stationOrder}_trace`],
    governance: {
      ...scenario.governance,
      safetyCriticalTraceTags: [`station_${stationOrder}_safety_trace`],
      validationStage: stationOrder === 1 ? "stage_1_expert_reviewed" : "stage_0_synthetic_draft",
    },
  };
});

describe("MongoDB memory repositories", () => {
  let context: MongoMemoryTestContext;

  beforeAll(async () => {
    context = await createMongoMemoryTestContext();
  }, 120_000);

  afterAll(async () => {
    await context.close();
  });

  it("stores and retrieves versioned scenarios", async () => {
    const repository = new MongoScenarioRepository(context.db);
    await repository.ensureIndexes();
    await repository.save(scenario);

    await expect(repository.findByIdAndVersion("ed_chest_pain_priority_v1", 1)).resolves.toMatchObject({
      scenarioId: "ed_chest_pain_priority_v1",
      version: 1,
      status: "approved",
    });

    await expect(repository.approved()).resolves.toHaveLength(1);
  });

  it("enforces trace sequence uniqueness and replays in order", async () => {
    const repository = new MongoTraceRepository(context.db);
    await repository.ensureIndexes();
    await repository.append(trace(0, "station_started"));
    await repository.append(trace(1, "ecg_request"));

    await expect(repository.append(trace(1, "duplicate_sequence"))).rejects.toThrow();
    await expect(repository.replay("run_001")).resolves.toEqual([expect.objectContaining({ sequence: 0 }), expect.objectContaining({ sequence: 1 })]);
  });

  it("upserts replay snapshots idempotently and reports the latest sequence", async () => {
    const repository = new MongoTraceRepository(context.db);
    await repository.ensureIndexes();

    await repository.upsertMany([trace(10, "station_started", "run_snapshot"), trace(11, "history_opqrst", "run_snapshot")]);
    await repository.upsertMany([trace(10, "station_started", "run_snapshot"), trace(11, "history_opqrst", "run_snapshot"), trace(12, "ecg_request", "run_snapshot")]);

    await expect(repository.replay("run_snapshot")).resolves.toEqual([
      expect.objectContaining({ sequence: 10 }),
      expect.objectContaining({ sequence: 11 }),
      expect.objectContaining({ sequence: 12 }),
    ]);
    await expect(repository.latestSequence("run_snapshot")).resolves.toBe(12);
    await expect(repository.latestSequence("missing_run")).resolves.toBeNull();
  });

  it("stores and retrieves review packets with trace quality evidence", async () => {
    const repository = new MongoReviewPacketRepository(context.db);
    await repository.ensureIndexes();
    await repository.save(reviewPacket);

    await expect(repository.findByStationRunId("run_001")).resolves.toMatchObject({
      stationRunId: "run_001",
      scenarioId: "ed_chest_pain_priority_v1",
      traceQuality: {
        modelGeneratedEventCount: 1,
        hasModelProvenance: true,
      },
      patientNote: {
        text: "Concern for ACS. ECG requested.",
      },
    });

    await expect(repository.listByScenario("ed_chest_pain_priority_v1")).resolves.toHaveLength(1);
  });

  it("stores exam forms with locked scenario versions for drift review", async () => {
    const repository = new MongoExamFormRepository(context.db);
    await repository.ensureIndexes();
    const form = assembleExamForm({
      examFormId: "form_openclinxr_pilot_001",
      blueprint: createDefaultClinicalSkillsBlueprint(),
      scenarios: [scenario],
    });

    await repository.save(form);

    await expect(repository.findById("form_openclinxr_pilot_001")).resolves.toMatchObject({
      examFormId: "form_openclinxr_pilot_001",
      blueprintId: "blueprint_openclinxr_clinical_skills_pilot_v1",
      stationRefs: [
        {
          scenarioId: "ed_chest_pain_priority_v1",
          scenarioVersion: 1,
        },
      ],
    });
    await expect(repository.listByBlueprint("blueprint_openclinxr_clinical_skills_pilot_v1")).resolves.toHaveLength(1);
  });

  it("stores station run queue snapshots for reviewer launch gating", async () => {
    const repository = new MongoStationRunQueueRepository(context.db);
    await repository.ensureIndexes();
    const blueprint = createStep2CsStyleSeedBlueprint(seedQueueScenarios);
    const queue = createExamStationRunQueue(blueprint, seedQueueScenarios);

    await repository.save({
      snapshotId: "queue_snapshot_seed_001",
      createdAt: "2026-05-03T16:00:00.000Z",
      reviewerId: "psychometrician_001",
      queue,
    });

    await expect(repository.findById("queue_snapshot_seed_001")).resolves.toMatchObject({
      snapshotId: "queue_snapshot_seed_001",
      reviewerId: "psychometrician_001",
      queue: {
        blueprintId: "blueprint_openclinxr_step2cs_style_seed_v1",
        canStartLearnerExam: false,
        summary: {
          activationReady: 1,
          draftBlocked: 11,
          governanceBlocked: 0,
          missingScenario: 0,
        },
        stationQueue: expect.arrayContaining([
          expect.objectContaining({
            stationOrder: 9,
            scenarioId: "clinic_abdominal_pain_interpreter_v1",
            status: "draft_blocked",
            blockers: ["scenario_not_approved"],
          }),
        ]),
      },
    });
    await expect(repository.listByBlueprint("blueprint_openclinxr_step2cs_style_seed_v1")).resolves.toEqual([
      expect.objectContaining({
        snapshotId: "queue_snapshot_seed_001",
        queue: expect.objectContaining({
          totalStationTimeSeconds: 18720,
        }),
      }),
    ]);
  });

  it("persists API snapshots through a Mongo-backed sink", async () => {
    const sink = createMongoApiPersistenceSink(context.db);
    await sink.ensureIndexes();
    const form = assembleExamForm({
      examFormId: "form_sink_001",
      blueprint: createDefaultClinicalSkillsBlueprint(),
      scenarios: [scenario],
    });

    await sink.saveExamForm(form);
    await sink.saveTraceEvents("run_sink", [trace(0, "station_started", "run_sink"), trace(1, "ecg_request", "run_sink")]);
    await sink.saveTraceEvents("run_sink", [trace(0, "station_started", "run_sink"), trace(1, "ecg_request", "run_sink"), trace(2, "team_communication", "run_sink")]);
    await sink.saveReviewPacket("run_sink", { ...reviewPacket, stationRunId: "run_sink" });

    await expect(new MongoExamFormRepository(context.db).findById("form_sink_001")).resolves.toMatchObject({
      examFormId: "form_sink_001",
    });
    await expect(new MongoTraceRepository(context.db).replay("run_sink")).resolves.toHaveLength(3);
    await expect(new MongoReviewPacketRepository(context.db).findByStationRunId("run_sink")).resolves.toMatchObject({
      stationRunId: "run_sink",
    });
  });
});
