import type { ReviewPacket, Scenario, TraceEvent } from "@openclinxr/shared-schemas";
import type {
  AsyncDurableMultiActorSessionStore,
  DurableClinicalEventRecord,
  DurableConversationTurnRecord,
  DurableEmotionalStateTimelineRecord,
} from "@openclinxr/session-state";
import {
  assembleExamForm,
  createDefaultClinicalSkillsBlueprint,
  createExamStationRunQueue,
  createStep2CsStyleSeedBlueprint,
} from "@openclinxr/exam-assembly";
import type { Document } from "mongodb";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { createEdChestPainLocalEncounterRuntimeAssetBundle, createEdChestPainLocalLearnerRuntimeAssetBundle, toLearnerRuntimeAssetBundle, type EncounterRuntimeAsset, type EncounterRuntimeAssetBundle } from "../../asset-registry/src/runtime-bundles.js";
import {
  MongoExamFormRepository,
  createMongoApiPersistenceSink,
  MongoScenarioRepository,
  MongoScenarioReviewDecisionRepository,
  MongoStationRunQueueRepository,
  MongoTraceRepository,
  MongoReviewPacketRepository,
  MongoRuntimeAssetBundleRepository,
  saveLearnerRuntimeAssetBundleFromGeneratedReport,
  MongoDurableConversationTurnRepository,
  MongoDurableClinicalEventRepository,
  MongoDurableEmotionalStateTimelineRepository,
  createMongoDurableMultiActorSessionStore,
  durableClinicalEventPersistenceScope,
  durableActorTurnPersistenceScope,
  type ScenarioReviewDecisionRecord,
} from "./index.js";
import { createMongoMemoryTestContext, type MongoMemoryTestContext } from "./mongo-memory-context.js";

const scenario: Scenario = {
  scenarioId: "ed_chest_pain_priority_v1",
  version: 1,
  title: "ED Chest Pain",
  status: "approved",
  review: {
    clinical: "approved",
    psychometric: "approved",
    legal: "approved",
    simulationQa: "approved",
  },
  clinicalObjectives: ["Recognize possible ACS"],
  actors: [],
  requiredTraceTags: ["ecg_request"],
  eventSchedule: [],
  reviewRubric: [],
  governance: {
    scoreUseLabel: "formative_local_only",
    syntheticCaseDisclosure: "Synthetic repository-contract fixture.",
    validationStage: "stage_1_expert_reviewed",
    validationLimitations: ["Repository fixture only; no validity evidence."],
    requiredReviewerRoles: ["clinician", "psychometrician", "legal", "simulation_qa"],
    sourceIds: ["src-test-fixture"],
    safetyCriticalTraceTags: ["ecg_request"],
    hiddenFactPolicy: {
      learnerView: "redact_hidden_facts",
      disclosureRequiresTrigger: true,
    },
  },
};

function trace(sequence: number, tag?: string, stationRunId = "run_001"): TraceEvent {
  const event: TraceEvent = {
    stationRunId,
    sequence,
    eventType: "learner.action",
    occurredAt: new Date(Date.parse("2026-05-03T15:38:58.000Z") + sequence * 1000).toISOString(),
    atSecond: sequence,
    source: "learner",
    payload: {},
  };
  if (tag) {
    event.tag = tag;
  }
  return event;
}

const reviewPacket: ReviewPacket = {
  stationRunId: "run_001",
  scenarioId: "ed_chest_pain_priority_v1",
  observedTraceTags: ["ecg_request"],
  missingRequiredTraceTags: [],
  lateTraceTags: [],
  unsafeEvents: [],
  timeline: [
    {
      sequence: 0,
      atSecond: 0,
      eventType: "station.started",
      source: "system",
      summary: "system station.started",
    },
    {
      sequence: 1,
      atSecond: 120,
      eventType: "actor.response.generated",
      source: "model-gateway",
      actorId: "patient_robert_hayes_v1",
      tag: "history_opqrst",
      summary: "patient_robert_hayes_v1 response generated by mock-model (spoken_actor_response)",
    },
  ],
  traceQuality: {
    eventCount: 2,
    modelGeneratedEventCount: 1,
    modelFailedEventCount: 0,
    voiceAudioEventCount: 0,
    blockedGuardrailCount: 0,
    unsafeEventCount: 0,
    missingRequiredTraceTagCount: 0,
    hasPatientNote: true,
    hasModelProvenance: true,
  },
  patientNote: {
    stationRunId: "run_001",
    submittedAtSecond: 1260,
    text: "Concern for ACS. ECG requested.",
  },
  facultyScoreDraft: {
    reviewerId: "faculty_001",
    status: "draft",
    comments: "Ready for faculty scoring.",
  },
};

const scenarioReviewDecision: ScenarioReviewDecisionRecord = {
  scenarioId: "peds_asthma_parent_anxiety_v1",
  version: 1,
  reviewerRole: "clinical",
  reviewerId: "pediatrician_001",
  decision: "approved",
  comments: "Clinical review complete.",
  evidenceRefs: ["evidence:peds:clinical:2026-05-04"],
  reviewedAt: "2026-05-04T10:00:00.000Z",
};

const nurseConversationTurn: DurableConversationTurnRecord = {
  turnId: "turn_002_nurse_maria_alvarez_v1_180",
  stationRunId: "station_run_durable_actor_turn_001",
  actorId: "nurse_maria_alvarez_v1",
  atSecond: 180,
  sourceKind: "text",
  text: "Nurse, please repeat the blood pressure and start a 12-lead ECG.",
  traceContextTags: ["vitals_review", "ecg_request"],
  emotionalState: "focused",
  routingReason: "addressed_role_keyword",
  rawAudioStored: false,
  provenanceRefs: ["trace:station_run_durable_actor_turn_001:180"],
  durableStore: "database_source_of_truth",
};

const spouseConversationTurn: DurableConversationTurnRecord = {
  turnId: "turn_001_spouse_anna_hayes_v1_120",
  stationRunId: "station_run_durable_actor_turn_001",
  actorId: "spouse_anna_hayes_v1",
  atSecond: 120,
  sourceKind: "voice_transcript",
  text: "Anna, what happened right before he came in?",
  traceContextTags: ["history_onset", "family_collateral"],
  emotionalState: "anxious",
  routingReason: "addressed_actor_name",
  rawAudioStored: false,
  provenanceRefs: ["trace:voice_stream_station_001:segment_0008_final"],
  durableStore: "database_source_of_truth",
};

const spouseEmotionalState: DurableEmotionalStateTimelineRecord = {
  stationRunId: "station_run_durable_actor_turn_001",
  actorId: "spouse_anna_hayes_v1",
  atSecond: 120,
  emotionalState: "anxious",
  sourceTurnId: "turn_001_spouse_anna_hayes_v1_120",
  durableStore: "database_source_of_truth",
};

const clinicalEventOrderRequested: DurableClinicalEventRecord = {
  clinicalEventId: "event_001_ecg_order",
  stationRunId: "station_run_durable_clinical_event_001",
  actorId: "nurse_maria_alvarez_v1",
  atSecond: 180,
  eventKind: "order_status_changed",
  traceTag: "ecg_request",
  label: "12-lead ECG",
  status: "requested",
  payload: {
    public: {
      orderId: "order_1_ecg_request",
      requestedOrder: "12-lead ECG",
    },
    private: {
      hiddenFactRefs: ["fact:patient_robert_hayes_v1:1"],
      serverOnlyNotes: ["Recent cocaine use remains hidden until elicited."],
    },
  },
  provenanceRefs: ["trace:station_run_durable_clinical_event_001:180"],
  durableStore: "database_source_of_truth",
};

const clinicalEventFinding: DurableClinicalEventRecord = {
  clinicalEventId: "event_002_diaphoresis",
  stationRunId: "station_run_durable_clinical_event_001",
  actorId: "patient_robert_hayes_v1",
  atSecond: 190,
  eventKind: "finding_recorded",
  traceTag: "physical_exam_general",
  label: "Patient appears diaphoretic",
  payload: {
    public: {
      findingId: "finding_1_diaphoretic",
      observed: true,
    },
  },
  provenanceRefs: ["trace:station_run_durable_clinical_event_001:190"],
  durableStore: "database_source_of_truth",
};

function clinicalEventForStationRun(
  record: DurableClinicalEventRecord,
  stationRunId: string,
  overrides: Partial<DurableClinicalEventRecord> = {},
): DurableClinicalEventRecord {
  const next = { ...record, ...overrides, stationRunId };
  return {
    ...next,
    provenanceRefs: next.provenanceRefs.map((ref) =>
      ref.startsWith("trace:")
        ? `trace:${stationRunId}:${next.atSecond}`
        : ref
    ),
  };
}

it("rejects durable clinical events with blank identity fields before Mongo upsert", async () => {
  const context = await createMongoMemoryTestContext();
  try {
    const repository = new MongoDurableClinicalEventRepository(context.db);
    await repository.ensureIndexes();

    await expect(repository.save({ ...clinicalEventOrderRequested, clinicalEventId: " " }))
      .rejects.toThrow("durable Mongo clinical-event records require nonblank clinicalEventId");
    await expect(repository.save({ ...clinicalEventOrderRequested, stationRunId: " " }))
      .rejects.toThrow("durable Mongo clinical-event records require nonblank stationRunId");
    await expect(repository.save({ ...clinicalEventOrderRequested, label: " " }))
      .rejects.toThrow("durable Mongo clinical-event records require nonblank label");
    await expect(repository.save({ ...clinicalEventOrderRequested, atSecond: Number.NaN }))
      .rejects.toThrow("durable Mongo clinical-event records require a nonnegative finite atSecond");
    await expect(repository.save({ ...clinicalEventOrderRequested, traceTag: " " }))
      .rejects.toThrow("durable Mongo clinical-event records require nonblank traceTag");
    await expect(repository.listByStationRunId(clinicalEventOrderRequested.stationRunId)).resolves.toEqual([]);
  } finally {
    await context.close();
  }
});

it("rejects durable actor-turn and emotional-state timeline records with blank identity fields before Mongo upsert", async () => {
  const context = await createMongoMemoryTestContext();
  try {
    const turns = new MongoDurableConversationTurnRepository(context.db);
    const emotionalStates = new MongoDurableEmotionalStateTimelineRepository(context.db);
    await Promise.all([turns.ensureIndexes(), emotionalStates.ensureIndexes()]);

    await expect(turns.save({ ...spouseConversationTurn, turnId: " " }))
      .rejects.toThrow("durable Mongo records require nonblank turnId");
    await expect(turns.save({ ...spouseConversationTurn, stationRunId: " " }))
      .rejects.toThrow("durable Mongo records require nonblank stationRunId");
    await expect(turns.save({ ...spouseConversationTurn, actorId: " " }))
      .rejects.toThrow("durable Mongo records require nonblank actorId");
    await expect(turns.save({ ...spouseConversationTurn, text: " " }))
      .rejects.toThrow("durable Mongo records require nonblank text");
    await expect(turns.save({ ...spouseConversationTurn, atSecond: Number.POSITIVE_INFINITY }))
      .rejects.toThrow("durable Mongo conversation turns require a nonnegative finite atSecond");
    await expect(turns.save({ ...spouseConversationTurn, traceContextTags: ["history_onset", " "] }))
      .rejects.toThrow("durable Mongo records require traceContextTags to contain only nonblank strings");
    await expect(turns.listByStationRunId(spouseConversationTurn.stationRunId)).resolves.toEqual([]);

    await expect(emotionalStates.save({ ...spouseEmotionalState, actorId: " " }))
      .rejects.toThrow("durable Mongo records require nonblank actorId");
    await expect(emotionalStates.save({ ...spouseEmotionalState, sourceTurnId: " " }))
      .rejects.toThrow("durable Mongo records require nonblank sourceTurnId");
    await expect(emotionalStates.save({ ...spouseEmotionalState, atSecond: Number.NaN }))
      .rejects.toThrow("durable Mongo emotional-state timeline records require a nonnegative finite atSecond");
    await expect(
      emotionalStates.listByStationRunIdAndActorId(spouseEmotionalState.stationRunId, spouseEmotionalState.actorId),
    ).resolves.toEqual([]);
  } finally {
    await context.close();
  }
});

function planUsesIndex(plan: Document, indexName: string): boolean {
  return visitPlan(plan, (node) => node.indexName === indexName);
}

function planHasStage(plan: Document, stage: string): boolean {
  return visitPlan(plan, (node) => node.stage === stage);
}

function winningPlanFromExplain(explain: Document): Document {
  const winningPlan = explain.queryPlanner?.winningPlan;
  if (!winningPlan || typeof winningPlan !== "object") {
    throw new Error("Expected MongoDB explain output to include queryPlanner.winningPlan");
  }
  return winningPlan as Document;
}

function visitPlan(value: unknown, predicate: (node: Record<string, unknown>) => boolean): boolean {
  if (Array.isArray(value)) {
    return value.some((child) => visitPlan(child, predicate));
  }
  if (!value || typeof value !== "object") {
    return false;
  }
  const node = value as Record<string, unknown>;
  return predicate(node) || Object.values(node).some((child) => visitPlan(child, predicate));
}

const seedQueueScenarios: Scenario[] = Array.from({ length: 12 }, (_, index) => {
  const stationOrder = index + 1;
  const scenarioId = stationOrder === 9
    ? "clinic_abdominal_pain_interpreter_v1"
    : `seed_station_${String(stationOrder).padStart(2, "0")}_v1`;

  return {
    ...scenario,
    scenarioId,
    version: 1,
    title: stationOrder === 9 ? "Clinic abdominal pain with interpreter" : `Seed station ${stationOrder}`,
    status: stationOrder === 1 ? "approved" : "draft",
    review: stationOrder === 1
      ? scenario.review
      : {
        clinical: "draft",
        psychometric: "draft",
        legal: "draft",
        simulationQa: "draft",
      },
    requiredTraceTags: [`station_${stationOrder}_trace`],
    governance: {
      ...scenario.governance,
      safetyCriticalTraceTags: [`station_${stationOrder}_safety_trace`],
      validationStage: stationOrder === 1 ? "stage_1_expert_reviewed" : "stage_0_synthetic_draft",
    },
  };
});

describe("MongoDB memory repositories", () => {
  let context: MongoMemoryTestContext;

  beforeAll(async () => {
    context = await createMongoMemoryTestContext();
  }, 120_000);

  afterAll(async () => {
    await context?.close();
  });

  it("stores and retrieves versioned scenarios", async () => {
    const repository = new MongoScenarioRepository(context.db);
    await repository.ensureIndexes();
    await repository.save(scenario);

    await expect(repository.findByIdAndVersion("ed_chest_pain_priority_v1", 1)).resolves.toMatchObject({
      scenarioId: "ed_chest_pain_priority_v1",
      version: 1,
      status: "approved",
    });

    await expect(context.db.collection("scenarios").indexes()).resolves.toContainEqual(
      expect.objectContaining({
        key: { "governance.sourceIds": 1, status: 1 },
      }),
    );
    await expect(repository.approved()).resolves.toHaveLength(1);
  });

  it("rejects invalid scenarios before Mongo upsert", async () => {
    const repository = new MongoScenarioRepository(context.db);
    await repository.ensureIndexes();

    await expect(repository.save({
      ...scenario,
      scenarioId: "invalid_review_gate_scenario",
      review: { ...scenario.review, legal: "draft" },
    })).rejects.toThrow("Invalid scenario");
    await expect(repository.findByIdAndVersion("invalid_review_gate_scenario", scenario.version)).resolves.toBeNull();
  });

  it("enforces trace sequence uniqueness and replays in order", async () => {
    const repository = new MongoTraceRepository(context.db);
    await repository.ensureIndexes();
    const stationStarted = trace(0, "station_started");
    await repository.append(stationStarted);
    await repository.append(trace(1, "ecg_request"));

    expect("_id" in stationStarted).toBe(false);
    await expect(repository.append(trace(1, "duplicate_sequence"))).rejects.toThrow();
    await expect(repository.replay("run_001")).resolves.toEqual([expect.objectContaining({ sequence: 0 }), expect.objectContaining({ sequence: 1 })]);
  });

  it("rejects invalid trace events before Mongo insert or replay upsert", async () => {
    const repository = new MongoTraceRepository(context.db);
    await repository.ensureIndexes();
    const invalidTrace = { ...trace(0, "invalid_trace_identity", "run_invalid_trace"), source: " " };

    await expect(repository.append(invalidTrace)).rejects.toThrow("Invalid trace event");
    await expect(repository.upsertMany([invalidTrace])).rejects.toThrow("Invalid trace event");
    await expect(repository.replay("run_invalid_trace")).resolves.toEqual([]);
  });

  it("upserts replay snapshots idempotently and reports the latest sequence", async () => {
    const repository = new MongoTraceRepository(context.db);
    await repository.ensureIndexes();

    await repository.upsertMany([trace(10, "station_started", "run_snapshot"), trace(11, "history_opqrst", "run_snapshot")]);
    await repository.upsertMany([trace(10, "station_started", "run_snapshot"), trace(11, "history_opqrst", "run_snapshot"), trace(12, "ecg_request", "run_snapshot")]);

    await expect(repository.replay("run_snapshot")).resolves.toEqual([
      expect.objectContaining({ sequence: 10 }),
      expect.objectContaining({ sequence: 11 }),
      expect.objectContaining({ sequence: 12 }),
    ]);
    await expect(repository.latestSequence("run_snapshot")).resolves.toBe(12);
    await expect(repository.latestSequence("missing_run")).resolves.toBeNull();
  });

  it("stores and retrieves review packets with trace quality evidence", async () => {
    const repository = new MongoReviewPacketRepository(context.db);
    await repository.ensureIndexes();
    await repository.save(reviewPacket);

    await expect(repository.findByStationRunId("run_001")).resolves.toMatchObject({
      stationRunId: "run_001",
      scenarioId: "ed_chest_pain_priority_v1",
      traceQuality: {
        modelGeneratedEventCount: 1,
        hasModelProvenance: true,
      },
      patientNote: {
        text: "Concern for ACS. ECG requested.",
      },
    });

    await expect(context.db.collection("review_packets").indexes()).resolves.toContainEqual(
      expect.objectContaining({
        key: { "facultyScoreDraft.status": 1, scenarioId: 1 },
      }),
    );
    await expect(repository.listByScenario("ed_chest_pain_priority_v1")).resolves.toHaveLength(1);
  });

  it("rejects invalid review packets before Mongo upsert", async () => {
    const repository = new MongoReviewPacketRepository(context.db);
    await repository.ensureIndexes();

    await expect(repository.save({
      ...reviewPacket,
      stationRunId: "run_invalid_review_packet",
      traceQuality: {
        ...reviewPacket.traceQuality,
        eventCount: reviewPacket.timeline.length + 1,
      },
    })).rejects.toThrow("Invalid review packet");
    await expect(repository.findByStationRunId("run_invalid_review_packet")).resolves.toBeNull();
  });

  it("stores scenario review decisions in replay order for API startup reconstruction", async () => {
    const repository = new MongoScenarioReviewDecisionRepository(context.db);
    await repository.ensureIndexes();

    await repository.save({
      ...scenarioReviewDecision,
      reviewerRole: "legal",
      reviewerId: "legal_001",
      reviewedAt: "2026-05-04T11:00:00.000Z",
    });
    await repository.save(scenarioReviewDecision);
    const tiedReviewedAt = "2026-05-04T12:00:00.000Z";
    await repository.save({
      ...scenarioReviewDecision,
      version: 2,
      reviewerId: "clinical_002",
      reviewedAt: tiedReviewedAt,
    });
    await repository.save({
      ...scenarioReviewDecision,
      reviewerRole: "legal",
      reviewerId: "legal_001",
      reviewedAt: tiedReviewedAt,
    });
    await repository.save({
      ...scenarioReviewDecision,
      reviewerId: "clinical_001",
      reviewedAt: tiedReviewedAt,
    });

    await expect(repository.list()).resolves.toEqual([
      expect.objectContaining({
        scenarioId: "peds_asthma_parent_anxiety_v1",
        reviewerRole: "clinical",
        evidenceRefs: ["evidence:peds:clinical:2026-05-04"],
      }),
      expect.objectContaining({
        reviewerRole: "legal",
        reviewerId: "legal_001",
      }),
      expect.objectContaining({
        version: 1,
        reviewerRole: "clinical",
        reviewerId: "clinical_001",
      }),
      expect.objectContaining({
        version: 1,
        reviewerRole: "legal",
        reviewerId: "legal_001",
      }),
      expect.objectContaining({
        version: 2,
        reviewerRole: "clinical",
        reviewerId: "clinical_002",
      }),
    ]);
  });

  it("rejects invalid scenario review decisions before Mongo upsert", async () => {
    const repository = new MongoScenarioReviewDecisionRepository(context.db);
    await repository.ensureIndexes();

    await expect(repository.save({
      ...scenarioReviewDecision,
      scenarioId: "invalid_review_decision_scenario",
      reviewerId: " ",
    })).rejects.toThrow("Invalid scenario review decision");
    await expect(repository.list()).resolves.not.toEqual(
      expect.arrayContaining([
        expect.objectContaining({ scenarioId: "invalid_review_decision_scenario" }),
      ]),
    );
  });

  it("stores exam forms with locked scenario versions for drift review", async () => {
    const repository = new MongoExamFormRepository(context.db);
    await repository.ensureIndexes();
    const form = assembleExamForm({
      examFormId: "form_openclinxr_pilot_001",
      blueprint: createDefaultClinicalSkillsBlueprint(),
      scenarios: [scenario],
    });

    await repository.save(form);

    await expect(repository.findById("form_openclinxr_pilot_001")).resolves.toMatchObject({
      examFormId: "form_openclinxr_pilot_001",
      blueprintId: "blueprint_openclinxr_clinical_skills_pilot_v1",
      stationRefs: [
        {
          scenarioId: "ed_chest_pain_priority_v1",
          scenarioVersion: 1,
        },
      ],
    });
    await expect(repository.listByBlueprint("blueprint_openclinxr_clinical_skills_pilot_v1")).resolves.toHaveLength(1);
  });

  it("stores station run queue snapshots for reviewer launch gating", async () => {
    const repository = new MongoStationRunQueueRepository(context.db);
    await repository.ensureIndexes();
    const blueprint = createStep2CsStyleSeedBlueprint(seedQueueScenarios);
    const queue = createExamStationRunQueue(blueprint, seedQueueScenarios);

    await repository.save({
      snapshotId: "queue_snapshot_seed_001",
      createdAt: "2026-05-03T16:00:00.000Z",
      reviewerId: "psychometrician_001",
      queue,
    });

    await expect(repository.findById("queue_snapshot_seed_001")).resolves.toMatchObject({
      snapshotId: "queue_snapshot_seed_001",
      reviewerId: "psychometrician_001",
      queue: {
        blueprintId: "blueprint_openclinxr_step2cs_style_seed_v1",
        canStartLearnerExam: false,
          summary: {
            activationReady: 0,
            draftBlocked: 11,
            governanceBlocked: 1,
            missingScenario: 0,
          },
        stationQueue: expect.arrayContaining([
          expect.objectContaining({
            stationOrder: 9,
            scenarioId: "clinic_abdominal_pain_interpreter_v1",
            status: "draft_blocked",
            blockers: ["scenario_not_approved"],
          }),
        ]),
      },
    });
    await expect(repository.listByBlueprint("blueprint_openclinxr_step2cs_style_seed_v1")).resolves.toEqual([
      expect.objectContaining({
        snapshotId: "queue_snapshot_seed_001",
        queue: expect.objectContaining({
          totalStationTimeSeconds: 18720,
        }),
      }),
    ]);
  });

  it("persists API snapshots through a Mongo-backed sink", async () => {
    const sink = createMongoApiPersistenceSink(context.db);
    await sink.ensureIndexes();
    const form = assembleExamForm({
      examFormId: "form_sink_001",
      blueprint: createDefaultClinicalSkillsBlueprint(),
      scenarios: [scenario],
    });

    await sink.saveExamForm(form);
    await sink.saveTraceEvents("run_sink", [trace(0, "station_started", "run_sink"), trace(1, "ecg_request", "run_sink")]);
    await sink.saveTraceEvents("run_sink", [trace(0, "station_started", "run_sink"), trace(1, "ecg_request", "run_sink"), trace(2, "team_communication", "run_sink")]);
    await sink.saveReviewPacket("run_sink", {
      ...reviewPacket,
      stationRunId: "run_sink",
      patientNote: { ...reviewPacket.patientNote!, stationRunId: "run_sink" },
    });
    await sink.saveScenarioReviewDecision(scenarioReviewDecision);
    await sink.saveStationRunQueueSnapshot({
      snapshotId: "queue_snapshot_sink_001",
      createdAt: "2026-05-03T16:45:00.000Z",
      queue: createExamStationRunQueue(createStep2CsStyleSeedBlueprint(seedQueueScenarios), seedQueueScenarios),
    });

    await expect(new MongoExamFormRepository(context.db).findById("form_sink_001")).resolves.toMatchObject({
      examFormId: "form_sink_001",
    });
    await expect(new MongoTraceRepository(context.db).replay("run_sink")).resolves.toHaveLength(3);
    await expect(new MongoReviewPacketRepository(context.db).findByStationRunId("run_sink")).resolves.toMatchObject({
      stationRunId: "run_sink",
    });
    await expect(new MongoScenarioReviewDecisionRepository(context.db).list()).resolves.toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          scenarioId: "peds_asthma_parent_anxiety_v1",
          reviewerRole: "clinical",
        }),
      ]),
    );
    await expect(new MongoStationRunQueueRepository(context.db).findById("queue_snapshot_sink_001")).resolves.toMatchObject({
      snapshotId: "queue_snapshot_sink_001",
      queue: {
        summary: { activationReady: 0, draftBlocked: 11 },
      },
    });
    await expect(sink.listStationRunQueueSnapshots("blueprint_openclinxr_step2cs_style_seed_v1")).resolves.toEqual(
      expect.arrayContaining([expect.objectContaining({ snapshotId: "queue_snapshot_sink_001" })]),
    );
    await expect(sink.listScenarioReviewDecisions()).resolves.toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          reviewerId: "pediatrician_001",
          evidenceRefs: ["evidence:peds:clinical:2026-05-04"],
        }),
      ]),
    );
  });

  it("persists learner-safe runtime asset bundles through repository and API sink", async () => {
    const bundle = {
      ...createEdChestPainLocalLearnerRuntimeAssetBundle(),
      bundleId: "mongo_ed_chest_pain_runtime_bundle_001",
    };
    const repository = new MongoRuntimeAssetBundleRepository(context.db);
    await repository.ensureIndexes();
    await repository.saveLearnerBundle(bundle);

    await expect(repository.findLearnerBundleById(bundle.bundleId)).resolves.toMatchObject({
      bundleId: "mongo_ed_chest_pain_runtime_bundle_001",
      identityScope: "learner_runtime_opaque_bundle",
    });

    const sink = createMongoApiPersistenceSink(context.db);
    await sink.ensureIndexes();
    await sink.saveLearnerRuntimeAssetBundle({
      ...bundle,
      bundleId: "mongo_ed_chest_pain_runtime_bundle_002",
    });

    await expect(sink.getLearnerRuntimeAssetBundle("mongo_ed_chest_pain_runtime_bundle_002")).resolves.toMatchObject({
      bundleId: "mongo_ed_chest_pain_runtime_bundle_002",
      identityScope: "learner_runtime_opaque_bundle",
    });
    await expect(sink.listLearnerRuntimeAssetBundles()).resolves.toEqual(
      expect.arrayContaining([
        expect.objectContaining({ bundleId: "mongo_ed_chest_pain_runtime_bundle_001" }),
        expect.objectContaining({ bundleId: "mongo_ed_chest_pain_runtime_bundle_002" }),
      ]),
    );
  });

  it("rejects learner runtime asset bundles that expose identity fields", async () => {
    const repository = new MongoRuntimeAssetBundleRepository(context.db);
    await repository.ensureIndexes();
    const unsafeBundle = {
      ...createEdChestPainLocalLearnerRuntimeAssetBundle(),
      bundleId: "unsafe_runtime_bundle_identity_leak",
      tenantId: "tenant_001",
    };

    await expect(repository.saveLearnerBundle(unsafeBundle)).rejects.toThrow("must not expose identity fields");
  });

  it("publishes the learner-safe bundle from a generated station report", async () => {
    const bundle = {
      ...createEdChestPainLocalLearnerRuntimeAssetBundle(),
      bundleId: "generated_report_learner_runtime_bundle_001",
    };
    const repository = new MongoRuntimeAssetBundleRepository(context.db);
    await repository.ensureIndexes();

    await expect(saveLearnerRuntimeAssetBundleFromGeneratedReport(repository, {
      schemaVersion: "openclinxr.generated-ed-station-runtime-bundle.v1",
      status: "bundle_ready",
      learnerBundle: bundle,
    })).resolves.toMatchObject({
      bundleId: "generated_report_learner_runtime_bundle_001",
      identityScope: "learner_runtime_opaque_bundle",
    });
    await expect(repository.findLearnerBundleById("generated_report_learner_runtime_bundle_001")).resolves.toMatchObject({
      bundleId: "generated_report_learner_runtime_bundle_001",
    });
  });

  it("does not publish blocked generated station reports", async () => {
    const repository = new MongoRuntimeAssetBundleRepository(context.db);
    await repository.ensureIndexes();

    await expect(saveLearnerRuntimeAssetBundleFromGeneratedReport(repository, {
      schemaVersion: "openclinxr.generated-ed-station-runtime-bundle.v1",
      status: "blocked",
      learnerBundle: createEdChestPainLocalLearnerRuntimeAssetBundle(),
    })).rejects.toThrow("not bundle_ready");
  });

  it("does not publish full generated station reports before local runtime asset promotion passes", async () => {
    const repository = new MongoRuntimeAssetBundleRepository(context.db);
    await repository.ensureIndexes();

    await expect(saveLearnerRuntimeAssetBundleFromGeneratedReport(repository, {
      schemaVersion: "openclinxr.generated-ed-station-runtime-bundle.v1",
      status: "bundle_ready",
      bundle: createEdChestPainLocalEncounterRuntimeAssetBundle(),
      learnerBundle: createEdChestPainLocalLearnerRuntimeAssetBundle(),
      runtimeAssetReviewDecisions: [],
    })).rejects.toThrow("did not pass local runtime promotion");
  });

  it("publishes full generated station reports after local runtime asset promotion passes", async () => {
    const repository = new MongoRuntimeAssetBundleRepository(context.db);
    await repository.ensureIndexes();
    const bundle = localRuntimeReviewApprovedBundle();
    const learnerBundle = toLearnerRuntimeAssetBundle(bundle);

    await expect(saveLearnerRuntimeAssetBundleFromGeneratedReport(repository, {
      schemaVersion: "openclinxr.generated-ed-station-runtime-bundle.v1",
      status: "bundle_ready",
      bundle,
      learnerBundle,
      runtimeAssetReviewDecisions: runtimeAssetReviewDecisionsForBundle(bundle),
    })).resolves.toMatchObject({
      bundleId: learnerBundle.bundleId,
      identityScope: "learner_runtime_opaque_bundle",
    });
    await expect(repository.findLearnerBundleById(learnerBundle.bundleId)).resolves.toMatchObject({
      bundleId: learnerBundle.bundleId,
      identityScope: "learner_runtime_opaque_bundle",
    });
  });

  it("rejects API sink review packets whose path station run does not match the packet", async () => {
    const sink = createMongoApiPersistenceSink(context.db);
    await sink.ensureIndexes();

    await expect(sink.saveReviewPacket("run_sink_path", {
      ...reviewPacket,
      stationRunId: "run_sink_packet",
      patientNote: { ...reviewPacket.patientNote!, stationRunId: "run_sink_packet" },
    })).rejects.toThrow("Review packet stationRunId must match sink stationRunId");
    await expect(new MongoReviewPacketRepository(context.db).findByStationRunId("run_sink_packet")).resolves.toBeNull();
  });

  it("rejects API sink trace events whose station run does not match the path", async () => {
    const sink = createMongoApiPersistenceSink(context.db);
    await sink.ensureIndexes();

    await expect(sink.saveTraceEvents("run_trace_path", [trace(0, "station_started", "run_trace_packet")]))
      .rejects.toThrow("Trace event stationRunId must match sink stationRunId");
    await expect(new MongoTraceRepository(context.db).replay("run_trace_packet")).resolves.toEqual([]);
  });

  it("exposes durable multi-actor session methods through the Mongo API persistence sink without runtime wiring", async () => {
    const sink: AsyncDurableMultiActorSessionStore = createMongoApiPersistenceSink(context.db);
    await sink.ensureIndexes?.();
    const stationRunId = "station_run_api_sink_durable_multi_actor_001";

    await sink.saveConversationTurn({
      ...spouseConversationTurn,
      stationRunId,
    });
    await sink.saveEmotionalStateTimeline({
      ...spouseEmotionalState,
      stationRunId,
    });
    await sink.saveClinicalEvent({
      ...clinicalEventForStationRun(clinicalEventOrderRequested, stationRunId),
    });

    await expect(sink.listConversationTurns(stationRunId)).resolves.toEqual([
      {
        ...spouseConversationTurn,
        stationRunId,
      },
    ]);
    await expect(sink.listEmotionalStateTimeline(stationRunId, "spouse_anna_hayes_v1")).resolves.toEqual([
      {
        ...spouseEmotionalState,
        stationRunId,
      },
    ]);
    await expect(sink.listClinicalEvents(stationRunId)).resolves.toEqual([
      {
        ...clinicalEventForStationRun(clinicalEventOrderRequested, stationRunId),
      },
    ]);
    await expect(sink.listClinicalEventReviewProjections(stationRunId)).resolves.toEqual([
      expect.objectContaining({
        clinicalEventId: "event_001_ecg_order",
        stationRunId,
        payload: {
          orderId: "order_1_ecg_request",
          requestedOrder: "12-lead ECG",
        },
        privatePayloadRedacted: true,
        durableStore: "database_source_of_truth",
      }),
    ]);
    expect(JSON.stringify(await sink.listClinicalEventReviewProjections(stationRunId))).not.toContain("Recent cocaine use");
  });

  it("stores durable conversation turns in replay order without persisting raw voice audio or mutating duplicate turns", async () => {
    const repository = new MongoDurableConversationTurnRepository(context.db);
    await repository.ensureIndexes();

    await repository.save(nurseConversationTurn);
    await repository.save(spouseConversationTurn);
    await repository.save({
      ...spouseConversationTurn,
      text: "Anna, did the pain start before dinner or after dinner?",
      provenanceRefs: [
        ...spouseConversationTurn.provenanceRefs,
        "trace:voice_stream_station_001:segment_0008_corrected",
      ],
    });

    await expect(repository.listByStationRunId("station_run_durable_actor_turn_001")).resolves.toEqual([
      spouseConversationTurn,
      nurseConversationTurn,
    ]);
  });

  it("stores durable emotional-state timeline records in actor replay order without mutating duplicate source turns", async () => {
    const repository = new MongoDurableEmotionalStateTimelineRepository(context.db);
    await repository.ensureIndexes();

    await repository.save({
      ...spouseEmotionalState,
      sourceTurnId: "turn_002_spouse_anna_hayes_v1_300",
      atSecond: 300,
      emotionalState: "reassured",
    });
    await repository.save(spouseEmotionalState);
    await repository.save({
      ...spouseEmotionalState,
      emotionalState: "very anxious",
    });
    await repository.save({
      stationRunId: spouseEmotionalState.stationRunId,
      actorId: "nurse_maria_alvarez_v1",
      atSecond: 180,
      emotionalState: "focused",
      sourceTurnId: "turn_002_nurse_maria_alvarez_v1_180",
      durableStore: "database_source_of_truth",
    });

    await expect(repository.listByStationRunIdAndActorId(
      "station_run_durable_actor_turn_001",
      "spouse_anna_hayes_v1",
    )).resolves.toEqual([
      spouseEmotionalState,
      {
        ...spouseEmotionalState,
        sourceTurnId: "turn_002_spouse_anna_hayes_v1_300",
        atSecond: 300,
        emotionalState: "reassured",
      },
    ]);
  });

  it("creates a Mongo durable multi-actor session store with database-only actor-turn scope", async () => {
    const store: AsyncDurableMultiActorSessionStore = createMongoDurableMultiActorSessionStore(context.db);
    await store.ensureIndexes?.();

    await store.saveConversationTurn({
      ...spouseConversationTurn,
      stationRunId: "station_run_durable_actor_turn_store_001",
    });
    await store.saveEmotionalStateTimeline({
      ...spouseEmotionalState,
      stationRunId: "station_run_durable_actor_turn_store_001",
    });

    await expect(store.listConversationTurns("station_run_durable_actor_turn_store_001")).resolves.toEqual([
      {
        ...spouseConversationTurn,
        stationRunId: "station_run_durable_actor_turn_store_001",
      },
    ]);
    await expect(store.listEmotionalStateTimeline(
      "station_run_durable_actor_turn_store_001",
      "spouse_anna_hayes_v1",
    )).resolves.toEqual([
      {
        ...spouseEmotionalState,
        stationRunId: "station_run_durable_actor_turn_store_001",
      },
    ]);
    expect(durableActorTurnPersistenceScope).toMatchObject({
      approvedProposal: "proposals/approved/proposal-durable-actor-turn-persistence-promotion.md",
      actorTurnScope: "conversation_turns_and_emotional_state_timeline_only",
      clinicalActionsIncluded: false,
      redisRedkaIncluded: false,
      databaseOnly: true,
    });
  });

  it("rejects Redis or Redka cache posture at durable actor-turn Mongo boundaries", async () => {
    const conversationTurns = new MongoDurableConversationTurnRepository(context.db);
    const emotionalStateTimeline = new MongoDurableEmotionalStateTimelineRepository(context.db);
    await Promise.all([
      conversationTurns.ensureIndexes(),
      emotionalStateTimeline.ensureIndexes(),
    ]);

    await expect(conversationTurns.save({
      ...spouseConversationTurn,
      turnId: "turn_invalid_cache_store",
      durableStore: "redis_redka_ephemeral_cache" as never,
    })).rejects.toThrow("durable Mongo records must use durableStore database_source_of_truth");
    await expect(emotionalStateTimeline.save({
      ...spouseEmotionalState,
      sourceTurnId: "turn_invalid_cache_store",
      durableStore: "redis_redka_ephemeral_cache" as never,
    })).rejects.toThrow("durable Mongo records must use durableStore database_source_of_truth");

    await expect(conversationTurns.listByStationRunId(spouseConversationTurn.stationRunId)).resolves.not.toEqual(
      expect.arrayContaining([
        expect.objectContaining({ turnId: "turn_invalid_cache_store" }),
      ]),
    );
  });

  it("stores durable clinical events in deterministic replay order with idempotent upsert", async () => {
    const repository = new MongoDurableClinicalEventRepository(context.db);
    await repository.ensureIndexes();

    const orderRequested: DurableClinicalEventRecord = {
      ...clinicalEventOrderRequested,
      clinicalEventId: "event_001_ecg_order_requested",
    };
    const orderCompleted: DurableClinicalEventRecord = {
      ...clinicalEventOrderRequested,
      clinicalEventId: "event_001_ecg_order_completed",
      atSecond: 205,
      status: "completed",
      payload: {
        public: {
          orderId: "order_1_ecg_request",
          requestedOrder: "12-lead ECG",
          resultSummary: "ST elevation present.",
        },
        ...(clinicalEventOrderRequested.payload.private
          ? { private: clinicalEventOrderRequested.payload.private }
          : {}),
      },
      provenanceRefs: [
        ...clinicalEventOrderRequested.provenanceRefs,
        "review:cardiology:ecg-overread",
      ],
    };
    const checklistUpdated: DurableClinicalEventRecord = {
      clinicalEventId: "event_003_checklist_airway",
      stationRunId: "station_run_durable_clinical_event_001",
      atSecond: 210,
      eventKind: "checklist_item_updated",
      label: "Airway and breathing assessed",
      status: "completed",
      payload: {
        public: {
          checklistItemId: "primary_survey_airway_breathing",
          checked: true,
        },
      },
      provenanceRefs: ["trace:station_run_durable_clinical_event_001:210"],
      durableStore: "database_source_of_truth",
    };
    const rubricProgressUpdated: DurableClinicalEventRecord = {
      clinicalEventId: "event_004_rubric_acs",
      stationRunId: "station_run_durable_clinical_event_001",
      atSecond: 240,
      eventKind: "rubric_progress_updated",
      traceTag: "diagnostic_reasoning_acs",
      label: "ACS considered",
      status: "met",
      payload: {
        public: {
          rubricItemId: "diagnostic_reasoning_acs",
          scoreDraft: "met",
        },
      },
      provenanceRefs: ["trace:station_run_durable_clinical_event_001:240"],
      durableStore: "database_source_of_truth",
    };
    const caseStatusChanged: DurableClinicalEventRecord = {
      clinicalEventId: "event_005_case_escalation",
      stationRunId: "station_run_durable_clinical_event_001",
      atSecond: 300,
      eventKind: "case_status_changed",
      traceTag: "escalation_to_attending",
      label: "Case escalated to attending",
      status: "escalated",
      payload: {
        public: {
          casePhase: "escalated_care",
        },
      },
      provenanceRefs: ["trace:station_run_durable_clinical_event_001:300"],
      durableStore: "database_source_of_truth",
    };
    const clinicalActionRecorded: DurableClinicalEventRecord = {
      clinicalEventId: "event_006_clinical_action",
      stationRunId: "station_run_durable_clinical_event_001",
      actorId: "nurse_maria_alvarez_v1",
      atSecond: 320,
      eventKind: "clinical_action_recorded",
      traceTag: "team_communication",
      label: "Nurse repeats closed-loop instruction",
      status: "observed",
      payload: {
        public: {
          actionId: "closed_loop_communication_001",
          communicationPattern: "closed_loop",
        },
      },
      provenanceRefs: ["trace:station_run_durable_clinical_event_001:320"],
      durableStore: "database_source_of_truth",
    };

    await repository.save(clinicalEventFinding);
    await repository.save(orderRequested);
    await repository.save(orderRequested);
    await repository.save({
      ...orderRequested,
      status: "conflicting_duplicate_should_not_replace",
      payload: {
        public: {
          orderId: "order_1_ecg_request",
          requestedOrder: "12-lead ECG",
          resultSummary: "This conflicting duplicate must not replace the original event.",
        },
        ...(orderRequested.payload.private
          ? { private: orderRequested.payload.private }
          : {}),
      },
    });
    await repository.save(orderCompleted);
    await repository.save(checklistUpdated);
    await repository.save(rubricProgressUpdated);
    await repository.save(caseStatusChanged);
    await repository.save(clinicalActionRecorded);

    await expect(repository.listByStationRunId("station_run_durable_clinical_event_001")).resolves.toEqual([
      orderRequested,
      clinicalEventFinding,
      orderCompleted,
      checklistUpdated,
      rubricProgressUpdated,
      caseStatusChanged,
      clinicalActionRecorded,
    ]);
    expect(durableClinicalEventPersistenceScope).toMatchObject({
      approvedProposal: "proposals/approved/proposal-durable-clinical-event-persistence.md",
      eventScope: "clinical_actions_orders_findings_checklists_rubric_and_case_progress",
      idempotencyBehavior: "clinical_event_id_is_insert_once_status_history_uses_distinct_event_ids",
      actorTurnScopeChanged: false,
      redisRedkaIncluded: false,
      databaseOnly: true,
    });
  });

  it("keeps Mongo clinical-event idempotency insert-only while preserving same-second replay order", async () => {
    const repository = new MongoDurableClinicalEventRepository(context.db);
    await repository.ensureIndexes();
    const stationRunId = "station_run_durable_clinical_event_same_second_001";
    const orderRequested = clinicalEventForStationRun(clinicalEventOrderRequested, stationRunId, {
      clinicalEventId: "event_a_order_requested",
      atSecond: 200,
    });
    const findingRecorded = clinicalEventForStationRun(clinicalEventFinding, stationRunId, {
      clinicalEventId: "event_b_finding_recorded",
      atSecond: 200,
    });

    await repository.save(findingRecorded);
    await repository.save(orderRequested);
    await repository.save({
      ...orderRequested,
      status: "conflicting_duplicate_should_not_replace",
      payload: {
        public: {
          orderId: "order_1_ecg_request",
          requestedOrder: "12-lead ECG",
          resultSummary: "This conflicting duplicate must not replace the original event.",
        },
        ...(orderRequested.payload.private
          ? { private: orderRequested.payload.private }
          : {}),
      },
    });

    await expect(repository.listByStationRunId(stationRunId)).resolves.toEqual([
      orderRequested,
      findingRecorded,
    ]);
  });

  it("rejects Redis or Redka cache posture at durable clinical-event Mongo boundaries", async () => {
    const repository = new MongoDurableClinicalEventRepository(context.db);
    await repository.ensureIndexes();

    await expect(repository.save({
      ...clinicalEventOrderRequested,
      clinicalEventId: "event_invalid_cache_store",
      durableStore: "redis_redka_ephemeral_cache" as never,
    })).rejects.toThrow("durable Mongo records must use durableStore database_source_of_truth");

    await expect(repository.listByStationRunId(clinicalEventOrderRequested.stationRunId)).resolves.not.toEqual(
      expect.arrayContaining([
        expect.objectContaining({ clinicalEventId: "event_invalid_cache_store" }),
      ]),
    );
  });

  it("rejects durable clinical events whose trace provenance refs point at another station run before Mongo persistence", async () => {
    const repository = new MongoDurableClinicalEventRepository(context.db);
    await repository.ensureIndexes();
    const stationRunId = "station_run_durable_clinical_event_mongo_provenance_001";
    const validEvent = {
      ...clinicalEventOrderRequested,
      stationRunId,
      clinicalEventId: "event_valid_same_run_trace_provenance",
      provenanceRefs: [
        `trace:${stationRunId}:180`,
        "review:cardiology:ecg-overread",
      ],
    };
    const invalidEvent = {
      ...validEvent,
      clinicalEventId: "event_invalid_cross_run_trace_provenance",
      provenanceRefs: [
        "trace:station_run_other:180",
        "review:cardiology:ecg-overread",
      ],
    };

    await expect(repository.save(validEvent)).resolves.toBeUndefined();
    await expect(repository.save(invalidEvent))
      .rejects.toThrow("durable Mongo clinical-event provenanceRefs trace ref trace:station_run_other:180 must match stationRunId station_run_durable_clinical_event_mongo_provenance_001");
    await expect(repository.listByStationRunId(stationRunId)).resolves.toEqual([validEvent]);
    await expect(repository.listReviewProjectionsByStationRunId(stationRunId)).resolves.toEqual([
      expect.objectContaining({
        clinicalEventId: "event_valid_same_run_trace_provenance",
        provenanceRefs: validEvent.provenanceRefs,
      }),
    ]);
  });

  it("rejects durable clinical events with malformed trace provenance refs before Mongo persistence", async () => {
    const repository = new MongoDurableClinicalEventRepository(context.db);
    await repository.ensureIndexes();
    const stationRunId = "station_run_durable_clinical_event_mongo_malformed_provenance_001";
    const invalidEvent = {
      ...clinicalEventForStationRun(clinicalEventOrderRequested, stationRunId),
      clinicalEventId: "event_invalid_malformed_trace_provenance",
      provenanceRefs: [`trace:${stationRunId}`],
    };

    await expect(repository.save(invalidEvent))
      .rejects.toThrow(`durable Mongo clinical-event provenanceRefs trace ref trace:${stationRunId} must include stationRunId and sequence`);
    await expect(repository.listByStationRunId(stationRunId)).resolves.toEqual([]);
  });

  it("keeps durable clinical-event replay and review queries on indexed sort paths", async () => {
    const repository = new MongoDurableClinicalEventRepository(context.db);
    await repository.ensureIndexes();

    await repository.save({
      ...clinicalEventForStationRun(clinicalEventOrderRequested, "station_run_clinical_event_index_001"),
      clinicalEventId: "event_001_order_requested",
    });
    await repository.save({
      ...clinicalEventForStationRun(clinicalEventFinding, "station_run_clinical_event_index_001"),
      clinicalEventId: "event_002_finding",
    });

    const indexes = await context.db.collection("durable_clinical_events").indexes();
    expect(indexes).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          key: { stationRunId: 1, clinicalEventId: 1 },
          unique: true,
        }),
        expect.objectContaining({
          key: { stationRunId: 1, atSecond: 1, clinicalEventId: 1 },
        }),
        expect.objectContaining({
          key: { stationRunId: 1, eventKind: 1, atSecond: 1 },
        }),
        expect.objectContaining({
          key: { stationRunId: 1, traceTag: 1, atSecond: 1 },
        }),
      ]),
    );

    const stationReplayPlan = winningPlanFromExplain(await context.db.collection("durable_clinical_events")
      .find({ stationRunId: "station_run_clinical_event_index_001" }, { projection: { _id: 0 } })
      .sort({ atSecond: 1, clinicalEventId: 1 })
      .explain("queryPlanner"));
    expect(planUsesIndex(stationReplayPlan, "stationRunId_1_atSecond_1_clinicalEventId_1")).toBe(true);
    expect(planHasStage(stationReplayPlan, "SORT")).toBe(false);

    const kindReviewPlan = winningPlanFromExplain(await context.db.collection("durable_clinical_events")
      .find(
        { stationRunId: "station_run_clinical_event_index_001", eventKind: "order_status_changed" },
        { projection: { _id: 0 } },
      )
      .sort({ atSecond: 1 })
      .explain("queryPlanner"));
    expect(planUsesIndex(kindReviewPlan, "stationRunId_1_eventKind_1_atSecond_1")).toBe(true);
    expect(planHasStage(kindReviewPlan, "SORT")).toBe(false);
  });

  it("returns redacted durable clinical-event review projections from Mongo replay", async () => {
    const repository = new MongoDurableClinicalEventRepository(context.db);
    await repository.ensureIndexes();

    await repository.save({
      ...clinicalEventForStationRun(clinicalEventOrderRequested, "station_run_durable_clinical_event_projection_001"),
      payload: {
        public: {
          orderId: "order_1_ecg_request",
          requestedOrder: "12-lead ECG",
          hiddenFactRefs: ["fact:patient_robert_hayes_v1:1"],
          nested: {
            displayHint: "show ECG result after completion",
            serverOnlyNotes: ["Do not show this reviewer projection."],
          },
        },
        private: {
          hiddenFactRefs: ["fact:patient_robert_hayes_v1:1"],
          serverOnlyNotes: ["Recent cocaine use remains hidden until elicited."],
        },
      },
    });

    await expect(repository.listReviewProjectionsByStationRunId("station_run_durable_clinical_event_projection_001"))
      .resolves.toEqual([
        expect.objectContaining({
          clinicalEventId: "event_001_ecg_order",
          stationRunId: "station_run_durable_clinical_event_projection_001",
          payload: {
            orderId: "order_1_ecg_request",
            requestedOrder: "12-lead ECG",
            nested: {
              displayHint: "show ECG result after completion",
            },
          },
          privatePayloadRedacted: true,
          durableStore: "database_source_of_truth",
        }),
      ]);
  });

  it("adds clinical-event methods to the Mongo durable multi-actor session store without overloading actor turns", async () => {
    const store: AsyncDurableMultiActorSessionStore = createMongoDurableMultiActorSessionStore(context.db);
    await store.ensureIndexes?.();

    await store.saveClinicalEvent({
      ...clinicalEventForStationRun(clinicalEventOrderRequested, "station_run_durable_clinical_event_store_001"),
    });

    await expect(store.listClinicalEvents("station_run_durable_clinical_event_store_001")).resolves.toEqual([
      {
        ...clinicalEventForStationRun(clinicalEventOrderRequested, "station_run_durable_clinical_event_store_001"),
      },
    ]);
    await expect(store.listClinicalEventReviewProjections("station_run_durable_clinical_event_store_001"))
      .resolves.toEqual([
        expect.objectContaining({
          clinicalEventId: "event_001_ecg_order",
          stationRunId: "station_run_durable_clinical_event_store_001",
          payload: {
            orderId: "order_1_ecg_request",
            requestedOrder: "12-lead ECG",
          },
          privatePayloadRedacted: true,
          durableStore: "database_source_of_truth",
        }),
      ]);
    const reviewProjectionJson = JSON.stringify(
      await store.listClinicalEventReviewProjections("station_run_durable_clinical_event_store_001"),
    );
    expect(reviewProjectionJson).not.toContain("Recent cocaine use");
    expect(reviewProjectionJson).not.toContain("hiddenFactRefs");
    await expect(store.listConversationTurns("station_run_durable_clinical_event_store_001")).resolves.toEqual([]);
  });
});

function localRuntimeReviewApprovedBundle(): EncounterRuntimeAssetBundle {
  const bundle = createEdChestPainLocalEncounterRuntimeAssetBundle();
  const approve = (asset: EncounterRuntimeAsset): EncounterRuntimeAsset => ({
    ...asset,
    reviewStatus: "approved_for_local_runtime",
  });
  return {
    ...bundle,
    environment: approve(bundle.environment),
    actors: bundle.actors.map((actor) => ({
      ...actor,
      model: approve(actor.model),
      animationClips: actor.animationClips.map(approve),
      phonemeMap: actor.phonemeMap ? approve(actor.phonemeMap) : undefined,
    })),
    equipment: bundle.equipment.map((equipment) => ({
      ...equipment,
      model: approve(equipment.model),
    })),
    uiSurfaces: bundle.uiSurfaces.map((surface) => ({
      ...surface,
      schema: surface.schema ? approve(surface.schema) : undefined,
      data: surface.data ? approve(surface.data) : undefined,
    })),
  };
}

function runtimeAssetReviewDecisionsForBundle(bundle: EncounterRuntimeAssetBundle) {
  const assets = new Map<string, EncounterRuntimeAsset>();
  for (const asset of [
    bundle.environment,
    ...bundle.actors.flatMap((actor) => [actor.model, ...actor.animationClips, ...(actor.phonemeMap ? [actor.phonemeMap] : [])]),
    ...bundle.equipment.map((equipment) => equipment.model),
    ...bundle.uiSurfaces.flatMap((surface) => [surface.schema, surface.data].filter((asset): asset is EncounterRuntimeAsset => asset !== undefined)),
  ]) {
    assets.set(asset.assetId, asset);
  }
  return [...assets.keys()].flatMap((assetId) => [
    {
      assetId,
      reviewerRole: "asset_pipeline" as const,
      reviewerId: "asset_pipeline_reviewer",
      decision: "approved_for_local_runtime" as const,
      comments: "Local runtime asset evidence attached.",
      evidenceRefs: [`${assetId}:asset_pipeline`],
      reviewedAt: "2026-05-23T08:40:00.000Z",
    },
    {
      assetId,
      reviewerRole: "security_privacy" as const,
      reviewerId: "security_privacy_reviewer",
      decision: "approved_for_local_runtime" as const,
      comments: "Local runtime asset reference privacy evidence attached.",
      evidenceRefs: [`${assetId}:security_privacy`],
      reviewedAt: "2026-05-23T08:41:00.000Z",
    },
  ]);
}
