/**
 * Public interface of @openclinxr/xr-humanoid-animation.
 *
 * Named lists, not `export *`. A star republishes a module wholesale, so a symbol added inside
 * becomes public with nobody deciding it should be. Generated by `pnpm arch:narrow-entrypoint`
 * from what the tree actually consumes, then proved by `pnpm packages:typecheck:agent`.
 */
export type {
  GeneratedHumanoidAnimationSlot,
  HumanoidActingCueRecord,
  HumanoidAnimationRuntimeContext,
  HumanoidDialogueEmotionContext,
  HumanoidDialogueGazeTarget,
  HumanoidEmotionExpressionState,
  HumanoidExpressionEmotion,
  HumanoidExpressionWeights,
  HumanoidSpeechPlayback,
} from "./types.js";
export {
  applyHumanoidFaceRigControls,
  applyHumanoidMorphTargetCue,
  computeHumanoidEyeMotionMetrics,
  createHumanoidEmotionExpressionState,
  startHumanoidEmotionTransition,
  updateHumanoidEmotionExpression,
  visemeOpenness,
} from "./face-rig.js";
export {
  buildHumanoidSpeechEvidence,
  buildRuntimeActorRealismLaunchBadge,
  humanoidDialogueDurationMs,
  isGeneratedRuntimeDrive,
  orientHumanoidEyeFocusCue,
  orientHumanoidTowardGazeTarget,
  resolveHumanoidGazeTargetWorld,
} from "./gaze-evidence.js";
export {
  pediatricAsthmaActingOverlayForSlot,
  recordMouthGazePoseComparatorEvidence,
  updateGeneratedHumanoidAnimations,
  updateHumanoidSpeechCue,
} from "./animation-loop.js";
export {
  recordRuntimeHumanoidActingCueEvidence,
} from "./speech-evidence.js";
export type {
  MouthGazePoseComparatorEvidenceRecord,
  RuntimeHumanoidActingCueEvidenceRecord,
} from "./speech-evidence.js";
