/**
 * Public interface of @openclinxr/xr-humanoid-animation.
 *
 * Named lists, not `export *`. A star republishes a module wholesale, so a symbol added inside
 * becomes public with nobody deciding it should be. Generated by `pnpm arch:narrow-entrypoint`
 * from what the tree actually consumes, then proved by `pnpm packages:typecheck:agent`.
 */

export {
  updateGeneratedHumanoidAnimations,
} from "./animation-loop.js";
export {
  applyHumanoidMorphTargetCue,
  createHumanoidEmotionExpressionState,
  startHumanoidEmotionTransition,
  updateHumanoidEmotionExpression,
} from "./face-rig.js";
export {
  buildHumanoidSpeechEvidence,
  humanoidDialogueDurationMs,
  isGeneratedRuntimeDrive,
  orientHumanoidEyeFocusCue,
  orientHumanoidTowardGazeTarget,
  resolveHumanoidGazeTargetWorld,
} from "./gaze-evidence.js";
export type {
  MouthGazePoseComparatorEvidenceRecord,
  RuntimeHumanoidActingCueEvidenceRecord,
} from "./speech-evidence.js";
/**
 * Distance-indexed stop-take playback: start the root-removed take at the entry clip time
 * (distance-driven, never mixer-integrated), morph the walk/stop weights across the entry
 * crossfade, and manage stopping entry, crossfade, exits, and the settle-blend.
 */
export {
  blendStopClipPlayback,
  startStopClipPlayback,
  STOP_PLAYING_FLAG,
  updateStopPlayback,
} from "./stop-clip-playback-mod.js";
/** Walk-to-stop crossfade window in seconds: walk fades 1 to 0 while the stop fades 0 to 1. */
export {
  STOP_CROSSFADE_SECONDS,
} from "./stop-clip-wiring-mod.js";
/**
 * The slice of the case-owned approach the stop mixer touches. Narrower than the full
 * approach type, which the frozen surface review keeps off the public surface: tests
 * fabricate exactly this.
 */
export type {
  StopClipPlaybackState,
} from "./stop-clip-playback-mod.js";
export type {
  GeneratedHumanoidAnimationSlot,
  HumanoidActingCueRecord,
  HumanoidAnimationRuntimeContext,
  HumanoidDialogueEmotionContext,
  HumanoidDialogueGazeTarget,
  HumanoidEmotionExpressionState,
  HumanoidExpressionEmotion,
  HumanoidExpressionWeights,
  HumanoidSpeechPlayback,
} from "./types.js";
