/**
 * Public interface of @openclinxr/factory-stations.
 *
 * Named lists, not `export *`. A star republishes a module wholesale, so a symbol added inside
 * becomes public with nobody deciding it should be. Generated by `pnpm arch:narrow-entrypoint`
 * from what the tree actually consumes, then proved by `pnpm packages:typecheck:agent`.
 */
export {
  PRODUCTION_STATION_IDS,
  factoryStationSchemas,
  productionStationIds,
} from "./catalog.js";
export type {
  FactoryStationSchema,
  ProductionStationId,
  StandardIssue,
  StandardResult,
  StationJsonSchema,
  StationPropertySchema,
} from "./catalog.js";
export {
  equipmentGenerateRunner,
  planEquipmentGenerate,
  runEquipmentGenerate,
} from "./equipment_generate/run.js";
export {
  KNOWN_EQUIPMENT_SUBJECTS,
  findEquipmentSubject,
} from "./equipment_generate/subjects.js";
export {
  clothingConsumeRunner,
  planClothingConsume,
  runClothingConsume,
} from "./clothing_consume/run.js";
export {
  applyStationPayloadToCompileSpec,
} from "./apply-station-payload.js";
export {
  bodyParamRunner,
  planBodyParam,
  runBodyParam,
} from "./body_param/run.js";
export {
  ROOM_ALBEDO_REL,
  ROOM_OCCLUSION_REL,
  planRoomGenerate,
  roomGenerateRunner,
  runRoomGenerate,
} from "./room_generate/run.js";
export {
  motionRetargetRunner,
  planMotionRetarget,
  runMotionRetarget,
} from "./motion_retarget/run.js";
export {
  runStaging,
  stagingRunner,
} from "./staging/run.js";
export {
  lipSyncRunner,
  runLipSync,
} from "./lip_sync/run.js";
export type {
  LipSyncCue,
} from "./lip_sync/run.js";
export {
  writeLipSyncFixtureWav,
} from "./lip_sync/fixture-wav.js";
export {
  clothingGenerateRunner,
  runClothingGenerate,
} from "./clothing_generate/run.js";
export {
  dialogueRuntimeRunner,
  runDialogueRuntime,
} from "./dialogue_runtime/run.js";
export {
  LIGHTING_RIG_SCHEMA_VERSION,
  lightingDesignRunner,
} from "./lighting_design/run.js";
export type {
  LightingRig,
  RigLightType,
} from "./lighting_design/run.js";
// Reached only through a STRING KEY in the-station-runners-are-reachable-by-station-id.test.ts,
// so the name never appears as an identifier and the marker check read it as unused. This is the
// false negative recorded as clause (4) of unused-entrypoint-exports.test.ts, caught by the test
// that exists to catch it.
export {
  stationRunners,
} from "./station-runners.js";
