/**
 * Public interface of @openclinxr/factory-stations.
 *
 * Named lists, not `export *`. A star republishes a module wholesale, so a symbol added inside
 * becomes public with nobody deciding it should be. Generated by `pnpm arch:narrow-entrypoint`
 * from what the tree actually consumes, then proved by `pnpm packages:typecheck:agent`.
 */

export {
  applyStationPayloadToCompileSpec,
} from "./apply-station-payload.js";
export {
  planBodyParam,
  runBodyParam,
} from "./body_param/run.js";
export type {
  FactoryStationSchema,
  ProductionStationId,
  StandardIssue,
  StandardResult,
  StationJsonSchema,
  StationPropertySchema,
} from "./catalog-mod.js";
export {
  factoryStationSchemas,
  PRODUCTION_STATION_IDS,
  productionStationIds,
} from "./catalog-mod.js";
export {
  planClothingConsume,
  runClothingConsume,
} from "./clothing_consume/run.js";
export {
  runClothingGenerate,
} from "./clothing_generate/run.js";
export {
  runDialogueRuntime,
} from "./dialogue_runtime/run.js";
export {
  planEquipmentGenerate,
  runEquipmentGenerate,
} from "./equipment_generate/run.js";
export {
  findEquipmentSubject,
} from "./equipment_generate/subjects.js";
export {
  writeLipSyncFixtureWav,
} from "./lip_sync/fixture-wav.js";
export {
  runLipSync,
} from "./lip_sync/run.js";
export {
  planMotionRetarget,
  runMotionRetarget,
} from "./motion_retarget/run.js";
export {
  planRoomGenerate,
  ROOM_ALBEDO_REL,
  ROOM_OCCLUSION_REL,
  runRoomGenerate,
} from "./room_generate/run.js";
export {
  runStaging,
} from "./staging/run.js";
