/**
 * Public interface of @openclinxr/capability-gateway.
 *
 * Named lists, not `export *`. A star republishes a module wholesale, so a symbol added inside
 * becomes public with nobody deciding it should be. Generated by `pnpm arch:narrow-entrypoint`
 * from what the tree actually consumes, then proved by `pnpm packages:typecheck:agent`.
 */
export {
  AssetGenerationCapabilityFacade,
  buildEncounterAssetGenerationPlan,
  buildEncounterAssetGenerationPublicationTargets,
  buildEncounterWorkerMaterializationPlan,
  buildVisualQaRemediationWorkOrderPlans,
  createDeterministicAssetGenerationAdapter,
  createEncounterAssetGenerationQueueMessage,
  decodeAzureStorageQueueMessage,
  encodeAzureStorageQueueMessage,
  processEncounterAssetGenerationQueueMessage,
  processNextEncounterAssetGenerationQueueMessage,
} from "./asset-generation-jobs.js";
export type {
  AssetGenerationArtifactKind,
  AssetGenerationCapabilityId,
  AssetGenerationJobPolicyInput,
  AssetGenerationJobRecord,
  AzureStorageQueueEncounterAssetMessage,
  EncounterAssetGenerationPublicationTargets,
  EncounterAssetGenerationQueueClient,
  EncounterAssetGenerationQueueMessageEnvelope,
  EncounterAssetGenerationQueueProcessingResult,
  EncounterAssetGenerationWorkerExecution,
  EncounterExecutableAssetGenerationRequest,
  EncounterFactoryInputSummary,
  EncounterGenerationWorkOrder,
  EncounterGenerationWorkOrderTargetKind,
  EncounterHumanoidRealismProfile,
  EncounterHumanoidRealismRequirements,
  EncounterWorkerMaterializationPlan,
} from "./asset-generation-jobs.js";
export {
  createAzureStorageEncounterAssetGenerationQueueClientFromConnectionString,
} from "./azure-storage-queue-client.js";
export type {
  CapabilityProviderBinding,
  RuntimeProfile,
} from "./types.js";
export {
  buildOpenClinXrCapabilityRoutingMatrix,
} from "./routing-matrix.js";
export {
  evaluateCapabilityRoutingMatrix,
  evaluateRuntimeProviderReadinessSurface,
} from "./facade-and-readiness.js";
export {
  ACTOR_TURN_PLAN_CLAIM_SCOPE,
  ACTOR_TURN_PLAN_NOT_EVIDENCE_FOR,
  AUTHORED_LOCAL_FIXTURE_PROVIDER_ID,
  HIDDEN_TRUTH_REFUSAL_SPOKEN_TEXT,
  createDeterministicDialogueAdapter,
  resolveDeterministicActorTurnPlan,
} from "./deterministic-dialogue-adapter.js";
export type {
  AuthoredDialogueActor,
  AuthoredDialogueCatalog,
  AuthoredDialogueSeed,
  DeterministicDialogueRequestPayload,
  DialogueEmotion,
  DialogueSafetyExpectation,
  FrozenActorTurnPlan,
} from "./deterministic-dialogue-adapter.js";
