/**
 * Public interface of @openclinxr/capability-gateway.
 *
 * Named lists, not `export *`. A star republishes a module wholesale, so a symbol added inside
 * becomes public with nobody deciding it should be. Generated by `pnpm arch:narrow-entrypoint`
 * from what the tree actually consumes, then proved by `pnpm packages:typecheck:agent`.
 */

export type {
  AssetGenerationCapabilityId,
  AssetGenerationJobPolicyInput,
  AzureStorageQueueEncounterAssetMessage,
  EncounterAssetGenerationQueueClient,
  EncounterAssetGenerationQueueMessageEnvelope,
  EncounterAssetGenerationWorkerExecution,
  EncounterExecutableAssetGenerationRequest,
  EncounterHumanoidRealismRequirements,
} from "./asset-generation-jobs.js";
export {
  AssetGenerationCapabilityFacade,
  buildEncounterAssetGenerationPlan,
  buildEncounterAssetGenerationPublicationTargets,
  buildVisualQaRemediationWorkOrderPlans,
  createDeterministicAssetGenerationAdapter,
  createEncounterAssetGenerationQueueMessage,
  decodeAzureStorageQueueMessage,
  encodeAzureStorageQueueMessage,
  processEncounterAssetGenerationQueueMessage,
  processNextEncounterAssetGenerationQueueMessage,
} from "./asset-generation-jobs.js";
export type {
  AuthoredDialogueActor,
  AuthoredDialogueCatalog,
  AuthoredDialogueSeed,
  DeterministicDialogueRequestPayload,
  DialogueEmotion,
  DialogueSafetyExpectation,
  FrozenActorTurnPlan,
} from "./deterministic-dialogue-adapter.js";
export {
  AUTHORED_LOCAL_FIXTURE_PROVIDER_ID,
  createDeterministicDialogueAdapter,
  HIDDEN_TRUTH_REFUSAL_SPOKEN_TEXT,
  resolveDeterministicActorTurnPlan,
} from "./deterministic-dialogue-adapter.js";
export {
  evaluateCapabilityRoutingMatrix,
  evaluateRuntimeProviderReadinessSurface,
} from "./facade-and-readiness.js";
export {
  buildOpenClinXrCapabilityRoutingMatrix,
} from "./routing-matrix.js";
export type {
  RuntimeProfile,
} from "./types.js";
