import { type ProviderHealth, validateProviderHealth } from "@openclinxr/shared-schemas";
import type {
  RuntimeProfile,
  RuntimeProviderProfileKind,
  CapabilityId,
  ProviderKind,
  ImplementationLanguage,
  CapabilityTransport,
  NetworkExposure,
  CapabilityBindingStatus,
  CapabilityPlane,
  CapabilityProviderBinding,
  CapabilityRoutingMatrix,
  CapabilityRoutingReadiness,
  RuntimeProviderPlaneReadiness,
  RuntimeProviderReadinessSurface,
  ProviderGateDomain,
  ProviderGatePath,
  ProviderGateMetadata,
  RuntimeCapabilityRequest,
  RuntimeCapabilityAdapter,
} from "./types.js";
import {
  buildProviderGateMetadata,
  providerGate,
  recommendedNextActionForProviderGates,
  uniqueStrings,
  binding,
  summarizeProviderPlane,
  capabilityIdsByStatus,
  planeForCapability,
  facadeForCapability,
  executableWorkerControls,
} from "./internal.js";

export function buildOpenClinXrCapabilityRoutingMatrix(): CapabilityRoutingMatrix {
  const requiredCapabilities: CapabilityId[] = [
    "model-dialogue",
    "scenario-generation",
    "speech-recognition",
    "voice-synthesis",
    "adversarial-visual-review",
    "character-generation",
    "voice-asset-generation",
    "medical-equipment-generation",
    "animation-generation",
    "asset-bake",
    "persistence",
    "vector-index",
  ];
  const profiles: RuntimeProfile[] = ["local-development", "local-production", "production"];

  return {
    publicIngress: {
      strategy: "single-main-api-endpoint",
      allowedExternalEndpoint: "apps/api",
      internalServices: [
        "python-capability-worker",
        "asset-executable-worker",
        "local-model-runtime",
        "local-voice-runtime",
      ],
    },
    requiredCapabilities,
    profiles,
    bindings: [
      binding("local-development", "model-dialogue", "mock-model", "deterministic-mock", {
        implementationLanguage: "typescript",
        transport: "in-process",
        networkExposure: "none",
        status: "ready",
        notes: "Deterministic actor dialogue for CI and development without model downloads.",
      }),
      binding("local-development", "scenario-generation", "mock-scenario-generator", "deterministic-mock", {
        implementationLanguage: "typescript",
        transport: "in-process",
        networkExposure: "none",
        status: "ready",
        notes: "Deterministic draft generation until local or cloud models are deliberately enabled.",
      }),
      binding("local-development", "speech-recognition", "mock-transcript", "deterministic-mock", {
        implementationLanguage: "typescript",
        transport: "in-process",
        networkExposure: "none",
        status: "ready",
        notes: "Typed or fixture transcript path for repeatable station tests.",
      }),
      binding("local-development", "voice-synthesis", "mock-voice", "deterministic-mock", {
        implementationLanguage: "typescript",
        transport: "in-process",
        networkExposure: "none",
        status: "ready",
        notes: "Deterministic audio event stream with no local voice model execution.",
      }),
      binding("local-development", "adversarial-visual-review", "deterministic-visual-reviewer", "deterministic-mock", {
        implementationLanguage: "typescript",
        transport: "in-process",
        networkExposure: "none",
        status: "ready",
        notes: "Deterministic visual-review fixtures convert known screenshot findings into remediation refs without external models.",
      }),
      binding("local-development", "character-generation", "python-character-worker", "python-worker", {
        implementationLanguage: "python",
        transport: "main-api-tunnel",
        networkExposure: "single-main-api-external",
        endpointPath: "/internal/capabilities/character-generation/jobs",
        executableDependencies: ["python", "blender"],
        requiredControls: executableWorkerControls(),
        status: "planned",
        notes: "Generates character manifests and source assets asynchronously through the main API facade.",
      }),
      binding("local-development", "voice-asset-generation", "python-voice-asset-worker", "python-worker", {
        implementationLanguage: "python",
        transport: "main-api-tunnel",
        networkExposure: "single-main-api-external",
        endpointPath: "/internal/capabilities/voice-asset-generation/jobs",
        executableDependencies: ["python", "ffmpeg"],
        requiredControls: executableWorkerControls(),
        status: "planned",
        notes: "Generates approved prerecorded voice assets, not live interactive dialogue.",
      }),
      binding("local-development", "medical-equipment-generation", "python-equipment-worker", "python-worker", {
        implementationLanguage: "python",
        transport: "main-api-tunnel",
        networkExposure: "single-main-api-external",
        endpointPath: "/internal/capabilities/medical-equipment-generation/jobs",
        executableDependencies: ["python", "blender"],
        requiredControls: executableWorkerControls(),
        status: "planned",
        notes: "Generates reviewable equipment meshes and manifests for scenario environments.",
      }),
      binding("local-development", "medical-equipment-generation", "hunyuan3d-local", "python-worker", {
        implementationLanguage: "python",
        transport: "local-executable-worker",
        networkExposure: "none",
        executableDependencies: ["python", "blender"],
        requiredControls: [...executableWorkerControls(), "local_model_license_review", "shared_asset_library_lru_lookup"],
        status: "blocked",
        notes: "Planned local/open-source Hunyuan3D trial route for non-humanoid equipment and room props; disabled until install, license, cache, and runtime evidence exist.",
      }),
      binding("local-development", "animation-generation", "blender-animation-worker", "native-executable-worker", {
        implementationLanguage: "native-executable",
        transport: "main-api-tunnel",
        networkExposure: "single-main-api-external",
        endpointPath: "/internal/capabilities/animation-generation/jobs",
        executableDependencies: ["blender"],
        requiredControls: executableWorkerControls(),
        status: "planned",
        notes: "Generates and retargets animation clips for actors and clinical equipment.",
      }),
      binding("local-development", "asset-bake", "blender-bake-worker", "native-executable-worker", {
        implementationLanguage: "native-executable",
        transport: "main-api-tunnel",
        networkExposure: "single-main-api-external",
        endpointPath: "/internal/capabilities/asset-bake/jobs",
        executableDependencies: ["blender", "gltf-pipeline"],
        requiredControls: executableWorkerControls(),
        status: "planned",
        notes: "Bakes and optimizes generated assets outside request handlers.",
      }),
      binding("local-development", "persistence", "mongodb-memory-server", "local-database", {
        implementationLanguage: "typescript",
        transport: "main-api-facade",
        networkExposure: "none",
        requiredControls: ["dev_only", "test_seeded", "no_external_network"],
        status: "ready",
        notes: "Ephemeral Mongo-compatible store for local tests and demos.",
      }),
      binding("local-development", "vector-index", "local-memory-vector-index", "deterministic-mock", {
        implementationLanguage: "typescript",
        transport: "in-process",
        networkExposure: "none",
        status: "ready",
        notes: "Small deterministic vector-index substitute until persistence-backed retrieval is wired.",
      }),
      binding("local-production", "model-dialogue", "local-qwen-or-deepseek", "local-runtime", {
        implementationLanguage: "typescript",
        transport: "internal-sidecar-http",
        networkExposure: "internal-only",
        requiredControls: ["explicit_model_id", "license_record", "local_benchmark", "operator_enabled"],
        status: "not-configured",
        notes: "Local Apple Silicon model runtime behind the same model gateway contract.",
      }),
      binding("local-production", "scenario-generation", "local-qwen-or-deepseek", "local-runtime", {
        implementationLanguage: "typescript",
        transport: "internal-sidecar-http",
        networkExposure: "internal-only",
        requiredControls: ["explicit_model_id", "license_record", "local_benchmark", "operator_enabled"],
        status: "not-configured",
        notes: "Uses the same local model runtime for draft scenario generation when enabled.",
      }),
      binding("local-production", "speech-recognition", "local-speech-runtime", "local-runtime", {
        implementationLanguage: "typescript",
        transport: "internal-sidecar-http",
        networkExposure: "internal-only",
        requiredControls: ["medical_vocabulary_wer", "streaming_latency_benchmark", "operator_enabled"],
        status: "not-configured",
        notes: "Local ASR can swap in without changing station runtime code.",
      }),
      binding("local-production", "voice-synthesis", "local-vibevoice-provider", "local-runtime", {
        implementationLanguage: "typescript",
        transport: "internal-sidecar-http",
        networkExposure: "internal-only",
        requiredControls: ["voice_safety_review", "first_audio_latency_benchmark", "operator_enabled"],
        status: "not-configured",
        notes: "Interactive local voice provider swaps remain behind the voice gateway and separate from asset-generation workers.",
      }),
      binding("local-production", "adversarial-visual-review", "local-vlm-adversarial-reviewer", "local-runtime", {
        implementationLanguage: "typescript",
        transport: "internal-sidecar-http",
        networkExposure: "internal-only",
        requiredControls: ["model_license_review", "screenshot_video_evidence_policy", "operator_enabled", "claim_boundary_enforced"],
        status: "not-configured",
        notes: "Local VLM adversarial reviewer candidate for screenshots/videos; no model execution until local model evidence and policy controls exist.",
      }),
      binding("local-production", "character-generation", "python-character-worker", "python-worker", {
        implementationLanguage: "python",
        transport: "main-api-tunnel",
        networkExposure: "single-main-api-external",
        endpointPath: "/internal/capabilities/character-generation/jobs",
        executableDependencies: ["python", "blender"],
        requiredControls: executableWorkerControls(),
        status: "planned",
        notes: "Local workstation asset generation remains asynchronous and facade-routed.",
      }),
      binding("local-production", "voice-asset-generation", "python-voice-asset-worker", "python-worker", {
        implementationLanguage: "python",
        transport: "main-api-tunnel",
        networkExposure: "single-main-api-external",
        endpointPath: "/internal/capabilities/voice-asset-generation/jobs",
        executableDependencies: ["python", "ffmpeg"],
        requiredControls: executableWorkerControls(),
        status: "planned",
        notes: "Production-like local generation of approved voice assets remains asynchronous and review-gated.",
      }),
      binding("local-production", "medical-equipment-generation", "python-equipment-worker", "python-worker", {
        implementationLanguage: "python",
        transport: "main-api-tunnel",
        networkExposure: "single-main-api-external",
        endpointPath: "/internal/capabilities/medical-equipment-generation/jobs",
        executableDependencies: ["python", "blender"],
        requiredControls: executableWorkerControls(),
        status: "planned",
        notes: "Local equipment generation can use Python and Blender while staying inside the main API facade.",
      }),
      binding("local-production", "medical-equipment-generation", "hunyuan3d-local", "python-worker", {
        implementationLanguage: "python",
        transport: "local-executable-worker",
        networkExposure: "none",
        executableDependencies: ["python", "blender"],
        requiredControls: [...executableWorkerControls(), "local_model_license_review", "shared_asset_library_lru_lookup"],
        status: "blocked",
        notes: "Local Hunyuan3D route for reusable equipment/room prop generation; disabled until installation, license, cache, and runtime evidence are attached.",
      }),
      binding("local-production", "animation-generation", "blender-animation-worker", "native-executable-worker", {
        implementationLanguage: "native-executable",
        transport: "main-api-tunnel",
        networkExposure: "single-main-api-external",
        endpointPath: "/internal/capabilities/animation-generation/jobs",
        executableDependencies: ["blender"],
        requiredControls: executableWorkerControls(),
        status: "planned",
        notes: "Local animation generation remains a batch pipeline separate from live station interaction.",
      }),
      binding("local-production", "asset-bake", "blender-bake-worker", "native-executable-worker", {
        implementationLanguage: "native-executable",
        transport: "main-api-tunnel",
        networkExposure: "single-main-api-external",
        endpointPath: "/internal/capabilities/asset-bake/jobs",
        executableDependencies: ["blender", "gltf-pipeline"],
        requiredControls: executableWorkerControls(),
        status: "planned",
        notes: "Asset baking may run on the M4 workstation but should not widen the public API surface.",
      }),
      binding("local-production", "persistence", "local-mongodb", "local-database", {
        implementationLanguage: "typescript",
        transport: "main-api-facade",
        networkExposure: "internal-only",
        requiredControls: ["connection_string_secret", "migration_check", "backup_policy"],
        status: "not-configured",
        notes: "Local durable MongoDB instance for production-like single-user runs.",
      }),
      binding("local-production", "vector-index", "local-mongodb-vector-index", "local-database", {
        implementationLanguage: "typescript",
        transport: "main-api-facade",
        networkExposure: "internal-only",
        requiredControls: ["index_versioning", "embedding_model_record", "rebuild_job"],
        status: "planned",
        notes: "Mongo-compatible vector index or adjacent local vector store behind repository contracts.",
      }),
      binding("production", "model-dialogue", "grok-reasoning-provider", "paid-cloud-provider", {
        implementationLanguage: "managed-service",
        transport: "outbound-provider-api",
        networkExposure: "outbound-provider-only",
        requiredControls: ["procurement_review", "phi_policy", "cost_budget", "model_trace_provenance"],
        status: "planned",
        notes: "Production model provider remains an outbound server-side adapter behind the model gateway.",
      }),
      binding("production", "scenario-generation", "grok-reasoning-provider", "paid-cloud-provider", {
        implementationLanguage: "managed-service",
        transport: "outbound-provider-api",
        networkExposure: "outbound-provider-only",
        requiredControls: ["procurement_review", "case_review_required", "model_trace_provenance"],
        status: "planned",
        notes: "Scenario generation output must still pass clinical, psychometric, legal, and simulation review.",
      }),
      binding("production", "speech-recognition", "grok-voice-provider", "paid-cloud-provider", {
        implementationLanguage: "managed-service",
        transport: "outbound-provider-api",
        networkExposure: "outbound-provider-only",
        requiredControls: ["procurement_review", "medical_vocabulary_wer", "transcript_redaction_policy"],
        status: "planned",
        notes: "Production STT can switch providers without touching WebXR station logic.",
      }),
      binding("production", "voice-synthesis", "grok-voice-provider", "paid-cloud-provider", {
        implementationLanguage: "managed-service",
        transport: "outbound-provider-api",
        networkExposure: "outbound-provider-only",
        requiredControls: ["procurement_review", "voice_safety_review", "latency_slo"],
        status: "planned",
        notes: "Production TTS is provider-swappable through the voice gateway.",
      }),
      binding("production", "adversarial-visual-review", "vlm-adversarial-reviewer-requires-approval", "paid-cloud-provider", {
        implementationLanguage: "managed-service",
        transport: "outbound-provider-api",
        networkExposure: "outbound-provider-only",
        requiredControls: ["procurement_review", "phi_policy", "cost_budget", "screenshot_video_redaction", "claim_boundary_enforced"],
        status: "blocked",
        notes: "Cloud VLM adversarial review candidate for screenshot/video realism critique; blocked until explicit approval, privacy review, and cost controls.",
      }),
      binding("production", "character-generation", "python-character-worker", "python-worker", {
        implementationLanguage: "python",
        transport: "main-api-tunnel",
        networkExposure: "single-main-api-external",
        endpointPath: "/internal/capabilities/character-generation/jobs",
        executableDependencies: ["python", "blender"],
        requiredControls: executableWorkerControls(),
        status: "planned",
        notes: "Internal production worker for generated character assets and manifests.",
      }),
      binding("production", "character-generation", "meshy-cloud-requires-approval", "paid-cloud-provider", {
        implementationLanguage: "managed-service",
        transport: "outbound-provider-api",
        networkExposure: "outbound-provider-only",
        requiredControls: ["procurement_review", "paid_api_budget", "asset_license_review", "credential_secret", "shared_asset_library_lru_lookup", "human_review_before_learner_use"],
        status: "blocked",
        notes: "Meshy cloud candidate for humanoid mesh/rigging/basic animation experiments; blocked until explicit approval, credentials, budget, and license review.",
      }),
      binding("production", "character-generation", "tripo-cloud-requires-approval", "paid-cloud-provider", {
        implementationLanguage: "managed-service",
        transport: "outbound-provider-api",
        networkExposure: "outbound-provider-only",
        requiredControls: ["procurement_review", "paid_api_budget", "asset_license_review", "credential_secret", "shared_asset_library_lru_lookup", "human_review_before_learner_use"],
        status: "blocked",
        notes: "Tripo cloud candidate for fast draft props/reference-image-to-3D comparisons; blocked until explicit approval and license/cost controls.",
      }),
      binding("production", "voice-asset-generation", "python-voice-asset-worker", "python-worker", {
        implementationLanguage: "python",
        transport: "main-api-tunnel",
        networkExposure: "single-main-api-external",
        endpointPath: "/internal/capabilities/voice-asset-generation/jobs",
        executableDependencies: ["python", "ffmpeg"],
        requiredControls: executableWorkerControls(),
        status: "planned",
        notes: "Internal production worker for reviewable voice assets; live TTS remains in the voice gateway.",
      }),
      binding("production", "medical-equipment-generation", "python-equipment-worker", "python-worker", {
        implementationLanguage: "python",
        transport: "main-api-tunnel",
        networkExposure: "single-main-api-external",
        endpointPath: "/internal/capabilities/medical-equipment-generation/jobs",
        executableDependencies: ["python", "blender"],
        requiredControls: executableWorkerControls(),
        status: "planned",
        notes: "Internal production worker for medical-equipment meshes, colliders, and provenance manifests.",
      }),
      binding("production", "medical-equipment-generation", "hunyuan3d-local-or-managed-requires-review", "python-worker", {
        implementationLanguage: "python",
        transport: "main-api-tunnel",
        networkExposure: "single-main-api-external",
        endpointPath: "/internal/capabilities/medical-equipment-generation/jobs/hunyuan3d",
        executableDependencies: ["python", "blender"],
        requiredControls: [...executableWorkerControls(), "model_license_review", "shared_asset_library_lru_lookup", "human_review_before_learner_use"],
        status: "blocked",
        notes: "Hunyuan3D candidate for reusable medical equipment/room prop generation; blocked until license, runtime, and deployment posture are reviewed.",
      }),
      binding("production", "animation-generation", "blender-animation-worker", "native-executable-worker", {
        implementationLanguage: "native-executable",
        transport: "main-api-tunnel",
        networkExposure: "single-main-api-external",
        endpointPath: "/internal/capabilities/animation-generation/jobs",
        executableDependencies: ["blender"],
        requiredControls: executableWorkerControls(),
        status: "planned",
        notes: "Internal production worker for Speech2Motion, Mesh2Motion, retargeting, and authored animation clips.",
      }),
      binding("production", "asset-bake", "blender-bake-worker", "native-executable-worker", {
        implementationLanguage: "native-executable",
        transport: "main-api-tunnel",
        networkExposure: "single-main-api-external",
        endpointPath: "/internal/capabilities/asset-bake/jobs",
        executableDependencies: ["blender", "gltf-pipeline"],
        requiredControls: executableWorkerControls(),
        status: "planned",
        notes: "Internal asset pipeline worker; outputs versioned GLB/KTX2/meshopt artifacts.",
      }),
      binding("production", "persistence", "microsoft-documentdb", "managed-database", {
        implementationLanguage: "managed-service",
        transport: "main-api-facade",
        networkExposure: "internal-only",
        requiredControls: ["private_networking", "backup_policy", "migration_check", "audit_logging"],
        status: "planned",
        notes: "Mongo-compatible production persistence behind repository contracts.",
      }),
      binding("production", "vector-index", "documentdb-vector-index", "managed-database", {
        implementationLanguage: "managed-service",
        transport: "main-api-facade",
        networkExposure: "internal-only",
        requiredControls: ["index_versioning", "embedding_model_record", "rebuild_job", "audit_logging"],
        status: "planned",
        notes: "Production vector/retrieval index remains hidden behind repository and memory contracts.",
      }),
    ],
  };
}

