/**
 * Public interface of @openclinxr/agent-loop.
 *
 * Named lists, not `export *`. A star republishes a module wholesale, so a symbol added inside
 * becomes public with nobody deciding it should be. Generated by `pnpm arch:narrow-entrypoint`
 * from what the tree actually consumes, then proved by `pnpm packages:typecheck:agent`.
 */

export {
  recommendBackgroundAgentModel,
} from "./model-recommendation.js";

export {
  createAgentDispatchPackets,
  createAgentLoopPlan,
  normalizeLegacyScorecard,
  serializeAgentLoopPlan,
} from "./plan.js";
export type {
  AgentMemoryEntry,
} from "./types.js";
