/**
 * Public interface of @openclinxr/agent-loop.
 *
 * Named lists, not `export *`. A star republishes a module wholesale, so a symbol added inside
 * becomes public with nobody deciding it should be. Generated by `pnpm arch:narrow-entrypoint`
 * from what the tree actually consumes, then proved by `pnpm packages:typecheck:agent`.
 */
export {
  scoreWeights,
} from "./types.js";
export type {
  AgentLoopPlan,
  AgentMemoryEntry,
  LegacyScorecard,
  NextAction,
  ScoreDimension,
} from "./types.js";
export {
  role,
} from "./roster.js";
export {
  createAgentDispatchPackets,
  createAgentLoopPlan,
  normalizeLegacyScorecard,
  serializeAgentLoopPlan,
} from "./plan.js";
export {
  recommendBackgroundAgentModel,
} from "./model-recommendation.js";
export {
  PREFERRED_CLI_SOFT_WARN,
  allowedToolsForRole,
  disallowedToolsForRole,
  getRepoRoleHarnessPolicy,
  repoRoleHarnessPolicies,
  resolveHarnessModelSpec,
  shouldRecommendMoonbridgeAssist,
} from "./role-harness-policy.js";
export type {
  RepoRoleHarnessPolicy,
  RepoWorkflowSkillId,
} from "./role-harness-policy.js";
export {
  GROK_TIER_PACKAGE_SCRIPTS,
  buildGrokTierIntrospectionReport,
  buildGrokTierWorkOrder,
  evaluateGrokDelegationAdvice,
  evaluateGrokTierUpgrade,
  formatGrokTierIntrospectionBrief,
  formatGrokTierRecordLine,
  recommendGrokStartTier,
  validateGrokHarnessTierConfig,
} from "./grok-tier-routing.js";
export type {
  GrokDelegationIntent,
  GrokTierId,
} from "./grok-tier-routing.js";
export {
  buildGrokSliceTokenBaseline,
  buildGrokSliceTokenIntrospectionReport,
  formatGrokSliceTokenBrief,
  parseCcusageDailyPayload,
} from "./grok-token-introspection.js";
export type {
  GrokSessionTokenSnapshot,
  GrokSliceTokenBaseline,
} from "./grok-token-introspection.js";
export {
  DONE_WHEN_RULE_VOCABULARY,
  buildSliceTeamSpawnPrompt,
  buildTeamSpawnReport,
  formatTeamSpawnBrief,
  isKnownDoneWhenRule,
  materializeBriefFromTemplate,
  sliceBriefPath,
  sliceHandoffPath,
  sliceRootDir,
  verifySliceBrief,
} from "./slice-team.js";
export type {
  SliceBrief,
  SliceHandoff,
  SliceTeamTemplate,
} from "./slice-team.js";
export {
  WORKER_PLANTED_CONTRACT_DIRECTIVE,
  WORKER_TONE_DIRECTIVE,
  buildGrokRepoAgentSpawnRegistry,
  buildGrokRepoAgentSpawnSpec,
  buildRepoAgentSpawnPrompt,
  formatGrokRepoAgentSpawnBrief,
  recommendRepoAgentsForConsult,
  requiresMultimodalReasoning,
  resolveGrokSpawnSurfaceForPolicy,
} from "./grok-repo-agent-spawn.js";
export {
  assertWriterIsolation,
  buildParentSpawnChecklist,
} from "./spawn-isolation.js";
